# Generated by Django 3.1.13 on 2021-11-29 10:47

from django.db import migrations, models
import django.db.models.deletion
import payments.order_numbers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation_units', '0030_reservation_unit_price_and_unit'),
        ('reservations', '0016_reservation_confirmed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('created', 'created'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='created', max_length=32, verbose_name='state')),
                ('order_number', models.CharField(default=payments.order_numbers.generate_order_number, max_length=64, unique=True, verbose_name='order number')),
                ('verkkokauppa_order_id', models.UUIDField(unique=True)),
                ('payment_url', models.URLField(verbose_name='payment URL')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='reservations.reservation', verbose_name='reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verkkokauppa_product_id', models.UUIDField(unique=True)),
                ('reservation_unit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='reservation_units.reservationunit', verbose_name='Reservation unit')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='payments.order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='payments.product', verbose_name='product')),
            ],
        ),
    ]
