# Generated by Django 3.2.15 on 2022-08-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reservation_notification',
            field=models.CharField(choices=[('all', 'All'), ('only_handling_required', 'Only Handling Required'), ('none', 'None')], default='none', help_text='When user wants to receive reservation notification emails.', max_length=32, verbose_name='Reservation notification'),
        ),
    ]
