# Generated by Django 3.2.15 on 2022-10-07 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfoViewLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(editable=False, max_length=255)),
                ('viewer_username', models.CharField(max_length=255)),
                ('access_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_info_view_logs', to=settings.AUTH_USER_MODEL)),
                ('viewer_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_viewer_personal_info_view_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
