# Generated by Django 3.2.16 on 2023-02-19 16:48

from django.db import migrations, models
import uuid


def set_uuids_for_existing(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        user.tvp_uuid = uuid.uuid4()
        user.save(update_fields=['tvp_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_personalinfoviewlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tvp_uuid',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(set_uuids_for_existing, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='tvp_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=False),
        ),
    ]
