# Generated by Django 3.2.16 on 2023-02-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_tvp_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfoviewlog',
            name='viewer_user_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='personalinfoviewlog',
            name='viewer_user_full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
