# Generated by Django 3.2.18 on 2023-03-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_personalinfoviewlog_viewer_fullname_and_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
