# Generated by Django 3.2.18 on 2023-03-10 15:47

from django.db import migrations, models


def set_default_values(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(reservation_notification="none").update(
        reservation_notification="only_handling_required"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reservation_notification',
            field=models.CharField(choices=[('all', 'All'), ('only_handling_required', 'Only Handling Required'), ('none', 'None')], default='only_handling_required', help_text='When user wants to receive reservation notification emails.', max_length=32, verbose_name='Reservation notification'),
        ),
        migrations.RunPython(set_default_values, reverse_code=migrations.RunPython.noop),
    ]
