# Generated by Django 4.2.4 on 2023-10-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_reservation_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user', models.Model),
        ),
    ]
