# Generated by Django 4.2.10 on 2024-02-11 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_change_database_table_names"),
    ]

    operations = []
