# Generated by Django 4.2.7 on 2023-11-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_change_database_table_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                blank=True,
                choices=[("fi", "Finnish"), ("sv", "Swedish"), ("en", "English")],
                max_length=8,
                null=True,
                verbose_name="Preferred UI language",
            ),
        ),
    ]
