# Generated by Django 5.0.4 on 2024-04-08 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_proxyusersocialauth"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personalinfoviewlog",
            options={"base_manager_name": "objects", "ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"base_manager_name": "objects", "ordering": ["pk"]},
        ),
    ]
