# Generated by Django 5.0.8 on 2024-08-26 22:44

from django.db import migrations


def anonymize_anonymized_users(apps, schema_editor):
    User = apps.get_model("users", "User")

    anonymized_users = User.objects.filter(email__icontains="@anonymized.net", is_active=False)
    for user in anonymized_users:
        user.profile_id = ""
        user.save()

        user.social_auth.all().delete()
        user.ad_groups.clear()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_delete_proxyusersocialauth"),
    ]

    operations = [
        migrations.RunPython(anonymize_anonymized_users, migrations.RunPython.noop),
    ]
