# Generated by Django 5.0.8 on 2024-08-26 22:44
import os

from django.contrib.sessions.backends.cache import KEY_PREFIX
from django.core.cache import cache
from django.db import migrations


def clear_sessions(apps, schema_editor):
    if os.getenv("DJANGO_SETTINGS_ENVIRONMENT") != "AutomatedTests":
        cache.delete_many(cache.keys(f"{KEY_PREFIX}*"))


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_anonymize"),
    ]

    operations = [
        migrations.RunPython(clear_sessions, migrations.RunPython.noop),
    ]
