# Generated by Django 5.1.1 on 2024-09-26 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_clear_sessions"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="personalinfoviewlog",
                    name="user",
                ),
                migrations.RemoveField(
                    model_name="personalinfoviewlog",
                    name="viewer_user",
                ),
                migrations.RemoveField(
                    model_name="user",
                    name="ad_groups",
                ),
                migrations.RemoveField(
                    model_name="user",
                    name="groups",
                ),
                migrations.RemoveField(
                    model_name="user",
                    name="user_permissions",
                ),
                migrations.DeleteModel(
                    name="ProfileUser",
                ),
                migrations.DeleteModel(
                    name="PersonalInfoViewLog",
                ),
                migrations.DeleteModel(
                    name="User",
                ),
            ],
            database_operations=[],
        ),
    ]
