# Generated by Django 3.0.10 on 2020-11-20 12:59
import datetime

from django.core.exceptions import ValidationError
from django.db import migrations, models
from django.utils.text import format_lazy
from django.utils.translation import gettext_lazy as _


def year_not_in_future(year: int | None) -> None:
    from common.date_utils import DEFAULT_TIMEZONE

    if year is None:
        return

    current_date = datetime.datetime.now(tz=DEFAULT_TIMEZONE)

    if current_date.year < year:
        msg = _("is after current year")
        raise ValidationError(format_lazy("{year} {msg}", year=year, msg=msg))


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0003_application_periods"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="year_established",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[year_not_in_future],
                verbose_name="Year established",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="identifier",
            field=models.TextField(
                max_length=255,
                unique=True,
                verbose_name="Organisation identifier",
            ),
        ),
    ]
