# Generated by Django 3.0.10 on 2020-12-15 09:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0003_reservationunitimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0002_add_recurring_reservation_fields'),
        ('applications', '0004_fixed_organisation_year_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='description',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reservation_purpose',
        ),
        migrations.RemoveField(
            model_name='applicationevent',
            name='duration',
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='begin',
            field=models.DateField(default=datetime.datetime(2020, 12, 15, 9, 27, 53, 990937, tzinfo=utc), verbose_name='Start date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='biweekly',
            field=models.BooleanField(blank=True, default=False, verbose_name='Every second week only'),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='end',
            field=models.DateField(default=datetime.datetime(2021, 3, 25, 9, 28, 12, 456921, tzinfo=utc), verbose_name='End date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='events_per_week',
            field=models.PositiveIntegerField(default=1, verbose_name='Events per week'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='max_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Maximum duration'),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='min_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name='Minimum duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='name',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reservation_units.Purpose', verbose_name='Purpose'),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='applications.Person', verbose_name='Contact person'),
        ),
        migrations.AlterField(
            model_name='application',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='applications.Organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Applicant'),
        ),
        migrations.AlterField(
            model_name='applicationevent',
            name='ability_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.AbilityGroup', verbose_name='Ability group'),
        ),
        migrations.AlterField(
            model_name='applicationevent',
            name='age_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.AgeGroup', verbose_name='Age group'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='identifier',
            field=models.TextField(max_length=255, verbose_name='Organisation identifier'),
        ),
        migrations.CreateModel(
            name='EventReservationUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True, null=True, verbose_name='Priority')),
                ('application_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reservation_units', to='applications.ApplicationEvent', verbose_name='Application event')),
                ('reservation_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservation_units.ReservationUnit', verbose_name='Reservation unit')),
            ],
        ),
    ]
