# Generated by Django 3.0.10 on 2020-12-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_fixed_organisation_year_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='application',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='application',
            name='contact_first_name',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='application',
            name='contact_last_name',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='application',
            name='contact_phone_number',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Phone number'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
