# Generated by Django 3.0.10 on 2020-12-03 09:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0001_initial'),
        ('applications', '0005_auto_20201202_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='email',
        ),
        migrations.RemoveField(
            model_name='application',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='timeframe_start',
            field=models.TimeField(default=datetime.datetime(2020, 12, 3, 9, 16, 23, 87512, tzinfo=utc), verbose_name='Time frame end'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ApplicationReservationUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(100, 'Low'), (200, 'Medium'), (300, 'High')], default=200)),
                ('reservation_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservation_units.ReservationUnit', verbose_name='Reservation unit')),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='applications.ApplicationEvent', verbose_name='Application event')),
            ],
        ),
    ]
