# Generated by Django 3.0.10 on 2020-12-17 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_period_to_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationevent',
            name='num_events',
        ),
    ]
