# Generated by Django 3.0.10 on 2020-12-03 09:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20201203_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationevent',
            name='timeframe_end',
            field=models.TimeField(default=datetime.datetime(2020, 12, 3, 14, 17, 26, 771343, tzinfo=utc), verbose_name='Time frame end'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationevent',
            name='timeframe_start',
            field=models.TimeField(verbose_name='Time frame start'),
        ),
    ]
