# Generated by Django 3.0.10 on 2021-01-14 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_fix_verbose_name_typo'),
        ('applications', '0009_applicationstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationevent',
            name='ability_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.AbilityGroup', verbose_name='Ability group'),
        ),
        migrations.AlterField(
            model_name='applicationevent',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.AgeGroup', verbose_name='Age group'),
        ),
        migrations.AlterField(
            model_name='applicationevent',
            name='begin',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='applicationevent',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='applicationevent',
            name='events_per_week',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Events per week'),
        ),
        migrations.AlterField(
            model_name='applicationevent',
            name='min_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Minimum duration'),
        ),
        migrations.AlterField(
            model_name='applicationevent',
            name='name',
            field=models.TextField(blank=True, default='', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.TextField(blank=True, max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.TextField(blank=True, max_length=50, verbose_name='Last name'),
        ),
    ]
