# Generated by Django 3.0.10 on 2021-02-03 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_allow_null_for_application_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='applications.ApplicationPeriod', verbose_name='Applicantion period'),
        ),
    ]
