# Generated by Django 3.0.10 on 2021-02-02 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0011_add_new_application_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEventStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('allocating', 'Allocating'), ('allocated', 'Allocated'), ('validated', 'Validated'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], max_length=20, verbose_name='Status')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('application_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='applications.ApplicationEvent', verbose_name='Application event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
