# Generated by Django 3.0.10 on 2021-02-09 07:42

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0008_reservationunit_unit'),
        ('spaces', '0012_district_translations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0003_fix_verbose_name_typo'),
        ('applications', '0013_application_period_application_related_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('target_group', models.CharField(choices=[('internal', 'Internal'), ('public', 'Public'), ('all', 'All')], max_length=50, verbose_name='Target group')),
                ('application_period_begin', models.DateTimeField(verbose_name='Application round begin')),
                ('application_period_end', models.DateTimeField(verbose_name='Application round end')),
                ('reservation_period_begin', models.DateField(verbose_name='Reservation period begin')),
                ('reservation_period_end', models.DateField(verbose_name='Reservation period end')),
                ('public_display_begin', models.DateTimeField(verbose_name='Public display begin')),
                ('public_display_end', models.DateTimeField(verbose_name='Public display end')),
                ('purposes', models.ManyToManyField(blank=True, related_name='application_rounds', to='reservation_units.Purpose', verbose_name='Purposes')),
                ('reservation_units', models.ManyToManyField(related_name='application_rounds', to='reservation_units.ReservationUnit', verbose_name='Reservation units')),
                ('service_sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spaces.ServiceSector', verbose_name='Service sector')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationRoundBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('must_be_main_purpose_of_applicant', models.BooleanField(default=False, verbose_name='Must be main purpose of the applicant')),
                ('customer_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('business', 'Business'), ('nonprofit', 'Nonprofit'), ('individual', 'Individual')], max_length=50), size=None)),
                ('home_city', models.CharField(max_length=255)),
                ('allocation_percentage', models.PositiveSmallIntegerField(default=0, verbose_name='Allocation percentage')),
                ('age_groups', models.ManyToManyField(to='reservations.AgeGroup')),
                ('application_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_round_baskets', to='applications.ApplicationRound', verbose_name='Application round')),
                ('purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_round_baskets', to='reservation_units.Purpose', verbose_name='Purpose')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationRoundStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], max_length=20, verbose_name='Status')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('application_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='applications.ApplicationRound', verbose_name='Application round')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='application_period',
        ),
        migrations.DeleteModel(
            name='ApplicationPeriod',
        ),
        migrations.AddField(
            model_name='application',
            name='application_round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='applications.ApplicationRound', verbose_name='Applicantion period'),
            preserve_default=False,
        ),
    ]
