# Generated by Django 3.0.10 on 2021-02-12 07:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_applicationstatus_add_handled'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationroundbasket',
            name='order_number',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Order number'),
        ),
        migrations.AlterField(
            model_name='applicationroundbasket',
            name='customer_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('business', 'Business'), ('nonprofit', 'Nonprofit'), ('individual', 'Individual')], max_length=50, null=True), size=None),
        ),
    ]
