# Generated by Django 3.0.10 on 2021-02-12 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0017_application_billing_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationAggregateData",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("value", models.FloatField(max_length=255, verbose_name="Value")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aggregated_data",
                        to="applications.Application",
                    ),
                ),
            ],
            options={
                "db_table": "application_aggregate_data",
            },
        ),
    ]
