# Generated by Django 3.0.10 on 2021-02-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_organisation_active_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='core_business',
            field=models.TextField(blank=True, verbose_name='Core business of this organization'),
        ),
    ]
