# Generated by Django 3.0.10 on 2021-02-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_applicationaggregatedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='active_members',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Active members'),
        ),
    ]
