# Generated by Django 3.0.10 on 2021-02-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_application_applicant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='post_code',
            field=models.CharField(max_length=5, verbose_name='Post code'),
        ),
    ]
