# Generated by Django 3.0.10 on 2021-02-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_address_post_code_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='identifier',
            field=models.TextField(max_length=255, null=True, verbose_name='Organisation identifier'),
        ),
    ]
