# Generated by Django 3.0.10 on 2021-02-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_organisation_identifier_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('association', 'Association'), ('community', 'Community'), ('company', 'Company')], max_length=64, null=True, verbose_name='Applicant type'),
        ),
    ]
