# Generated by Django 3.0.10 on 2021-02-24 12:19

from django.db import migrations, models


def update_cached_statuses(apps, schema_editor):
    Application = apps.get_model("applications", "Application")
    ApplicationStatus = apps.get_model("applications", "ApplicationStatus")
    for application in Application.objects.all():
        latest_status = ApplicationStatus.objects.filter(application=application).last()
        application.cached_latest_status = latest_status.status
        application.save()


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_applicant_type_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cached_latest_status',
            field=models.CharField(blank=True, db_index=True, default='draft', max_length=20, verbose_name='Cached latest status'),
        ),
        migrations.RunPython(
            update_cached_statuses, reverse_code=lambda apps, schema_editor: None
        ),
    ]
