# Generated by Django 3.0.10 on 2021-03-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_application_cached_latest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationround',
            name='allocating',
            field=models.BooleanField(blank=True, default=False, verbose_name='Allocating'),
        ),
        migrations.AlterField(
            model_name='applicationroundstatus',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('review_done', 'Review done'), ('allocated', 'Allocated'), ('handled', 'Handled'), ('validated', 'Validated'), ('approved', 'Approved')], max_length=20, verbose_name='Status'),
        ),
    ]
