# Generated by Django 3.1.7 on 2021-03-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0025_organisation_organisation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationround',
            name='criteria',
            field=models.TextField(default=''),
        ),
    ]
