# Generated by Django 3.1.7 on 2021-03-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0026_applicationround_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationround',
            name='criteria_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='applicationround',
            name='criteria_fi',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='applicationround',
            name='criteria_sv',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='applicationround',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='applicationround',
            name='name_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='applicationround',
            name='name_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
