# Generated by Django 3.1.7 on 2021-04-08 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0028_organisation_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),

        migrations.AddField(
            model_name='application',
            name='home_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.city', verbose_name='Home city'),
        ),
        migrations.RunSQL("ALTER TABLE applications_applicationroundbasket RENAME COLUMN home_city to home_city_tmp"),
        migrations.RunSQL("INSERT INTO applications_city (name) select home_city_tmp from applications_applicationroundbasket where home_city_tmp is not null"),
        migrations.AddField(
            model_name='applicationroundbasket',
            name='home_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.city', verbose_name='Home city'),
        ),
        migrations.RunSQL(
            "update applications_applicationroundbasket set home_city_id = (select id from applications_city where name = home_city_tmp)"),
        migrations.RunSQL(
            "ALTER TABLE applications_applicationroundbasket drop column home_city_tmp"),
    ]
