# Generated by Django 3.1.7 on 2021-04-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0012_remove_reservationunitimage_image_url'),
        ('applications', '0029_application_and_basket_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationroundbasket',
            name='purpose',
        ),
        migrations.AddField(
            model_name='applicationroundbasket',
            name='purposes',
            field=models.ManyToManyField(to='reservation_units.Purpose', verbose_name='Purposes'),
        ),
    ]
