# Generated by Django 3.1.7 on 2021-04-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0013_reservationunit_uuid'),
        ('applications', '0030_basket_purposes_manytomany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationround',
            name='purposes',
            field=models.ManyToManyField(related_name='application_rounds', to='reservation_units.Purpose', verbose_name='Purposes'),
        ),
        migrations.AlterField(
            model_name='applicationroundbasket',
            name='purposes',
            field=models.ManyToManyField(blank=True, to='reservation_units.Purpose', verbose_name='Purposes'),
        ),
    ]
