# Generated by Django 3.1.7 on 2021-04-09 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0013_reservationunit_uuid'),
        ('applications', '0031_purpose_manytomany_fixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEventScheduleResult',
            fields=[
                ('application_event_schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='applications.applicationeventschedule')),
                ('allocated_duration', models.DurationField()),
                ('allocated_day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Day')),
                ('allocated_begin', models.TimeField(verbose_name='Start')),
                ('allocated_end', models.TimeField(verbose_name='End')),
                ('allocated_reservation_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_units.reservationunit')),
            ],
        ),
    ]
