# Generated by Django 3.1.8 on 2021-04-16 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0033_applicationeventscheduleresult_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
