# Generated by Django 3.1.8 on 2021-04-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0013_reservationunit_uuid'),
        ('applications', '0034_created_and_modified_field_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationevent',
            name='declined_reservation_units',
            field=models.ManyToManyField(to='reservation_units.ReservationUnit', verbose_name='Declined reservation units'),
        ),
    ]
