# Generated by Django 3.1.7 on 2021-04-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0034_created_and_modified_field_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationeventstatus',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('allocated', 'Allocated'), ('validated', 'Validated'), ('approved', 'Approved'), ('declined', 'Declined')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('review_done', 'Review done'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], max_length=20, verbose_name='Status'),
        ),
    ]
