# Generated by Django 3.1.8 on 2021-04-28 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0037_add_allocated_to_schedule_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEventWeeklyAmountReduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('application_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_amount_reductions', to='applications.applicationevent', verbose_name='Application event')),
                ('application_event_schedule_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.applicationeventscheduleresult', verbose_name='Application event schedule result')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
