# Generated by Django 3.1.8 on 2021-05-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0038_applicationevent_weekly_amount_reduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationeventscheduleresult',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
