# Generated by Django 3.1.7 on 2021-05-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0041_applicationeventscheduleresultaggregatedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationeventaggregatedata',
            name='value',
            field=models.FloatField(max_length=255, null=True, verbose_name='Value'),
        ),
    ]
