# Generated by Django 3.1.7 on 2021-05-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0042_applicationeventaggregatedata_value_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationaggregatedata',
            name='value',
            field=models.FloatField(default=0, max_length=255, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='applicationeventaggregatedata',
            name='value',
            field=models.FloatField(default=0, max_length=255, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='applicationeventscheduleresultaggregatedata',
            name='value',
            field=models.FloatField(default=0, max_length=255, null=True, verbose_name='Value'),
        ),
    ]
