# Generated by Django 3.1.7 on 2021-05-10 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0043_aggregatedata_base_model_value_field_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRoundAggregateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('value', models.FloatField(default=0, max_length=255, null=True, verbose_name='Value')),
                ('application_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_data', to='applications.applicationround')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
