# Generated by Django 3.1.8 on 2021-05-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0044_applicationroundaggregatedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatus',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('review_done', 'Review done'), ('sent', 'Decision sent'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], max_length=20, verbose_name='Status'),
        ),
    ]
