# Generated by Django 3.1.8 on 2021-05-14 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0046_change_application_aggregate_data_key_names'),
    ]

    def create_uuid(apps, schema_editor):
        ApplicationEvent = apps.get_model('applications', 'ApplicationEvent')
        for event in ApplicationEvent.objects.all():
            event.uuid = uuid.uuid4()
            event.save()

    operations = [
        migrations.AddField(
            model_name='applicationevent',
            name='uuid',
            field=models.UUIDField(editable=False, unique=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='applicationevent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=False),
        ),
    ]
