# Generated by Django 3.1.13 on 2021-10-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0048_blanks_and_nulls'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city_en',
            field=models.TextField(max_length=80, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='address',
            name='city_fi',
            field=models.TextField(max_length=80, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='address',
            name='city_sv',
            field=models.TextField(max_length=80, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='address',
            name='street_address_en',
            field=models.TextField(max_length=80, null=True, verbose_name='Street address'),
        ),
        migrations.AddField(
            model_name='address',
            name='street_address_fi',
            field=models.TextField(max_length=80, null=True, verbose_name='Street address'),
        ),
        migrations.AddField(
            model_name='address',
            name='street_address_sv',
            field=models.TextField(max_length=80, null=True, verbose_name='Street address'),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='name_en',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='name_fi',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='name_sv',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='applicationroundbasket',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='applicationroundbasket',
            name='name_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='applicationroundbasket',
            name='name_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_fi',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_sv',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='core_business_en',
            field=models.TextField(blank=True, null=True, verbose_name='Core business of this organization'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='core_business_fi',
            field=models.TextField(blank=True, null=True, verbose_name='Core business of this organization'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='core_business_sv',
            field=models.TextField(blank=True, null=True, verbose_name='Core business of this organization'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='name_en',
            field=models.TextField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='name_fi',
            field=models.TextField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='name_sv',
            field=models.TextField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
