# Generated by Django 3.1.13 on 2021-11-11 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_delete_old_reservation_purpose'),
        ('applications', '0049_missing_translated_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationevent',
            name='purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reservations.reservationpurpose', verbose_name='Reservation purpose'),
        ),
        migrations.AlterField(
            model_name='applicationround',
            name='purposes',
            field=models.ManyToManyField(related_name='application_rounds', to='reservations.ReservationPurpose', verbose_name='Reservation purposes'),
        ),
        migrations.AlterField(
            model_name='applicationroundbasket',
            name='purposes',
            field=models.ManyToManyField(blank=True, to='reservations.ReservationPurpose', verbose_name='Reservation purposes'),
        ),
    ]
