# Generated by Django 3.2.12 on 2022-02-28 11:47

from django.db import migrations, models


def forwards(apps, schema_editor):
    ApplicationEventSchedule = apps.get_model(
        "applications", "ApplicationEventSchedule"
    )
    db_alias = schema_editor.connection.alias

    # At the time of writing, PRIORITY_HIGH was set to 300.
    # This is hardcoded here as referencing the choice class might change
    # some time in the future.
    ApplicationEventSchedule.objects.using(db_alias).all().update(priority=300)


def backwards(apps, schema_editor):
    ApplicationEventSchedule = apps.get_model(
        "applications", "ApplicationEventSchedule"
    )
    db_alias = schema_editor.connection.alias

    # At the time of writing, the default was set to PRIORITY_MEDIUM (200).
    # This is hardcoded here as referencing the choice class might change
    # some time in the future.
    ApplicationEventSchedule.objects.using(db_alias).all().update(priority=200)


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0052_alter_organisation_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationeventschedule",
            name="priority",
            field=models.IntegerField(
                choices=[(100, "Low"), (200, "Medium"), (300, "High")], default=300
            ),
        ),
        migrations.RunPython(forwards, backwards, elidable=True),
    ]
