# Generated by Django 3.2.12 on 2022-03-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0053_alter_applicationeventschedule_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='additional_information',
            field=models.TextField(blank=True, help_text='Additional information about the application', null=True, verbose_name='Additional information'),
        ),
    ]
