# Generated by Django 3.2.12 on 2022-03-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0054_application_additional_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='post_code',
            field=models.CharField(max_length=32, verbose_name='Post code'),
        ),
    ]
