# Generated by Django 3.2.13 on 2022-06-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0055_alter_address_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationroundstatus',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('review_done', 'Review done'), ('allocated', 'Allocated'), ('reserving', 'Reserving'), ('handled', 'Handled'), ('sending', 'Sending'), ('sent', 'Sent'), ('archived', 'Archived')], max_length=20, verbose_name='Status'),
        ),
    ]
