# Generated by Django 3.2.13 on 2022-04-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0055_alter_address_post_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationevent',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='applicationeventstatus',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='applicationeventweeklyamountreduction',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='applicationroundstatus',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='applicationstatus',
            options={'ordering': ('id',)},
        ),
    ]
