# Generated by Django 3.2.13 on 2022-06-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0056_alter_applicationroundstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatus',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('received', 'Received'), ('in_review', 'In review'), ('review_done', 'Review done'), ('allocated', 'Allocated'), ('handled', 'Handled'), ('sent', 'Decision sent'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], max_length=20, verbose_name='Status'),
        ),
    ]
