# Generated by Django 3.2.13 on 2022-06-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0057_alter_applicationstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationeventstatus',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('reserved', 'Reserved'), ('failed', 'Failed'), ('declined', 'Declined')], max_length=20, verbose_name='Status'),
        ),
    ]
