# Generated by Django 3.2.13 on 2022-06-15 03:17

from django.db import migrations

from applications.models import ApplicationStatus


def change_status_to_new(*args, **kwargs):
    ApplicationStatus.objects.filter(status="declined").update(status="handled")


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0059_change_application_round_status_values"),
    ]

    # Rolling back to original values is not possible because
    # we can't assume that all 'handled' applications are 'declined'
    operations = [migrations.RunPython(change_status_to_new, migrations.RunPython.noop)]
