# Generated by Django 3.2.13 on 2022-06-15 03:21

from django.db import migrations

from applications.models import ApplicationEventStatus

OLD_STATUS_VALUES = ["allocated", "validated"]
NEW_STATUS_VALUES = ["approved", "approved"]


def change_status_to_new(*args, **kwargs):
    for new, old in zip(NEW_STATUS_VALUES, OLD_STATUS_VALUES):
        ApplicationEventStatus.objects.filter(status=old).update(status=new)


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0060_change_application_status_values"),
    ]

    # Rolling back to original values is not possible because both 'allocated' and 'validated' are updated to 'approved'
    # We can't set all 'approved' rows back to 'allocated' or 'validated'
    operations = [migrations.RunPython(change_status_to_new, migrations.RunPython.noop)]
