# Generated by Django 3.2.13 on 2022-08-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0061_change_application_event_status_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationevent',
            name='flagged',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is the event flagged'),
        ),
    ]
