# Generated by Django 3.2.16 on 2023-02-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0062_applicationevent_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='municipality_code',
            field=models.CharField(default='', max_length=30, verbose_name='Municipality code'),
        ),
    ]
