# Generated by Django 3.2.18 on 2023-04-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0063_city_municipality_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('association', 'Association'), ('community', 'Community'), ('company', 'Company')], db_index=True, max_length=64, null=True, verbose_name='Applicant type'),
        ),
    ]
