# Generated by Django 4.2.6 on 2023-10-25 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0066_remove_applicationaggregatedata_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationevent',
            name='declined_reservation_units',
        ),
    ]
