# Generated by Django 4.2.6 on 2023-10-20 12:16

from django.db import migrations


def convert_enums_to_upper_case(apps, schema_editor):
    Application = apps.get_model("applications", "Application")
    for application in Application.objects.all():
        if application.applicant_type is not None:
            application.applicant_type = application.applicant_type.upper()
            application.save()

    Organisation = apps.get_model("applications", "Organisation")
    for organisation in Organisation.objects.all():
        if organisation.organisation_type is not None:
            organisation.organisation_type = organisation.organisation_type.upper()
            organisation.save()


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0070_application_working_memo"),
    ]

    operations = [
        migrations.RunPython(convert_enums_to_upper_case, migrations.RunPython.noop),
    ]
