# Generated by Django 4.2.6 on 2023-10-20 12:16

from django.db import migrations


def convert_enums_to_upper_case(apps, schema_editor):
    ApplicationRound = apps.get_model("applications", "ApplicationRound")
    for application in ApplicationRound.objects.all():
        if application.target_group is not None:
            application.target_group = application.target_group.upper()
            application.save()


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0071_update_application_enums"),
    ]

    operations = [
        migrations.RunPython(convert_enums_to_upper_case, migrations.RunPython.noop),
    ]
