# Generated by Django 4.2.7 on 2023-11-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0072_fix_target_group_case"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventreservationunit",
            options={"ordering": ["preferred_order"]},
        ),
        migrations.AddField(
            model_name="eventreservationunit",
            name="preferred_order",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
