# Generated by Django 4.2.7 on 2023-11-08 11:36

from django.db import migrations


def migrate_priority_to_preferred_order(apps, schema_editor):
    EventReservationUnit = apps.get_model("applications", "EventReservationUnit")

    priority: int = 0
    application_event_id: int = -1
    # Order events by priority and application event. This way we can
    # assign preferred order sequentially without having to worry about
    # what the order of priority has been.
    for event_unit in EventReservationUnit.objects.order_by("application_event", "priority").all():
        if application_event_id != event_unit.application_event_id:
            application_event_id = event_unit.application_event_id
            priority = 0
        else:
            priority += 1

        event_unit.preferred_order = priority
        event_unit.save()


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0073_alter_eventreservationunit_options_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_priority_to_preferred_order, migrations.RunPython.noop),
    ]
