# Generated by Django 4.2.7 on 2023-11-08 11:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0074_migrate_priority_to_preferred_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventreservationunit",
            name="priority",
        ),
    ]
