# Generated by Django 4.2.9 on 2024-01-23 07:12

from django.db import migrations

from utils.migration import AlterModelTable


class Migration(migrations.Migration):
    dependencies = [
        (
            "applications",
            "0078_add_base_manager_name_to_all_models",
        ),
    ]

    operations = [
        AlterModelTable(
            name="address",
            table="address",
        ),
        AlterModelTable(
            name="application",
            table="application",
        ),
        AlterModelTable(
            name="applicationevent",
            table="application_event",
        ),
        AlterModelTable(
            name="applicationeventschedule",
            table="application_event_schedule",
        ),
        AlterModelTable(
            name="applicationround",
            table="application_round",
        ),
        AlterModelTable(
            name="applicationroundtimeslot",
            table="application_round_time_slot",
        ),
        AlterModelTable(
            name="city",
            table="city",
        ),
        AlterModelTable(
            name="eventreservationunit",
            table="event_reservation_unit",
        ),
        AlterModelTable(
            name="organisation",
            table="organisation",
        ),
        AlterModelTable(
            name="person",
            table="person",
        ),
    ]
