# Generated by Django 4.2.10 on 2024-02-23 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0080_applicationsection_suitabletimerange_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"base_manager_name": "objects", "verbose_name": "Address", "verbose_name_plural": "Addresses"},
        ),
        migrations.AlterModelOptions(
            name="allocatedtimeslot",
            options={
                "base_manager_name": "objects",
                "verbose_name": "Allocated Time Slot",
                "verbose_name_plural": "Allocated Time Slots",
            },
        ),
        migrations.AlterModelOptions(
            name="application",
            options={
                "base_manager_name": "objects",
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationround",
            options={
                "base_manager_name": "objects",
                "verbose_name": "Application Round",
                "verbose_name_plural": "Application Rounds",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationroundtimeslot",
            options={
                "base_manager_name": "objects",
                "ordering": ["reservation_unit", "weekday"],
                "verbose_name": "Application Round Time Slot",
                "verbose_name_plural": "Application Round Time Slots",
            },
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"base_manager_name": "objects", "verbose_name": "City", "verbose_name_plural": "Cities"},
        ),
        migrations.AlterModelOptions(
            name="organisation",
            options={
                "base_manager_name": "objects",
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisations",
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"base_manager_name": "objects", "verbose_name": "Person", "verbose_name_plural": "Persons"},
        ),
        migrations.AlterModelOptions(
            name="suitabletimerange",
            options={
                "base_manager_name": "objects",
                "verbose_name": "Suitable Time Range",
                "verbose_name_plural": "Suitable Time Ranges",
            },
        ),
    ]
