# Generated by Django 5.0.3 on 2024-03-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0082_applicationround_terms_of_use"),
        ("reservations", "0064_alter_reservationstatistic_priority"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="allocatedtimeslot",
            name="begin_time_before_end_time_allocated",
        ),
        migrations.RemoveConstraint(
            model_name="applicationsection",
            name="begin_date_before_end_date",
        ),
        migrations.RemoveConstraint(
            model_name="suitabletimerange",
            name="begin_time_before_end_time_suitable",
        ),
        migrations.AddConstraint(
            model_name="allocatedtimeslot",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("begin_time__lt", models.F("end_time")),
                    models.Q(("end_time__hour", 0), models.Q(("begin_time__hour", 0), _negated=True)),
                    _connector="OR",
                ),
                name="begin_time_before_end_time_allocated",
                violation_error_message="Begin time must be before end time.",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationsection",
            constraint=models.CheckConstraint(
                check=models.Q(("reservations_begin_date__lte", models.F("reservations_end_date"))),
                name="begin_date_before_end_date",
                violation_error_message="Reservations begin date must be before reservations end date.",
            ),
        ),
        migrations.AddConstraint(
            model_name="suitabletimerange",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("begin_time__lt", models.F("end_time")),
                    models.Q(("end_time__hour", 0), models.Q(("begin_time__hour", 0), _negated=True)),
                    _connector="OR",
                ),
                name="begin_time_before_end_time_suitable",
                violation_error_message="Begin time must be before end time.",
            ),
        ),
    ]
