# Generated by Django 5.0.3 on 2024-03-20 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0083_remove_allocatedtimeslot_begin_time_before_end_time_allocated_and_more"),
        ("spaces", "0036_change_database_table_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationround",
            name="service_sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="application_rounds",
                to="spaces.servicesector",
            ),
        ),
    ]
