# Generated by Django 5.0.3 on 2024-03-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0084_alter_applicationround_service_sector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationsection',
            options={'base_manager_name': 'objects', 'verbose_name': 'Application Section', 'verbose_name_plural': 'Application Sections'},
        ),
    ]
