# Generated by Django 5.0.3 on 2024-03-28 10:49

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0085_alter_applicationsection_options"),
        ("reservation_units", "0098_alter_reservationunit_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="applicationroundtimeslot",
            name="unique_reservation_unit_weekday",
        ),
        migrations.AddConstraint(
            model_name="applicationroundtimeslot",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("reservation_unit", "weekday"),
                name="unique_reservation_unit_weekday",
                violation_error_message="A reservation unit can only have one timeslot per weekday.",
            ),
        ),
    ]
