# Generated by Django 5.0.4 on 2024-04-08 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0086_remove_applicationroundtimeslot_unique_reservation_unit_weekday_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.AlterModelOptions(
            name="allocatedtimeslot",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "Allocated Time Slot",
                "verbose_name_plural": "Allocated Time Slots",
            },
        ),
        migrations.AlterModelOptions(
            name="application",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationround",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "Application Round",
                "verbose_name_plural": "Application Rounds",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationsection",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "Application Section",
                "verbose_name_plural": "Application Sections",
            },
        ),
        migrations.AlterModelOptions(
            name="city",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
            },
        ),
        migrations.AlterModelOptions(
            name="organisation",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisations",
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "Person",
                "verbose_name_plural": "Persons",
            },
        ),
        migrations.AlterModelOptions(
            name="reservationunitoption",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "Reservation Unit Option",
                "verbose_name_plural": "Reservation Unit Options",
            },
        ),
        migrations.AlterModelOptions(
            name="suitabletimerange",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "Suitable Time Range",
                "verbose_name_plural": "Suitable Time Ranges",
            },
        ),
    ]
