# Generated by Django 5.0.4 on 2024-04-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0087_alter_address_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationround",
            name="notes_when_applying",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="applicationround",
            name="notes_when_applying_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="applicationround",
            name="notes_when_applying_fi",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="applicationround",
            name="notes_when_applying_sv",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
