# Generated by Django 5.0.7 on 2024-08-07 06:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0090_add_application_notification_dates"),
        ("reservations", "0080_remove_recurringreservation_application_event_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicationeventschedule",
            name="application_event",
        ),
        migrations.RemoveField(
            model_name="eventreservationunit",
            name="application_event",
        ),
        migrations.RemoveField(
            model_name="applicationeventschedule",
            name="allocated_reservation_unit",
        ),
        migrations.RemoveField(
            model_name="eventreservationunit",
            name="reservation_unit",
        ),
        migrations.DeleteModel(
            name="ApplicationEvent",
        ),
        migrations.DeleteModel(
            name="ApplicationEventSchedule",
        ),
        migrations.DeleteModel(
            name="EventReservationUnit",
        ),
    ]
