# Generated by Django 5.0.7 on 2024-08-07 06:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0091_remove_applicationeventschedule_application_event_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicationround",
            name="service_sector",
        ),
    ]
