# Generated by Django 5.0.7 on 2024-08-07 06:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0092_remove_applicationround_service_sector"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicationround",
            name="target_group",
        ),
    ]
