# Generated by Django 5.1.1 on 2024-09-18 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0093_remove_applicationround_target_group"),
        ("tilavarauspalvelu", "0004_migrate_terms_of_use"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="applicationround",
                    name="terms_of_use",
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_rounds",
                        to="tilavarauspalvelu.termsofuse",
                    ),
                ),
            ],
            # We just moved the model, so no need to modify foreign keys
            database_operations=[],
        ),
    ]
