# Generated by Django 5.1.1 on 2024-09-26 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0094_alter_applicationround_terms_of_use"),
        ("tilavarauspalvelu", "0011_migrate_reservations"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="applicationround",
                    name="purposes",
                    field=models.ManyToManyField(
                        related_name="application_rounds",
                        to="tilavarauspalvelu.reservationpurpose",
                    ),
                ),
                migrations.AlterField(
                    model_name="applicationsection",
                    name="age_group",
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_sections",
                        to="tilavarauspalvelu.agegroup",
                    ),
                ),
                migrations.AlterField(
                    model_name="applicationsection",
                    name="purpose",
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_sections",
                        to="tilavarauspalvelu.reservationpurpose",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
