# Generated by Django 5.1.1 on 2024-09-26 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0095_alter_applicationround_purposes_and_more"),
        ("tilavarauspalvelu", "0012_migrate_reservation_units"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="applicationround",
                    name="reservation_units",
                    field=models.ManyToManyField(
                        related_name="application_rounds", to="tilavarauspalvelu.reservationunit"
                    ),
                ),
                migrations.AlterField(
                    model_name="applicationroundtimeslot",
                    name="reservation_unit",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_round_time_slots",
                        to="tilavarauspalvelu.reservationunit",
                    ),
                ),
                migrations.AlterField(
                    model_name="reservationunitoption",
                    name="reservation_unit",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservation_unit_options",
                        to="tilavarauspalvelu.reservationunit",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
