from enum import Enum


class ReservationUnitState(Enum):
    DRAFT = "DRAFT"
    SCHEDULED_PUBLISHING = "SCHEDULED_PUBLISHING"
    SCHEDULED_RESERVATION = "SCHEDULED_RESERVATION"
    PUBLISHED = "PUBLISHED"
    ARCHIVED = "ARCHIVED"
