from enum import Enum


class ReservationUnitState(Enum):
    DRAFT = "DRAFT"
    SCHEDULED_PUBLISHING = "SCHEDULED_PUBLISHING"
    SCHEDULED_HIDING = "SCHEDULED_HIDING"
    SCHEDULED_PERIOD = "SCHEDULED_PERIOD"
    HIDDEN = "HIDDEN"
    PUBLISHED = "PUBLISHED"
    ARCHIVED = "ARCHIVED"


class ReservationState(Enum):
    SCHEDULED_RESERVATION = "SCHEDULED_RESERVATION"
    SCHEDULED_PERIOD = "SCHEDULED_PERIOD"
    RESERVABLE = "RESERVABLE"
    SCHEDULED_CLOSING = "SCHEDULED_CLOSING"
    RESERVATION_CLOSED = "RESERVATION_CLOSED"
