
changelog:
  exclude:
    authors:
      - dependabot[bot]
      - pre-commit-ci[bot]
  categories:
    - title: Features
      labels:
        - "*"
      exclude:
        labels:
          - fix
          - improvement
          - refactor
          - dependencies
    - title: Fixes
      labels:
        - fix
    - title: Updates
      labels:
        - improvement
        - refactor
        - dependencies
