
changelog:
  categories:
    - title: Features
      labels:
        - "*"
      exclude:
        labels:
          - fix
          - improvement
          - refactor
          - dependencies
    - title: Fixes
      labels:
        - fix
    - title: Updates
      labels:
        - improvement
        - refactor
    - title: Automated
      labels:
        - dependencies
