# Don't allow dependencies to be used before they have been released for at least 2 weeks
minimumReleaseAge: 20160
packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - core-js
  - esbuild
  - sharp
