FROM python:3.11-bullseye

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . /tvp
WORKDIR /tvp

RUN apt-get update && apt-get -y install libgdal-dev
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
