FROM python:3.11-bullseye

RUN mkdir -p /tvp \
    && apt-get update \
    && apt-get -y install \
        libgdal-dev

WORKDIR /tvp

COPY ./requirements.txt .

RUN pip install -r requirements.txt

COPY . .

RUN chmod +x /tvp/docker/entrypoint.sh

ENTRYPOINT ["/tvp/docker/entrypoint.sh"]
