# Build and deploy to the test environment after creating a tag with the given pattern.

resources:
  repositories:
    # Azure DevOps repository.
    - repository: tilavarauspalvelu-pipelines
      type: git
      # Azure DevOps project/repository.
      name: tilavarauspalvelu/tilavarauspalvelu-pipelines

trigger:
  # If another instance of this pipeline is running,
  # wait for it to complete and then run all other changes in a batch.
  batch: true
  tags:
    # Trigger when creating tags like v1.0.0, release-1.0.0, hotfix-1.0.0, release-1.0.0-core,
    # but not when creating tags like v1.0.0-ui, v1.0.0-customer, v1.0.0-admin, etc.
    include:
      - "v*"
      - "release-*"
      - "hotfix-*"
    exclude:
      - "*-ui"
      - "*-customer"
      - "*-admin"
  paths:
    include:
      - backend
    exclude:
      - README.md

# Don't use Azure pipelines for PRs.
pr: none

# By default, use self-hosted agents.
pool: Default

extends:
  # Filename for pipeline to extend from the Azure DevOps Repository.
  template: core-build-release.yml@tilavarauspalvelu-pipelines
