# Generated by Django 3.2.13 on 2022-06-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms_of_use', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsofuse',
            name='terms_type',
            field=models.CharField(choices=[('generic_terms', 'Generic terms'), ('payment_terms', 'Payment terms'), ('cancellation_terms', 'Cancellation terms'), ('recurring_terms', 'Recurring reservation terms'), ('service_terms', 'Service-specific terms'), ('pricing_terms', 'Pricing terms')], default='generic_terms', max_length=40, verbose_name='Terms type'),
        ),
    ]
