# Generated by Django 4.2.9 on 2024-01-23 07:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("terms_of_use", "0002_alter_termsofuse_terms_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="termsofuse",
            options={
                "base_manager_name": "objects",
                "verbose_name": "terms of use",
                "verbose_name_plural": "terms of use",
            },
        ),
    ]
