# Generated by Django 5.1.1 on 2024-09-18 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0094_alter_applicationround_terms_of_use"),
        ("reservation_units", "0106_alter_reservationunit_cancellation_terms_and_more"),
        ("terms_of_use", "0005_alter_termsofuse_options"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="TermsOfUse",
                ),
            ],
            database_operations=[],
        ),
    ]
