# Generated by Django 3.2.15 on 2022-09-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMerchant',
            fields=[
                ('id', models.UUIDField(help_text='Value comes from the Merchant Experience API', primary_key=True, serialize=False, verbose_name='Merchant ID')),
                ('name', models.CharField(max_length=128, verbose_name='Merchant name')),
            ],
        ),
    ]
