# Generated by Django 3.2.16 on 2022-10-28 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0032_reservationstatistic_reservationstatisticsreservationunit'),
        ('merchants', '0003_paymentorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='reservation',
            field=models.ForeignKey(help_text='Reservation this order is based on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_order', to='reservations.reservation', verbose_name='Reservation'),
        ),
    ]
