# Generated by Django 3.2.16 on 2022-11-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0006_paymentorder_url_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentorder',
            name='order_id',
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='remote_id',
            field=models.UUIDField(blank=True, help_text='eCommerce order ID', null=True, verbose_name='Remote order ID'),
        ),
    ]
