# Generated by Django 3.2.18 on 2023-04-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0010_paymentorder_refund_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('PAID', 'Paid'), ('PAID_MANUALLY', 'Paid manually'), ('REFUNDED', 'Refunded')], db_index=True, max_length=128, verbose_name='Payment status'),
        ),
    ]
