# Generated by Django 4.2.6 on 2023-10-27 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0054_remove_recurringreservation_application_and_more"),
        ("merchants", "0012_paymentaccounting_balance_profit_center"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentorder",
            name="reservation",
            field=models.ForeignKey(
                blank=True,
                help_text="Reservation this order is based on",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_order",
                to="reservations.Reservation",
                verbose_name="Reservation",
            ),
        ),
    ]
