# Generated by Django 4.2.9 on 2024-01-23 07:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("merchants", "0013_alter_paymentorder_reservation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentaccounting",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="paymentmerchant",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="paymentorder",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="paymentproduct",
            options={"base_manager_name": "objects"},
        ),
    ]
