# Generated by Django 4.2.9 on 2024-01-23 07:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("merchants", "0014_add_base_manager_name_to_all_models"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="paymentaccounting",
            table="payment_accounting",
        ),
        migrations.AlterModelTable(
            name="paymentmerchant",
            table="payment_merchant",
        ),
        migrations.AlterModelTable(
            name="paymentorder",
            table="payment_order",
        ),
        migrations.AlterModelTable(
            name="paymentproduct",
            table="payment_product",
        ),
    ]
