# Generated by Django 5.0.4 on 2024-04-08 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("merchants", "0015_change_database_table_names"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentaccounting",
            options={"base_manager_name": "objects", "ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="paymentmerchant",
            options={"base_manager_name": "objects", "ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="paymentorder",
            options={"base_manager_name": "objects", "ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="paymentproduct",
            options={"base_manager_name": "objects", "ordering": ["pk"]},
        ),
    ]
