# Generated by Django 5.1.1 on 2024-09-18 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("merchants", "0018_remove_verbose_names_and_nullability"),
        ("reservation_units", "0107_alter_reservationunit_payment_accounting_and_more"),
        ("spaces", "0040_alter_unit_payment_accounting_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="PaymentAccounting",
                ),
                migrations.RemoveField(
                    model_name="paymentproduct",
                    name="merchant",
                ),
                migrations.RemoveField(
                    model_name="paymentorder",
                    name="reservation",
                ),
                migrations.DeleteModel(
                    name="PaymentMerchant",
                ),
                migrations.DeleteModel(
                    name="PaymentProduct",
                ),
                migrations.DeleteModel(
                    name="PaymentOrder",
                ),
            ],
            database_operations=[],
        ),
    ]
