# Generated by Django 4.2.4 on 2023-08-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BannerNotification",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("message", models.TextField(blank=True, default="", max_length=1000)),
                ("message_fi", models.TextField(blank=True, default="", max_length=1000, null=True)),
                ("message_en", models.TextField(blank=True, default="", max_length=1000, null=True)),
                ("message_sv", models.TextField(blank=True, default="", max_length=1000, null=True)),
                ("draft", models.BooleanField(default=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("EXCEPTION", "Exception"), ("WARNING", "Warning"), ("NORMAL", "Normal")]
                    ),
                ),
                ("target", models.CharField(choices=[("ALL", "All"), ("STAFF", "Staff"), ("USER", "User")])),
                ("active_from", models.DateTimeField(blank=True, default=None, null=True)),
                ("active_until", models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                "db_table": "banner_notification",
                "base_manager_name": "objects",
                "indexes": [
                    models.Index(
                        models.Case(
                            models.When(then=models.Value(1), type="EXCEPTION"),
                            models.When(then=models.Value(2), type="WARNING"),
                            models.When(then=models.Value(3), type="NORMAL"),
                            default=models.Value(4),
                        ),
                        name="type_priority_index",
                    ),
                    models.Index(
                        models.Case(
                            models.When(target="ALL", then=models.Value(1)),
                            models.When(target="USER", then=models.Value(2)),
                            models.When(target="STAFF", then=models.Value(3)),
                            default=models.Value(4),
                        ),
                        name="target_priority_index",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="bannernotification",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("active_from__isnull", True), ("active_until__isnull", True)),
                    models.Q(
                        ("active_from__isnull", False),
                        ("active_until__isnull", False),
                        ("active_until__gt", models.F("active_from")),
                    ),
                    _connector="OR",
                ),
                name="active_period_not_set_or_active_until_after_active_from",
                violation_error_message="Both 'active_from' and 'active_until' must be either empty or set. If both are set, 'active_until' must be after 'active_from'.",
            ),
        ),
    ]
