# Generated by Django 4.2.4 on 2023-08-29 10:28

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannernotification',
            name='target',
            field=common.fields.ChoiceField(choices=[('ALL', 'All'), ('STAFF', 'Staff'), ('USER', 'User')], max_length=5),
        ),
        migrations.AlterField(
            model_name='bannernotification',
            name='type',
            field=common.fields.ChoiceField(choices=[('EXCEPTION', 'Exception'), ('WARNING', 'Warning'), ('NORMAL', 'Normal')], max_length=9),
        ),
    ]
