# Generated by Django 4.2.4 on 2023-08-29 10:28

from django.db import migrations, models

import utils.fields.model


class BannerNotificationLevel(models.TextChoices):
    EXCEPTION = "EXCEPTION", "Exception"
    WARNING = "WARNING", "Warning"
    NORMAL = "NORMAL", "Normal"


class BannerNotificationTarget(models.TextChoices):
    ALL = "ALL", "All"
    STAFF = "STAFF", "Staff"
    USER = "USER", "User"


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bannernotification",
            name="target",
            field=utils.fields.model.StrChoiceField(enum=BannerNotificationTarget, max_length=5),
        ),
        migrations.AlterField(
            model_name="bannernotification",
            name="type",
            field=utils.fields.model.StrChoiceField(enum=BannerNotificationLevel, max_length=9),
        ),
    ]
