# Generated by Django 4.2.4 on 2023-08-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_bannernotification_target_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bannernotification',
            name='type_priority_index',
        ),
        migrations.RenameField(
            model_name='bannernotification',
            old_name='type',
            new_name='level',
        ),
        migrations.AddIndex(
            model_name='bannernotification',
            index=models.Index(models.Case(models.When(level='EXCEPTION', then=models.Value(1)), models.When(level='WARNING', then=models.Value(2)), models.When(level='NORMAL', then=models.Value(3)), default=models.Value(4)), name='level_priority_index'),
        ),
    ]
