# Generated by Django 4.2.4 on 2023-09-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_bannernotification_type_priority_index_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bannernotification',
            constraint=models.CheckConstraint(check=models.Q(('draft', True), models.Q(('draft', False), ('active_from__isnull', False), ('active_until__isnull', False), models.Q(('message', ''), _negated=True)), _connector='OR'), name='non_draft_notifications_must_have_active_period_and_message', violation_error_message='Non-draft notifications must have an active period and message set.'),
        ),
    ]
