# Generated by Django 5.0.4 on 2024-04-08 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_bannernotification_non_draft_notifications_must_have_active_period_and_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bannernotification",
            options={"base_manager_name": "objects", "ordering": ["pk"]},
        ),
    ]
