# Generated by Django 5.0.4 on 2024-04-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_alter_bannernotification_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SQLLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sql", models.TextField(db_index=True, editable=False)),
                ("path", models.TextField(editable=False)),
                ("body", models.TextField(blank=True, editable=False, null=True)),
                ("duration_ns", models.PositiveBigIntegerField(editable=False)),
                ("succeeded", models.BooleanField(default=True, editable=False)),
                ("request_id", models.UUIDField(editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "SQL log",
                "verbose_name_plural": "SQL logs",
                "db_table": "sql_log",
                "base_manager_name": "objects",
            },
        ),
    ]
