# Generated by Django 5.0.4 on 2024-05-15 10:33


from django.db import migrations, models


def update_sql_logs(apps, schema_editor):
    RequestLog = apps.get_model("common", "RequestLog")
    SQLLog = apps.get_model("common", "SQLLog")

    request_logs = []
    for sql_log in SQLLog.objects.values("request_id", "path", "body", "created").distinct("request_id"):
        request_logs.append(
            RequestLog(
                request_id=sql_log["request_id"],
                path=sql_log["path"],
                body=sql_log["body"],
                created=sql_log["created"],
            )
        )

    RequestLog.objects.bulk_create(request_logs)

    SQLLog.objects.update(request_log=models.F("request_id"))

    logs_with_empty_duration = RequestLog.objects.filter(duration_ms=0)
    for request_log in logs_with_empty_duration:
        request_log.duration_ms = request_log.sql_logs.aggregate(total=models.Sum("duration_ns"))["total"] // 1_000_000
    RequestLog.objects.bulk_update(logs_with_empty_duration, ["duration_ms"])


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0007_create_request_log"),
    ]

    operations = [
        migrations.RunPython(update_sql_logs, migrations.RunPython.noop),
    ]
