# Generated by Django 5.0.4 on 2024-05-15 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0008_move_sql_log_data_to_request_log"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sqllog",
            name="body",
        ),
        migrations.RemoveField(
            model_name="sqllog",
            name="created",
        ),
        migrations.RemoveField(
            model_name="sqllog",
            name="path",
        ),
        migrations.RemoveField(
            model_name="sqllog",
            name="request_id",
        ),
        migrations.AlterField(
            model_name="requestlog",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="sqllog",
            name="request_log",
            field=models.ForeignKey(
                default=None,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sql_logs",
                to="common.requestlog",
            ),
            preserve_default=False,
        ),
    ]
