# Generated by Django 5.0.4 on 2024-05-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0009_remove_sqllog_body_remove_sqllog_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestlog",
            name="duration_ms",
            field=models.PositiveBigIntegerField(editable=False),
        ),
    ]
