# Generated by Django 5.0.6 on 2024-05-29 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0010_alter_requestlog_duration_ms"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="requestlog",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "Request log",
                "verbose_name_plural": "Request logs",
            },
        ),
        migrations.AlterModelOptions(
            name="sqllog",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "SQL log",
                "verbose_name_plural": "SQL logs",
            },
        ),
    ]
