# Generated by Django 5.0.6 on 2024-05-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0011_alter_requestlog_options_alter_sqllog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="sqllog",
            name="stack_info",
            field=models.TextField(blank=True, editable=False),
        ),
    ]
