# Generated by Django 5.1.1 on 2024-09-27 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0012_sqllog_stack_info"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="BannerNotification",
                ),
                migrations.RemoveField(
                    model_name="sqllog",
                    name="request_log",
                ),
                migrations.DeleteModel(
                    name="RequestLog",
                ),
                migrations.DeleteModel(
                    name="SQLLog",
                ),
            ],
            database_operations=[],
        ),
    ]
