# Generated by Django 4.2.6 on 2023-10-24 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OriginHaukiResource",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ("opening_hours_hash", models.CharField(blank=True, max_length=64)),
                ("latest_fetched_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReservableTimeSpan",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservable_time_spans",
                        to="opening_hours.originhaukiresource",
                    ),
                ),
            ],
            options={
                "base_manager_name": "objects",
                "ordering": ["resource", "start_datetime", "end_datetime"],
            },
        ),
        migrations.AddConstraint(
            model_name="reservabletimespan",
            constraint=models.CheckConstraint(
                check=models.Q(("start_datetime__lt", models.F("end_datetime"))),
                name="reservable_time_span_start_before_end",
                violation_error_message="`start_datetime` must be before `end_datetime`.",
            ),
        ),
    ]
