# Generated by Django 5.1.1 on 2024-09-19 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opening_hours", "0004_alter_originhaukiresource_options"),
        ("reservation_units", "0110_alter_reservationunit_origin_hauki_resource"),
        ("tilavarauspalvelu", "0010_migrate_opening_hours"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="reservabletimespan",
                    name="resource",
                ),
                migrations.DeleteModel(
                    name="OriginHaukiResource",
                ),
                migrations.DeleteModel(
                    name="ReservableTimeSpan",
                ),
            ],
            database_operations=[],
        ),
    ]
