# Generated by Django 5.1.1 on 2024-09-26 15:13

from django.db import migrations


# Empty migration file is required to move user model correctly.
class Migration(migrations.Migration):
    initial = True

    dependencies = []

    run_before = []

    operations = []
