# Generated by Django 5.1.1 on 2024-09-18 09:02

from django.db import migrations, models

from utils.migration import TestOnlyRunBefore


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0002_migrate_users"),
        ("applications", "0093_remove_applicationround_target_group"),
        ("common", "0012_sqllog_stack_info"),
        ("email_notification", "0009_rename_in_handling_to_in_allocation"),
        ("merchants", "0018_remove_verbose_names_and_nullability"),
        ("opening_hours", "0004_alter_originhaukiresource_options"),
        ("permissions", "0033_create_and_modified_auto_now"),
        ("reservation_units", "0104_alter_reservationunit_reservation_kind"),
        ("reservations", "0082_remove_net_prices"),
        ("resources", "0010_alter_resource_options"),
        ("services", "0005_alter_service_options"),
        ("spaces", "0039_add_tprek_last_modified_field"),
        ("terms_of_use", "0005_alter_termsofuse_options"),
        ("users", "0017_remove_personalinfoviewlog_user_and_more"),
    ]

    run_before = TestOnlyRunBefore(
        run_before=[
            ("social_django", "0013_migrate_extra_data"),
        ],
    )

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Service",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("name", models.CharField(max_length=255)),
                        ("name_fi", models.CharField(max_length=255, null=True)),
                        ("name_en", models.CharField(max_length=255, null=True)),
                        ("name_sv", models.CharField(max_length=255, null=True)),
                        (
                            "service_type",
                            models.CharField(
                                choices=[
                                    ("introduction", "Introduction"),
                                    ("catering", "Catering"),
                                    ("configuration", "Configuration"),
                                ],
                                default="introduction",
                                max_length=50,
                            ),
                        ),
                        ("buffer_time_before", models.DurationField(blank=True, null=True)),
                        ("buffer_time_after", models.DurationField(blank=True, null=True)),
                    ],
                    options={
                        "db_table": "service",
                        "ordering": ["pk"],
                        "base_manager_name": "objects",
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
