# Generated by Django 5.1.1 on 2024-09-19 11:15

import django.db.models.deletion
from django.db import migrations, models

from utils.migration import TestOnlyRunBefore


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0009_migrate_email_template"),
        ("applications", "0094_alter_applicationround_terms_of_use"),
        ("common", "0012_sqllog_stack_info"),
        ("email_notification", "0010_delete_emailtemplate"),
        ("merchants", "0019_delete_paymentaccounting_and_more"),
        ("opening_hours", "0004_alter_originhaukiresource_options"),
        ("permissions", "0035_remove_unitrole_assigner_remove_unitrole_unit_groups_and_more"),
        ("reservation_units", "0109_alter_reservationunit_spaces_and_more"),
        ("reservations", "0082_remove_net_prices"),
        ("resources", "0011_delete_resource"),
        ("services", "0006_delete_service"),
        ("spaces", "0042_delete_space_delete_unit_delete_unitgroup"),
        ("terms_of_use", "0006_delete_termsofuse"),
        ("users", "0017_remove_personalinfoviewlog_user_and_more"),
    ]

    run_before = TestOnlyRunBefore(
        run_before=[
            ("social_django", "0013_migrate_extra_data"),
        ],
    )

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="OriginHaukiResource",
                    fields=[
                        ("id", models.IntegerField(primary_key=True, serialize=False, unique=True)),
                        ("opening_hours_hash", models.CharField(blank=True, max_length=64)),
                        ("latest_fetched_date", models.DateField(blank=True, null=True)),
                    ],
                    options={
                        "db_table": "origin_hauki_resource",
                        "ordering": ["pk"],
                        "base_manager_name": "objects",
                    },
                ),
                migrations.AlterField(
                    model_name="unit",
                    name="origin_hauki_resource",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="units",
                        to="tilavarauspalvelu.originhaukiresource",
                    ),
                ),
                migrations.CreateModel(
                    name="ReservableTimeSpan",
                    fields=[
                        (
                            "id",
                            models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                        ),
                        ("start_datetime", models.DateTimeField()),
                        ("end_datetime", models.DateTimeField()),
                        (
                            "resource",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="reservable_time_spans",
                                to="tilavarauspalvelu.originhaukiresource",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "reservable_time_span",
                        "ordering": ["resource", "start_datetime", "end_datetime"],
                        "base_manager_name": "objects",
                        "constraints": [
                            models.CheckConstraint(
                                condition=models.Q(("start_datetime__lt", models.F("end_datetime"))),
                                name="reservable_time_span_start_before_end",
                                violation_error_message="`start_datetime` must be before `end_datetime`.",
                            )
                        ],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
