# Generated by Django 5.1.1 on 2024-09-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0015_remove_email_content_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("access_code_for_reservation", "Access Code For Reservation"),
                    ("application_handled", "Application Handled"),
                    ("application_in_allocation", "Application In Allocation"),
                    ("application_received", "Application Received"),
                    ("handling_required_reservation", "Handling Required Reservation"),
                    ("reservation_cancelled", "Reservation Cancelled"),
                    ("reservation_confirmed", "Reservation Confirmed"),
                    ("reservation_handled_and_confirmed", "Reservation Handled And Confirmed"),
                    ("reservation_handling_required", "Reservation Handling Required"),
                    ("reservation_modified", "Reservation Modified"),
                    ("reservation_needs_to_be_paid", "Reservation Needs To Be Paid"),
                    ("reservation_rejected", "Reservation Rejected"),
                    ("reservation_with_pin_confirmed", "Reservation With Pin Confirmed"),
                    ("staff_notification_reservation_made", "Staff Notification Reservation Made"),
                    (
                        "staff_notification_reservation_requires_handling",
                        "Staff Notification Reservation Requires Handling",
                    ),
                ],
                help_text="Only one template per type can be created.",
                max_length=254,
                unique=True,
                verbose_name="Email type",
            ),
        ),
    ]
