# Generated by Django 5.1.2 on 2024-10-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0021_generalrole_role_active_unitrole_role_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sent_email_about_deactivating_permissions",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
