# Generated by Django 5.1 on 2024-09-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0026_add_pricing_date_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationunitpricing",
            name="is_activated_on_begins",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name="reservationunitpricing",
            name="status",
        ),
        migrations.RemoveField(
            model_name="reservationunitpricing",
            name="pricing_type",
        ),
    ]
