# Generated by Django 5.1.3 on 2024-11-27 12:17
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0036_delete_introduction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keywordgroup",
            name="keyword_category",
        ),
        migrations.RemoveField(
            model_name="reservationunit",
            name="keyword_groups",
        ),
        migrations.DeleteModel(
            name="Keyword",
        ),
        migrations.DeleteModel(
            name="KeywordCategory",
        ),
        migrations.DeleteModel(
            name="KeywordGroup",
        ),
    ]
