# Generated by Django 5.1.3 on 2024-11-27 12:21
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0037_delete_keywords"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="buffer_time_after",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="buffer_time_before",
        ),
    ]
