# Generated by Django 5.1.3 on 2024-11-28 07:23
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0040_alter_reservationstatisticsreservationunit_unit_tprek_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recurringreservation",
            old_name="uuid",
            new_name="ext_uuid",
        ),
    ]
