# Generated by Django 5.1.3 on 2024-11-28 07:30
from __future__ import annotations

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor) -> None:
    Reservation = apps.get_model("tilavarauspalvelu", "Reservation")
    rows = list(Reservation.objects.all())
    for row in rows:
        row.ext_uuid = uuid.uuid4()
    Reservation.objects.bulk_update(rows, ["ext_uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0042_add_reservation_uuids"),
    ]

    operations = [migrations.RunPython(gen_uuid, migrations.RunPython.noop)]
