# Generated by Django 5.1.3 on 2024-12-19 12:09
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0054_bugreport"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bugreport",
            old_name="phase",
            new_name="found_in_phase",
        ),
    ]
