# Generated by Django 5.1.3 on 2025-01-07 17:03
from __future__ import annotations

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0057_add_reservation_unit_require_adult_reservee"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="search_terms",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, default=list, size=None
            ),
        ),
    ]
