# Generated by Django 5.1.3 on 2024-12-16 10:21
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0059_unit_allow_permissions_from_ad_groups_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="unitrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_from_ad_group", True)),
                fields=("role", "user"),
                name="unique_role_user_if_is_from_ad_group",
                violation_error_message="Role for user must be unique for AD group based roles.",
            ),
        ),
    ]
