# Generated by Django 5.1.4 on 2025-01-10 09:52
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0060_unitrole_unique_role_user_for_ad_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationunit",
            name="method_of_entry",
            field=models.CharField(
                choices=[("OPEN_ACCESS", "Open access"), ("WITH_KEY", "With key"), ("KEYLESS", "Keyless")],
                default="OPEN_ACCESS",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="reservationunit",
            name="method_of_entry_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservationunit",
            name="method_of_entry_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="reservationunit",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("method_of_entry_start_date__isnull", True),
                    ("method_of_entry_end_date__isnull", True),
                    ("method_of_entry_start_date__lte", models.F("method_of_entry_end_date")),
                    _connector="OR",
                ),
                name="method_of_entry_starts_before_ends",
                violation_error_message="Method of entry start date must be the same or before its end date",
            ),
        ),
    ]
