# Generated by Django 5.1.3 on 2025-01-08 08:49
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0060_unitrole_unique_role_user_for_ad_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationunit",
            name="keyless_entry_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservationunit",
            name="keyless_entry_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservationunit",
            name="method_of_entry",
            field=models.CharField(
                choices=[("OPEN_ACCESS", "Open access"), ("WITH_KEY", "With key"), ("KEYLESS", "Keyless")],
                default="OPEN_ACCESS",
                max_length=20,
            ),
        ),
    ]
