# Generated by Django 5.1.3 on 2024-12-16 23:51
from __future__ import annotations

import re

from django.db import migrations


def htmlize(text: str | None) -> str:
    """Convert linebreaks in text to paragraphs."""
    if not text:
        return text

    # Assume the text is already in HTML, skip conversion
    if text.startswith("<"):
        return text

    text = re.sub(r"(.{1,})", r"<p>\1</p>", text)
    return text.replace("\n", "")  # Remove linebreaks


def htmlize_instructions_fields(apps, schema_editor):
    ReservationUnit = apps.get_model("tilavarauspalvelu", "ReservationUnit")

    rows = list(ReservationUnit.objects.all())
    for ru in rows:
        ru.reservation_pending_instructions_fi = htmlize(ru.reservation_pending_instructions_fi)
        ru.reservation_pending_instructions_sv = htmlize(ru.reservation_pending_instructions_sv)
        ru.reservation_pending_instructions_en = htmlize(ru.reservation_pending_instructions_en)
        ru.reservation_confirmed_instructions_fi = htmlize(ru.reservation_confirmed_instructions_fi)
        ru.reservation_confirmed_instructions_sv = htmlize(ru.reservation_confirmed_instructions_sv)
        ru.reservation_confirmed_instructions_en = htmlize(ru.reservation_confirmed_instructions_en)
        ru.reservation_cancelled_instructions_fi = htmlize(ru.reservation_cancelled_instructions_fi)
        ru.reservation_cancelled_instructions_sv = htmlize(ru.reservation_cancelled_instructions_sv)
        ru.reservation_cancelled_instructions_en = htmlize(ru.reservation_cancelled_instructions_en)

    ReservationUnit.objects.bulk_update(
        rows,
        fields=[
            "reservation_pending_instructions_fi",
            "reservation_pending_instructions_sv",
            "reservation_pending_instructions_en",
            "reservation_confirmed_instructions_fi",
            "reservation_confirmed_instructions_sv",
            "reservation_confirmed_instructions_en",
            "reservation_cancelled_instructions_fi",
            "reservation_cancelled_instructions_sv",
            "reservation_cancelled_instructions_en",
        ],
    )


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0061_reservation_unit_access_type"),
    ]

    operations = [
        migrations.RunPython(htmlize_instructions_fields, migrations.RunPython.noop),
    ]
