# Generated by Django 5.1.4 on 2025-01-22 13:18
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0063_clean_newlines_from_rich_text_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="access_code_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="access_code_is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservation",
            name="access_type",
            field=models.CharField(
                choices=[
                    ("ACCESS_CODE", "access code"),
                    ("OPENED_BY_STAFF", "opened by staff"),
                    ("PHYSICAL_KEY", "physical key"),
                    ("UNRESTRICTED", "unrestricted"),
                ],
                default="UNRESTRICTED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="reservationstatistic",
            name="access_code_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservationstatistic",
            name="access_type",
            field=models.CharField(default="UNRESTRICTED", max_length=255),
            preserve_default=False,
        ),
    ]
