# Generated by Django 5.1.4 on 2025-01-22 05:49
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tilavarauspalvelu", "0063_clean_newlines_from_rich_text_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="reservee_language",
        ),
    ]
