# Generated by Django 3.0.10 on 2021-03-12 08:11

from django.db import migrations


def update_permissions(apps, schema_editor):
    UnitRoleChoice = apps.get_model('permissions', 'UnitRoleChoice')
    ServiceSectorRoleChoice = apps.get_model('permissions', 'ServiceSectorRoleChoice')
    GeneralRoleChoice = apps.get_model('permissions', 'GeneralRoleChoice')
    ServiceSectorRolePermission = apps.get_model('permissions', 'ServiceSectorRolePermission')
    UnitRolePermission = apps.get_model('permissions', 'UnitRolePermission')
    GeneralRolePermission = apps.get_model('permissions', 'GeneralRolePermission')


    # General Admin
    general_admin = GeneralRoleChoice.objects.get(
        code="admin",
    )
    GeneralRolePermission.objects.create(
        role=general_admin,
        permission="can_view_users"
    )

    # Service Sector Admin
    service_sector_admin = ServiceSectorRoleChoice.objects.get(code="admin")
    ServiceSectorRolePermission.objects.create(
        role=service_sector_admin,
        permission="can_view_users"
    )

    # Service Sector Application Manager
    service_sector_application_manager = ServiceSectorRoleChoice.objects.get(code="application_manager")
    ServiceSectorRolePermission.objects.create(
        role=service_sector_application_manager,
        permission="can_view_users"
    )

    # Unit Admin
    unit_admin = UnitRoleChoice.objects.get(code="admin")
    UnitRolePermission.objects.create(
        role=unit_admin,
        permission="can_view_users"
    )

    # Unit Manager
    unit_manager = UnitRoleChoice.objects.get(code="manager")
    UnitRolePermission.objects.create(
        role=unit_manager,
        permission="can_view_users"
    )

   # Unit Viewer
    unit_viewer = UnitRoleChoice.objects.get(code="viewer")
    UnitRolePermission.objects.create(
        role=unit_viewer,
        permission="can_view_users"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_add_view_users_permission'),
    ]

    operations = [
        migrations.RunPython(update_permissions, migrations.RunPython.noop),
    ]
