# Generated by Django 3.2.12 on 2022-02-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0013_reservation_purpose_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesectorrolepermission',
            name='permission',
            field=models.CharField(choices=[('can_manage_service_sector_roles', 'Can modify roles for the service sector'), ('can_manage_unit_roles', 'Can modify roles for units in the service sector'), ('can_manage_reservation_units', 'Can create, edit and delete reservation units in certain unit'), ('can_manage_application_rounds', 'Can create, edit and delete application rounds in the service sector'), ('can_handle_applications', 'Can handle applications in the service sector'), ('can_manage_reservations', 'Can create, edit and cancel reservations in the service sector'), ('can_view_reservations', 'Can view details of all reservations in the service sector'), ('can_view_users', 'Can view users in the whole system'), ('can_allocate_applications', 'Can allocate applications in the service sector'), ('can_manage_spaces', 'Can create, edit and delete spaces in the service sector')], max_length=255, verbose_name='Permission'),
        ),
        migrations.AlterField(
            model_name='unitrolepermission',
            name='permission',
            field=models.CharField(choices=[('can_manage_unit_roles', 'Can modify roles for the unit'), ('can_manage_reservation_units', 'Can create, edit and delete reservation units in the unit'), ('can_manage_reservations', 'Can create, edit and cancel reservations in the unit'), ('can_view_reservations', 'Can view details of all reservations in the unit'), ('can_view_users', 'Can view users in the whole system'), ('can_allocate_applications', 'Can allocate applications'), ('can_validate_applications', 'Can validate applications'), ('can_manage_units', 'Can edit unit information'), ('can_manage_spaces', 'Can create, edit and delete spaces in the unit')], max_length=255, verbose_name='Permission'),
        ),
    ]
