# Generated by Django 3.2.16 on 2022-11-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0017_alter_generalrolepermission_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalrolepermission',
            name='permission',
            field=models.CharField(choices=[('can_manage_general_roles', 'Can manage general roles for the whole system'), ('can_manage_service_sector_roles', 'Can manage roles for service sectorsfor the whole system'), ('can_manage_unit_roles', 'Can manage roles for units in the whole system'), ('can_manage_reservation_units', 'Can create, edit and delete reservation units in the whole system'), ('can_manage_purposes', 'Can create, edit and delete purposes in the whole system'), ('can_manage_reservation_purposes', 'Can create, edit and delete reservation purposes in the whole system'), ('can_manage_age_groups', 'Can create, edit and delete age groups in the whole system'), ('can_manage_districts', 'Can create, edit and delete districts in the whole system'), ('can_manage_ability_groups', 'Can create, edit and delete ability groups in the whole system'), ('can_manage_reservation_unit_types', 'Can create, edit and delete reservation unit types in the whole system'), ('can_manage_equipment_categories', 'Can create, edit and delete equipment_categories in the whole system'), ('can_manage_equipment', 'Can create, edit and delete equipment in the whole system'), ('can_view_reservations', 'Can view reservations in the whole system'), ('can_manage_reservations', 'Can create, edit and delete equipment in the whole system'), ('can_manage_reservations', 'Can create, edit and cancel reservations in the whole system'), ('can_view_reservations', 'Can view details of all reservations in the whole system'), ('can_manage_resources', 'Can create, edit and delete resources in the whole system'), ('can_manage_spaces', 'Can create, edit and delete spaces in the whole system'), ('can_handle_applications', 'Can handle applications in the whole system'), ('can_manage_application_rounds', 'Can create, edit and delete application rounds in the whole system'), ('can_view_users', 'Can view users in the whole system'), ('can_comment_reservations', 'Can comment reservations in the whole system'), ('can_create_staff_reservations', 'Can create staff reservations in the whole system')], max_length=255, verbose_name='Permission'),
        ),
        migrations.AlterField(
            model_name='servicesectorrolepermission',
            name='permission',
            field=models.CharField(choices=[('can_manage_service_sector_roles', 'Can modify roles for the service sector'), ('can_manage_unit_roles', 'Can modify roles for units in the service sector'), ('can_manage_reservation_units', 'Can create, edit and delete reservation units in certain unit'), ('can_manage_application_rounds', 'Can create, edit and delete application rounds in the service sector'), ('can_handle_applications', 'Can handle applications in the service sector'), ('can_manage_reservations', 'Can create, edit and cancel reservations in the service sector'), ('can_view_reservations', 'Can view details of all reservations in the service sector'), ('can_view_users', 'Can view users in the whole system'), ('can_allocate_applications', 'Can allocate applications in the service sector'), ('can_manage_spaces', 'Can create, edit and delete spaces in the service sector'), ('can_manage_resources', 'Can create, edit and delete resources in the given service sector'), ('can_create_staff_reservations', 'Can create staff reservations in the given service sector')], max_length=255, verbose_name='Permission'),
        ),
        migrations.AlterField(
            model_name='unitrolepermission',
            name='permission',
            field=models.CharField(choices=[('can_manage_unit_roles', 'Can modify roles for the unit'), ('can_manage_reservation_units', 'Can create, edit and delete reservation units in the unit'), ('can_manage_reservations', 'Can create, edit and cancel reservations in the unit'), ('can_view_reservations', 'Can view details of all reservations in the unit'), ('can_view_users', 'Can view users in the whole system'), ('can_allocate_applications', 'Can allocate applications'), ('can_validate_applications', 'Can validate applications'), ('can_manage_units', 'Can edit unit information'), ('can_manage_spaces', 'Can create, edit and delete spaces in the unit'), ('can_manage_resources', 'Can create, edit and delete resources in the given unit'), ('can_create_staff_reservations', 'Can create staff reservations in the given unit')], max_length=255, verbose_name='Permission'),
        ),
    ]
