# Generated by Django 4.2.9 on 2024-01-23 07:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0022_alter_generalrolepermission_permission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generalrole",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="generalrolechoice",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="generalrolepermission",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="servicesectorrole",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="servicesectorrolechoice",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="servicesectorrolepermission",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="unitrole",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="unitrolechoice",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="unitrolepermission",
            options={"base_manager_name": "objects"},
        ),
    ]
