# Generated by Django 4.2.9 on 2024-01-23 07:12

from django.db import migrations

from utils.migration import AlterModelTable


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0023_add_base_manager_name_to_all_models"),
    ]

    operations = [
        AlterModelTable(
            name="generalrole",
            table="general_role",
        ),
        AlterModelTable(
            name="generalrolechoice",
            table="general_role_choice",
        ),
        AlterModelTable(
            name="generalrolepermission",
            table="general_role_permission",
        ),
        AlterModelTable(
            name="servicesectorrole",
            table="service_sector_role",
        ),
        AlterModelTable(
            name="servicesectorrolechoice",
            table="service_sector_role_choice",
        ),
        AlterModelTable(
            name="servicesectorrolepermission",
            table="service_sector_role_permission",
        ),
        AlterModelTable(
            name="unitrole",
            table="unit_role",
        ),
        AlterModelTable(
            name="unitrolechoice",
            table="unit_role_choice",
        ),
        AlterModelTable(
            name="unitrolepermission",
            table="unit_role_permission",
        ),
    ]
