# Generated by Django 5.0.7 on 2024-08-07 08:08

import django.db.models.deletion
import graphene_django_extensions.fields.model
from django.conf import settings
from django.db import migrations, models


class UserRoleChoice(models.TextChoices):
    ADMIN = "ADMIN", "Admin"
    HANDLER = "HANDLER", "Handler"
    VIEWER = "VIEWER", "Viewer"
    RESERVER = "RESERVER", "Reserver"
    NOTIFICATION_MANAGER = "NOTIFICATION_MANAGER", "Notification manager"


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0027_alter_generalrolepermission_permission"),
        ("spaces", "0039_add_tprek_last_modified_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewGeneralRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    graphene_django_extensions.fields.model.StrChoiceField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("HANDLER", "Handler"),
                            ("VIEWER", "Viewer"),
                            ("RESERVER", "Reserver"),
                            ("NOTIFICATION_MANAGER", "Notification manager"),
                        ],
                        enum=UserRoleChoice,
                        max_length=20,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(),
                ),
                (
                    "modified",
                    models.DateTimeField(),
                ),
                (
                    "assigner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="general_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "base_manager_name": "objects",
                "verbose_name": "General role",
                "verbose_name_plural": "General roles",
            },
        ),
        migrations.CreateModel(
            name="NewUnitRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    graphene_django_extensions.fields.model.StrChoiceField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("HANDLER", "Handler"),
                            ("VIEWER", "Viewer"),
                            ("RESERVER", "Reserver"),
                            ("NOTIFICATION_MANAGER", "Notification manager"),
                        ],
                        enum=UserRoleChoice,
                        max_length=20,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(),
                ),
                (
                    "modified",
                    models.DateTimeField(),
                ),
                (
                    "assigner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "units",
                    models.ManyToManyField(
                        blank=True,
                        related_name="unit_roles",
                        to="spaces.unit",
                    ),
                ),
                (
                    "unit_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="unit_roles",
                        to="spaces.unitgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "base_manager_name": "objects",
                "verbose_name": "Unit role",
                "verbose_name_plural": "Unit roles",
            },
        ),
    ]
