# Generated by Django 5.0.7 on 2024-08-07 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0029_migrate_permissions_to_new_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generalrolepermission",
            name="role",
        ),
        migrations.RemoveField(
            model_name="servicesectorrole",
            name="assigner",
        ),
        migrations.RemoveField(
            model_name="servicesectorrole",
            name="role",
        ),
        migrations.RemoveField(
            model_name="servicesectorrole",
            name="service_sector",
        ),
        migrations.RemoveField(
            model_name="servicesectorrole",
            name="user",
        ),
        migrations.RemoveField(
            model_name="servicesectorrolepermission",
            name="role",
        ),
        migrations.RemoveField(
            model_name="unitrole",
            name="assigner",
        ),
        migrations.RemoveField(
            model_name="unitrole",
            name="role",
        ),
        migrations.RemoveField(
            model_name="unitrole",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="unitrole",
            name="unit_group",
        ),
        migrations.RemoveField(
            model_name="unitrole",
            name="user",
        ),
        migrations.RemoveField(
            model_name="unitrolepermission",
            name="role",
        ),
        migrations.DeleteModel(
            name="GeneralRole",
        ),
        migrations.DeleteModel(
            name="GeneralRoleChoice",
        ),
        migrations.DeleteModel(
            name="GeneralRolePermission",
        ),
        migrations.DeleteModel(
            name="ServiceSectorRole",
        ),
        migrations.DeleteModel(
            name="ServiceSectorRoleChoice",
        ),
        migrations.DeleteModel(
            name="ServiceSectorRolePermission",
        ),
        migrations.DeleteModel(
            name="UnitRole",
        ),
        migrations.DeleteModel(
            name="UnitRoleChoice",
        ),
        migrations.DeleteModel(
            name="UnitRolePermission",
        ),
    ]
