# Generated by Django 5.1.1 on 2024-09-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0033_create_and_modified_auto_now"),
        ("tilavarauspalvelu", "0007_migrate_spaces"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="unitrole",
                    name="unit_groups",
                    field=models.ManyToManyField(
                        blank=True, related_name="unit_roles", to="tilavarauspalvelu.unitgroup"
                    ),
                ),
                migrations.AlterField(
                    model_name="unitrole",
                    name="units",
                    field=models.ManyToManyField(blank=True, related_name="unit_roles", to="tilavarauspalvelu.unit"),
                ),
            ],
            database_operations=[],
        ),
    ]
