# Generated by Django 5.1.1 on 2024-09-19 06:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0034_alter_unitrole_unit_groups_alter_unitrole_units"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="unitrole",
                    name="assigner",
                ),
                migrations.RemoveField(
                    model_name="unitrole",
                    name="unit_groups",
                ),
                migrations.RemoveField(
                    model_name="unitrole",
                    name="units",
                ),
                migrations.RemoveField(
                    model_name="unitrole",
                    name="user",
                ),
                migrations.DeleteModel(
                    name="GeneralRole",
                ),
                migrations.DeleteModel(
                    name="UnitRole",
                ),
            ],
            database_operations=[],
        ),
    ]
