# Generated by Django 5.0.4 on 2024-04-08 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0004_change_database_table_names"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"base_manager_name": "objects", "ordering": ["pk"]},
        ),
    ]
