# Generated by Django 5.1.1 on 2024-09-18 09:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservation_units", "0105_alter_reservationunit_services"),
        ("services", "0005_alter_service_options"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Service",
                ),
            ],
            database_operations=[],
        )
    ]
