# Generated by Django 3.0.10 on 2020-10-30 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spaces", "0001_initial"),
        ("services", "0001_initial"),
        ("resources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationUnit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "require_introduction",
                    models.BooleanField(
                        default=False, verbose_name="Require introduction"
                    ),
                ),
                (
                    "fixed_resources",
                    models.ManyToManyField(
                        related_name="reservation_units",
                        to="resources.FixedResource",
                        verbose_name="Fixed resources",
                    ),
                ),
                (
                    "movable_resources",
                    models.ManyToManyField(
                        related_name="reservation_units",
                        to="resources.MovableResource",
                        verbose_name="Movable resources",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        related_name="reservation_units",
                        to="services.Service",
                        verbose_name="Services",
                    ),
                ),
                (
                    "spaces",
                    models.ManyToManyField(
                        related_name="reservation_units",
                        to="spaces.Space",
                        verbose_name="Spaces",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("begin", models.DateTimeField(verbose_name="Begin time")),
                ("end", models.DateTimeField(verbose_name="End time")),
                (
                    "reservation_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservations.ReservationUnit",
                        verbose_name="Reservation unit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Introduction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(verbose_name="Completed at")),
                (
                    "reservation_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservations.ReservationUnit",
                        verbose_name="Reservation unit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
