# Generated by Django 3.0.10 on 2020-11-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_auto_20201102_1059"),
        ("spaces", "0002_auto_20201030_1213"),
        ("services", "0002_auto_20201102_1059"),
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationunit",
            name="fixed_resources",
            field=models.ManyToManyField(
                blank=True,
                related_name="reservation_units",
                to="resources.FixedResource",
                verbose_name="Fixed resources",
            ),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="movable_resources",
            field=models.ManyToManyField(
                blank=True,
                related_name="reservation_units",
                to="resources.MovableResource",
                verbose_name="Movable resources",
            ),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                related_name="reservation_units",
                to="services.Service",
                verbose_name="Services",
            ),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="spaces",
            field=models.ManyToManyField(
                blank=True,
                related_name="reservation_units",
                to="spaces.Space",
                verbose_name="Spaces",
            ),
        ),
    ]
