# Generated by Django 3.0.10 on 2020-11-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20201102_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='buffer_time_after',
            field=models.DurationField(blank=True, null=True, verbose_name='Buffer time after'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='buffer_time_before',
            field=models.DurationField(blank=True, null=True, verbose_name='Buffer time before'),
        ),
    ]
