# Generated by Django 3.0.10 on 2020-12-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_add_recurring_reservation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegroup',
            name='maximum',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum'),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='minimum',
            field=models.PositiveIntegerField(verbose_name='Minimum'),
        ),
    ]
