# Generated by Django 3.0.10 on 2020-11-04 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_auto_20201102_1244"),
    ]

    operations = [
        migrations.CreateModel(
            name="DayPart",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allowed_group",
                    models.CharField(
                        choices=[
                            ("allowed_everyone", "Everyone allowed"),
                            ("allowed_public", "Public allowed"),
                            ("allowed_staff", "Staff allowed"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "begin",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Begin time of day part"
                    ),
                ),
                (
                    "end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="End time of day part"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reservation_length_type",
                    models.CharField(
                        choices=[
                            ("within_day", "within day"),
                            ("whole_day", "whole day"),
                            ("over_night", "over night"),
                        ],
                        default="within_day",
                        max_length=16,
                        verbose_name="Reservations length type",
                    ),
                ),
                ("start", models.DateField(verbose_name="Start date")),
                ("end", models.DateField(verbose_name="End date")),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Name"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "closed",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="Closed"
                    ),
                ),
                (
                    "reservation_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="reservations.ReservationUnit",
                        verbose_name="Reservation unit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        verbose_name="Weekday",
                    ),
                ),
                (
                    "opens",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Time when opens"
                    ),
                ),
                (
                    "closes",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Time when closes"
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="reservations.Period",
                        verbose_name="Period",
                    ),
                ),
            ],
        ),
    ]
