# Generated by Django 3.0.10 on 2020-11-04 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_day_daypart_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='daypart',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations.Day', verbose_name='Day'),
            preserve_default=False,
        ),
    ]
