# Generated by Django 3.1.8 on 2021-05-16 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0044_applicationroundaggregatedata"),
        ("reservations", "0004_recurringreservation_application_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurringreservation",
            name="application",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recurring_reservation",
                to="applications.Application",
                verbose_name="Application",
            ),
        ),
        migrations.AlterField(
            model_name="recurringreservation",
            name="application_event",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recurring_reservation",
                to="applications.ApplicationEvent",
                verbose_name="Application event",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="recurring_reservation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="reservations.RecurringReservation",
                verbose_name="Recurring reservation",
            ),
        ),
    ]
