# Generated by Django 3.0.10 on 2020-11-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0005_daypart_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="reservation_unit",
        ),
        migrations.AddField(
            model_name="reservation",
            name="reservation_unit",
            field=models.ManyToManyField(
                to="reservations.ReservationUnit", verbose_name="Reservation unit"
            ),
        ),
    ]
