# Generated by Django 3.1.13 on 2021-10-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_ability_group_reservation_purpose_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
    ]
