# Generated by Django 3.0.10 on 2020-11-05 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservation_units", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reservations", "0008_reservationunit_resources"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringReservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservationPurpose",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_purpose",
                    models.TextField(blank=True, verbose_name="Custom purpose"),
                ),
                (
                    "purpose",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reservation_units.Purpose",
                        verbose_name="Reservation purpose",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="daypart",
            name="day",
        ),
        migrations.RemoveField(
            model_name="introduction",
            name="reservation_unit",
        ),
        migrations.RemoveField(
            model_name="introduction",
            name="user",
        ),
        migrations.RemoveField(
            model_name="period",
            name="reservation_unit",
        ),
        migrations.RemoveField(
            model_name="reservationunit",
            name="resources",
        ),
        migrations.RemoveField(
            model_name="reservationunit",
            name="services",
        ),
        migrations.RemoveField(
            model_name="reservationunit",
            name="spaces",
        ),
        migrations.AddField(
            model_name="reservation",
            name="priority",
            field=models.IntegerField(
                choices=[(100, "Low"), (200, "Medium"), (300, "High")], default=200
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="state",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("cancelled", "cancelled"),
                    ("confirmed", "confirmed"),
                    ("denied", "denied"),
                    ("requested", "requested"),
                    ("waiting_for_payment", "waiting for payment"),
                ],
                default="created",
                max_length=32,
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_unit",
            field=models.ManyToManyField(
                to="reservation_units.ReservationUnit", verbose_name="Reservation unit"
            ),
        ),
        migrations.DeleteModel(
            name="Day",
        ),
        migrations.DeleteModel(
            name="DayPart",
        ),
        migrations.DeleteModel(
            name="Introduction",
        ),
        migrations.DeleteModel(
            name="Period",
        ),
        migrations.DeleteModel(
            name="ReservationUnit",
        ),
        migrations.AddField(
            model_name="reservationpurpose",
            name="reservation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="reservations.Reservation",
                verbose_name="Reservation",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="recurring_reservation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="reservations.RecurringReservation",
                verbose_name="Recurring reservation",
            ),
        ),
    ]
