# Generated by Django 3.1.13 on 2021-10-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_reservee_name_and_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservee_name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservee_first_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Reservee first name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservee_last_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Reservee last name'),
        ),
    ]
