# Generated by Django 3.1.13 on 2021-11-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_migrate_reservation_purposes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OldReservationPurpose',
        ),
    ]
