# Generated by Django 3.1.13 on 2021-11-09 10:57

from django.db import migrations


def delete_old_purposes(apps, schema_editor):
    Purpose = apps.get_model("reservation_units", "Purpose")
    db_alias = schema_editor.connection.alias
    Purpose.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_delete_old_reservation_purpose'),
        ('applications', '0050_modify_purpose_foreign_keys'),
    ]

    operations = [
        migrations.RunPython(delete_old_purposes),
    ]
