# Generated by Django 3.1.13 on 2021-11-15 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_update_reservation_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationCancelReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='Reason for cancellation')),
                ('reason_fi', models.CharField(max_length=255, null=True, verbose_name='Reason for cancellation')),
                ('reason_en', models.CharField(max_length=255, null=True, verbose_name='Reason for cancellation')),
                ('reason_sv', models.CharField(max_length=255, null=True, verbose_name='Reason for cancellation')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancel_details',
            field=models.TextField(blank=True, verbose_name="Details for this reservation's cancellation"),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancel_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.reservationcancelreason', verbose_name='Reason for cancellation'),
        ),
    ]
