# Generated by Django 3.1.13 on 2021-11-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_reservation_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmed_at',
            field=models.DateTimeField(null=True, verbose_name='Confirmed at'),
        ),
    ]
