# Generated by Django 3.1.14 on 2021-12-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_reservation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='tax_percentage_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The value of the tax percentage for this particular reservation', max_digits=5, verbose_name='Tax percentage value'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The price of this particular reservation', max_digits=10, verbose_name='Unit price'),
        ),
    ]
