# Generated by Django 3.1.13 on 2022-01-12 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_reservation_handled_at_and_deny_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationDenyReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='Reason for deny')),
                ('reason_fi', models.CharField(max_length=255, null=True, verbose_name='Reason for deny')),
                ('reason_en', models.CharField(max_length=255, null=True, verbose_name='Reason for deny')),
                ('reason_sv', models.CharField(max_length=255, null=True, verbose_name='Reason for deny')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='deny_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.reservationdenyreason', verbose_name='Reason for deny'),
        ),
    ]
