# Generated by Django 3.1.13 on 2022-01-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0022_reservation_deny_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='deny_details',
        ),
        migrations.AddField(
            model_name='reservation',
            name='handling_details',
            field=models.TextField(blank=True, help_text='Additional details for denying or approving the reservation', verbose_name='Handling details for this reservation'),
        ),
    ]
