# Generated by Django 3.1.13 on 2022-01-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0023_reservation_rename_deny_details_to_handling_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('created', 'created'), ('cancelled', 'cancelled'), ('requires_handling', 'requires_handling'), ('confirmed', 'confirmed'), ('denied', 'denied')], default='created', max_length=32, verbose_name='State'),
        ),
    ]
