# Generated by Django 3.1.14 on 2022-01-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0024_add_reservation_state_requires_handling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservee_id',
            field=models.CharField(blank=True, default='', help_text="Reservee's business or association identity code", max_length=10, verbose_name='Reservee ID'),
        ),
    ]
