# Generated by Django 3.1.13 on 2022-01-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0025_fix_reservee_id_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='working_memo',
            field=models.TextField(blank=True, default='', help_text='Working memo for staff users.', null=True, verbose_name='Working memo'),
        ),
    ]
