# Generated by Django 3.1.14 on 2022-01-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0026_add_reservation_working_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='SKU'),
        ),
    ]
