# Generated by Django 3.2.15 on 2022-08-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0028_reservation_staff_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='type',
            field=models.CharField(choices=[('normal', 'Type Normal'), ('blocked', 'Type Blocked')], default='normal', help_text='Type of reservation', max_length=50, null=True),
        ),
    ]
