# Generated by Django 3.2.15 on 2022-08-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0029_reservation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('blocked', 'Blocked')], default='normal', help_text='Type of reservation', max_length=50, null=True),
        ),
    ]
