# Generated by Django 3.2.16 on 2022-11-04 06:24
from decimal import Decimal

from django.db import migrations


def update_net_prices(apps, schema_editor):
    pass
    Reservation = apps.get_model("reservations", "Reservation")

    for reservation in Reservation.objects.all():
        reservation.price_net = reservation.price / (
            1 + reservation.tax_percentage_value / Decimal("100")
        )
        reservation.save()


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0033_reservation_net_price"),
    ]

    operations = [
        migrations.RunPython(update_net_prices, migrations.RunPython.noop),
    ]
