# Generated by Django 3.2.16 on 2022-11-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0034_add_net_prices_to_existing_reservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='price_net',
            field=models.DecimalField(decimal_places=6, default=0, help_text='The price of this particular reservation excluding VAT', max_digits=20, verbose_name='Price net'),
        ),
    ]
