# Generated by Django 3.2.16 on 2022-11-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0035_alter_reservation_price_net'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='non_subsidised_price',
            field=models.DecimalField(decimal_places=6, default=0, help_text='The non subsidised price of this reservation excluding VAT', max_digits=20, verbose_name='Non subsidised price'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='non_subsidised_price_net',
            field=models.DecimalField(decimal_places=6, default=0, help_text='The non subsidised price of this reservation excluding VAT', max_digits=20, verbose_name='Non subsidised net price'),
        ),
    ]
