# Generated by Django 3.2.16 on 2022-11-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0038_change_staff_event_to_reservation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationstatistic',
            name='staff_event',
        ),
    ]
