# Generated by Django 3.2.16 on 2022-12-14 15:01

from django.db import migrations


def update_created_and_reservation_units(apps, schema_editor):
    RecurringReservation = apps.get_model("reservations", "RecurringReservation")

    for recurring in RecurringReservation.objects.all():
        reservation = recurring.reservations.first()
        if reservation:
            if reservation.created_at:
                recurring.created = reservation.created_at

            recurring.reservation_unit = reservation.reservation_unit.first()
            recurring.save()
        else:
            recurring.delete()




class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0040_recurring_reservation_fields_changes'),
    ]

    operations = [
        migrations.RunPython(update_created_and_reservation_units, migrations.RunPython.noop)
    ]
