# Generated by Django 3.2.16 on 2023-01-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0042_recurring_reservation_add_validator_comma_sep_int_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringreservation',
            name='interval',
        ),
        migrations.AddField(
            model_name='recurringreservation',
            name='recurrence_in_days',
            field=models.PositiveIntegerField(help_text="How this recurring reservation's reservations occurs within days. E.g 7 means that it occurs every week. 14 every other week", null=True),
        ),
    ]
