# Generated by Django 3.2.16 on 2023-01-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0043_recurring_reservation_rename_interval_to_recurrence_in_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringreservation',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
