# Generated by Django 3.2.16 on 2023-02-19 16:48

from django.db import migrations, models
import uuid



def set_uuids_for_existing(apps, schema_editor):
    RecurringReservation = apps.get_model("reservations", "RecurringReservation")
    for recurring in RecurringReservation.objects.all():
        recurring.uuid = uuid.uuid4()
        recurring.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0044_recurringreservation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringreservation',
            name='uuid',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(set_uuids_for_existing, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='recurringreservation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=False),
        ),
        migrations.RunSQL(migrations.RunSQL.noop, reverse_sql='SET CONSTRAINTS ALL IMMEDIATE'),
        migrations.AddField(
            model_name='reservationstatistic',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Is the reservation recurring'),
        ),
        migrations.AddField(
            model_name='reservationstatistic',
            name='is_subsidised',
            field=models.BooleanField(default=False, help_text='Is the reservation price subsidised'),
        ),
        migrations.AddField(
            model_name='reservationstatistic',
            name='non_subsidised_price',
            field=models.DecimalField(decimal_places=6, default=0, help_text='The non subsidised price of the reservation excluding VAT', max_digits=20, verbose_name='Non subsidised price'),
        ),
        migrations.AddField(
            model_name='reservationstatistic',
            name='non_subsidised_price_net',
            field=models.DecimalField(decimal_places=6, default=0, help_text='The non subsidised price of the reservation excluding VAT', max_digits=20, verbose_name='Non subsidised net price'),
        ),
        migrations.AddField(
            model_name='reservationstatistic',
            name='recurrence_begin_date',
            field=models.DateField(null=True, verbose_name='Recurrence begin date'),
        ),
        migrations.AddField(
            model_name='reservationstatistic',
            name='recurrence_end_date',
            field=models.DateField(null=True, verbose_name='Recurrence end date'),
        ),
        migrations.AddField(
            model_name='reservationstatistic',
            name='recurrence_uuid',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Recurrence UUID'),
        ),
        migrations.AddField(
            model_name='reservationstatistic',
            name='reservee_uuid',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Reservee UUID'),
        ),
    ]
