# Generated by Django 3.2.18 on 2023-03-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0045_reservee_stats_field_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('blocked', 'Blocked'), ('staff', 'Staff'), ('behalf', 'Behalf')], default='normal', help_text='Type of reservation', max_length=50, null=True),
        ),
    ]
