# Generated by Django 3.2.18 on 2023-04-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0046_alter_reservation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationstatistic',
            name='age_group_max',
        ),
        migrations.RemoveField(
            model_name='reservationstatistic',
            name='age_group_min',
        ),
        migrations.AddField(
            model_name='reservationstatistic',
            name='age_group_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reservationstatistic',
            name='buffer_time_after',
            field=models.DurationField(blank=True, null=True, verbose_name='Buffer time after'),
        ),
        migrations.AddField(
            model_name='reservationstatistic',
            name='buffer_time_before',
            field=models.DurationField(blank=True, null=True, verbose_name='Buffer time before'),
        ),
        migrations.AddField(
            model_name='reservationstatistic',
            name='home_city_municipality_code',
            field=models.CharField(default='', max_length=30, verbose_name='Home city municipality code'),
        ),
        migrations.AddField(
            model_name='reservationstatistic',
            name='home_city_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Home city name'),
        ),
        migrations.AddField(
            model_name='reservationstatistic',
            name='price_net',
            field=models.DecimalField(decimal_places=6, default=0, help_text='The price of this particular reservation excluding VAT', max_digits=20, verbose_name='Price net'),
        ),
        migrations.AddField(
            model_name='reservationstatistic',
            name='priority_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reservationstatistic',
            name='purpose_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='reservationstatistic',
            name='reservee_is_unregistered_association',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Reservee is an unregistered association'),
        ),
    ]
