# Generated by Django 3.2.18 on 2023-04-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0047_reservation_stats_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('created', 'created'), ('cancelled', 'cancelled'), ('requires_handling', 'requires_handling'), ('waiting_for_payment', 'waiting_for_payment'), ('confirmed', 'confirmed'), ('denied', 'denied')], db_index=True, default='created', max_length=32, verbose_name='State'),
        ),
    ]
