# Generated by Django 3.2.18 on 2023-04-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0048_add_db_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='billing_address_street',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Billing address street'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='billing_address_zip',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Billing address zip code'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='non_subsidised_price',
            field=models.DecimalField(decimal_places=6, default=0, help_text='The non subsidised price of this reservation including VAT', max_digits=20, verbose_name='Non subsidised price'),
        ),
    ]
