# Generated by Django 4.2.1 on 2023-06-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0051_refesh_reservation_statistics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="reservee_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Reservee's business or association identity code",
                max_length=255,
                verbose_name="Reservee ID",
            ),
        ),
    ]
