# Generated by Django 4.2.4 on 2023-10-16 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation_units", "0085_surface_area_to_integer"),
        ("applications", "0066_remove_applicationaggregatedata_application_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reservations", "0052_alter_reservation_reservee_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recurringreservation",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterField(
            model_name="abilitygroup",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="abilitygroup",
            name="name_en",
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="abilitygroup",
            name="name_fi",
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="abilitygroup",
            name="name_sv",
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="agegroup",
            name="maximum",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agegroup",
            name="minimum",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="recurringreservation",
            name="ability_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurring_reservations",
                to="reservations.AbilityGroup",
            ),
        ),
        migrations.AlterField(
            model_name="recurringreservation",
            name="age_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurring_reservations",
                to="reservations.AgeGroup",
            ),
        ),
        migrations.AlterField(
            model_name="recurringreservation",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recurring_reservations",
                to="applications.Application",
            ),
        ),
        migrations.AlterField(
            model_name="recurringreservation",
            name="application_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recurring_reservations",
                to="applications.ApplicationEvent",
            ),
        ),
        migrations.AlterField(
            model_name="recurringreservation",
            name="begin_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="recurringreservation",
            name="begin_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="recurringreservation",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="recurringreservation",
            name="end_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="recurringreservation",
            name="recurrence_in_days",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="recurringreservation",
            name="reservation_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recurring_reservations",
                to="reservation_units.ReservationUnit",
            ),
        ),
        migrations.AlterField(
            model_name="recurringreservation",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_type",
            field=models.CharField(
                blank=True,
                choices=[("BUSINESS", "Business"), ("NONPROFIT", "Nonprofit"), ("INDIVIDUAL", "Individual")],
                help_text="Type of reservee",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="state",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("cancelled", "Cancelled"),
                    ("requires_handling", "Requires handling"),
                    ("waiting_for_payment", "Waiting for payment"),
                    ("confirmed", "Confirmed"),
                    ("denied", "Denied"),
                ],
                db_index=True,
                default="created",
                max_length=32,
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="reservationcancelreason",
            name="reason",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="reservationcancelreason",
            name="reason_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="reservationcancelreason",
            name="reason_fi",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="reservationcancelreason",
            name="reason_sv",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="reservationdenyreason",
            name="reason",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="reservationdenyreason",
            name="reason_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="reservationdenyreason",
            name="reason_fi",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="reservationdenyreason",
            name="reason_sv",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="reservee_type",
            field=models.CharField(
                blank=True,
                choices=[("BUSINESS", "Business"), ("NONPROFIT", "Nonprofit"), ("INDIVIDUAL", "Individual")],
                help_text="Type of reservee",
                max_length=50,
                null=True,
            ),
        ),
    ]
