# Generated by Django 4.2.6 on 2023-10-26 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0067_remove_applicationevent_declined_reservation_units'),
        ('reservations', '0053_alter_recurringreservation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringreservation',
            name='application',
        ),
        migrations.RemoveField(
            model_name='recurringreservation',
            name='application_event',
        ),
        migrations.AddField(
            model_name='recurringreservation',
            name='application_event_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_reservations', to='applications.applicationeventschedule'),
        ),
    ]
