# Generated by Django 4.2.6 on 2023-10-26 05:57

import django.db.models.deletion
from django.db import migrations, models


def add_first_event_schedule(apps, schema_editor):
    RecurringReservation = apps.get_model("reservations", "RecurringReservation")
    for recurring in RecurringReservation.objects.all():
        recurring.application_event_schedule = recurring.application_event.application_event_schedule.first()
        recurring.save()


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0067_remove_applicationevent_declined_reservation_units'),
        ('reservations', '0053_alter_recurringreservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringreservation',
            name='application_event_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_reservations', to='applications.applicationeventschedule'),
        ),
        migrations.RunPython(add_first_event_schedule, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='recurringreservation',
            name='application',
        ),
        migrations.RemoveField(
            model_name='recurringreservation',
            name='application_event',
        ),
    ]
