# Generated by Django 4.2.9 on 2024-01-31 09:00

import datetime

from django.db import migrations


def update_null_buffers_to_zero(apps, schema_editor):
    Reservation = apps.get_model("reservations", "Reservation")
    Reservation.objects.filter(buffer_time_before=None).update(buffer_time_before=datetime.timedelta())
    Reservation.objects.filter(buffer_time_after=None).update(buffer_time_after=datetime.timedelta())

    ReservationStatistic = apps.get_model("reservations", "ReservationStatistic")
    ReservationStatistic.objects.filter(buffer_time_before=None).update(buffer_time_before=datetime.timedelta())
    ReservationStatistic.objects.filter(buffer_time_after=None).update(buffer_time_after=datetime.timedelta())


def update_zero_buffers_to_null(apps, schema_editor):
    Reservation = apps.get_model("reservations", "Reservation")
    Reservation.objects.filter(buffer_time_before=datetime.timedelta()).update(buffer_time_before=None)
    Reservation.objects.filter(buffer_time_after=datetime.timedelta()).update(buffer_time_after=None)

    ReservationStatistic = apps.get_model("reservations", "ReservationStatistic")
    ReservationStatistic.objects.filter(buffer_time_before=datetime.timedelta()).update(buffer_time_before=None)
    ReservationStatistic.objects.filter(buffer_time_after=datetime.timedelta()).update(buffer_time_after=None)


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0060_change_database_table_names"),
    ]

    operations = [
        migrations.RunPython(update_null_buffers_to_zero, update_zero_buffers_to_null),
    ]
