# Generated by Django 4.2.9 on 2024-01-31 09:00

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0061_buffers_from_null_to_zero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="buffer_time_after",
            field=models.DurationField(
                blank=True,
                default=datetime.timedelta(0),
                verbose_name="Buffer time after",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="buffer_time_before",
            field=models.DurationField(
                blank=True,
                default=datetime.timedelta(0),
                verbose_name="Buffer time before",
            ),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="buffer_time_after",
            field=models.DurationField(
                blank=True,
                default=datetime.timedelta(0),
                verbose_name="Buffer time after",
            ),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="buffer_time_before",
            field=models.DurationField(
                blank=True,
                default=datetime.timedelta(0),
                verbose_name="Buffer time before",
            ),
        ),
    ]
