# Generated by Django 4.2.9 on 2024-01-31 12:55

import datetime

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.math
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import applications.choices
import common.fields.model
import reservations.choices
import tilavarauspalvelu.utils.commons


class Migration(migrations.Migration):
    dependencies = [
        ("reservation_units", "0095_alter_reservationunit_buffer_time_after_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("applications", "0079_change_database_table_names"),
        ("reservations", "0062_alter_reservation_buffer_time_after_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recurringreservation",
            options={
                "base_manager_name": "objects",
                "ordering": ["begin_date", "begin_time", "reservation_unit"],
            },
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="reservation_unit",
        ),
        migrations.AddField(
            model_name="reservation",
            name="reservation_units",
            field=models.ManyToManyField(
                related_name="reservations",
                to="reservation_units.reservationunit",
            ),
        ),
        migrations.AlterField(
            model_name="recurringreservation",
            name="begin_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recurringreservation",
            name="begin_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recurringreservation",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recurringreservation",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recurringreservation",
            name="recurrence_in_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recurringreservation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurring_reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="age_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="reservations.agegroup",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="applying_for_free_of_charge",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="begin",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="billing_address_city",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="billing_address_street",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="billing_address_zip",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="billing_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="billing_first_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="billing_last_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="billing_phone",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="buffer_time_after",
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="buffer_time_before",
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="cancel_details",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="cancel_reason",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="reservations.reservationcancelreason",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="confirmed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="deny_reason",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="reservations.reservationdenyreason",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="end",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="free_of_charge_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="handled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="handling_details",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="home_city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="applications.city",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="non_subsidised_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="non_subsidised_price_net",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="num_persons",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="price_net",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="priority",
            field=common.fields.model.IntChoiceField(
                default=200,
                enum=applications.choices.PriorityChoice,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=100,
                        message="Value must be between 100 and 300.",
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=300,
                        message="Value must be between 100 and 300.",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="purpose",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="reservations.reservationpurpose",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="recurring_reservation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="reservations.recurringreservation",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_address_city",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_address_street",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_address_zip",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_first_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_is_unregistered_association",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_language",
            field=common.fields.model.StrChoiceField(
                blank=True,
                choices=[("fi", "Finnish"), ("sv", "Swedish"), ("en", "English")],
                enum=tilavarauspalvelu.utils.commons.Language,
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_last_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_organisation_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_phone",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_type",
            field=common.fields.model.StrChoiceField(
                blank=True,
                choices=[("BUSINESS", "Business"), ("NONPROFIT", "Nonprofit"), ("INDIVIDUAL", "Individual")],
                enum=reservations.choices.CustomerTypeChoice,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="sku",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="state",
            field=common.fields.model.StrChoiceField(
                choices=[
                    ("CREATED", "Created"),
                    ("CANCELLED", "Cancelled"),
                    ("REQUIRES_HANDLING", "Requires handling"),
                    ("WAITING_FOR_PAYMENT", "Waiting for payment"),
                    ("CONFIRMED", "Confirmed"),
                    ("DENIED", "Denied"),
                ],
                db_index=True,
                default="CREATED",
                enum=reservations.choices.ReservationStateChoice,
                max_length=19,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="tax_percentage_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="type",
            field=common.fields.model.StrChoiceField(
                choices=[("NORMAL", "Normal"), ("BLOCKED", "Blocked"), ("STAFF", "Staff"), ("BEHALF", "Behalf")],
                default="NORMAL",
                enum=reservations.choices.ReservationTypeChoice,
                max_length=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="working_memo",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="reservationmetadatafield",
            name="field_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="reservationmetadataset",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="reservationmetadataset",
            name="required_fields",
            field=models.ManyToManyField(
                blank=True,
                related_name="metadata_sets_required",
                to="reservations.reservationmetadatafield",
            ),
        ),
        migrations.AlterField(
            model_name="reservationmetadataset",
            name="supported_fields",
            field=models.ManyToManyField(
                related_name="metadata_sets_supported",
                to="reservations.reservationmetadatafield",
            ),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="ability_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservation_statistics",
                to="reservations.abilitygroup",
            ),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="ability_group_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="age_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservation_statistics",
                to="reservations.agegroup",
            ),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="applying_for_free_of_charge",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="begin",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="buffer_time_after",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="buffer_time_before",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="cancel_reason",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservation_statistics",
                to="reservations.reservationcancelreason",
            ),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="cancel_reason_text",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="deny_reason",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservation_statistics",
                to="reservations.reservationdenyreason",
            ),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="deny_reason_text",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="duration_minutes",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="end",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="home_city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservation_statistics",
                to="applications.city",
            ),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="home_city_municipality_code",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="home_city_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="is_applied",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="is_recurring",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="is_subsidised",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="non_subsidised_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="non_subsidised_price_net",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="num_persons",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="price_net",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="primary_reservation_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservation_statistics",
                to="reservation_units.reservationunit",
            ),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="primary_reservation_unit_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="primary_unit_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="primary_unit_tprek_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="priority",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="purpose",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservation_statistics",
                to="reservations.reservationpurpose",
            ),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="recurrence_begin_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="recurrence_end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="recurrence_uuid",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="reservation",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservation_statistic",
                to="reservations.reservation",
            ),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="reservation_confirmed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="reservation_created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="reservation_handled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="reservation_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="reservee_is_unregistered_association",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="reservee_language",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="reservee_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="reservee_uuid",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="state",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="tax_percentage_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatisticsreservationunit",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="reservationstatisticsreservationunit",
            name="reservation_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservation_stats_reservation_units",
                to="reservation_units.reservationunit",
            ),
        ),
        migrations.AlterField(
            model_name="reservationstatisticsreservationunit",
            name="unit_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="reservationstatisticsreservationunit",
            name="unit_tprek_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
