# Generated by Django 4.2.10 on 2024-02-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0062_alter_reservation_buffer_time_after_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='priority',
        ),
    ]
