# Generated by Django 4.2.10 on 2024-02-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0063_remove_reservation_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationstatistic',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(100, 'Low'), (200, 'Medium'), (300, 'High')], default=200, null=True),
        ),
    ]
