# Generated by Django 5.0.3 on 2024-03-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0064_alter_reservationstatistic_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringreservation',
            options={'base_manager_name': 'objects', 'ordering': ['begin_date', 'begin_time', 'reservation_unit']},
        ),
    ]
