# Generated by Django 4.2.7 on 2023-11-23 10:28

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.functions.math
from django.db import migrations

import applications.choices
import common.fields.model


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0064_update_reservation_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringreservation",
            # Use an intermediate name for migrations
            name="weekdays_new",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=common.fields.model.IntChoiceField(
                    enum=applications.choices.WeekdayChoice,
                    validators=[
                        django.core.validators.MinValueValidator(
                            limit_value=0, message="Value must be between 0 and 6."
                        ),
                        django.core.validators.MaxValueValidator(
                            limit_value=6, message="Value must be between 0 and 6."
                        ),
                    ],
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
