# Generated by Django 5.0.3 on 2024-03-18 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0065_alter_recurringreservation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'base_manager_name': 'objects', 'ordering': ['begin']},
        ),
    ]
