# Generated by Django 5.0.3 on 2024-03-25 08:49

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0085_alter_applicationsection_options"),
        ("reservation_units", "0098_alter_reservationunit_options_and_more"),
        ("reservations", "0066_alter_reservation_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="age_group",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="reservations.agegroup"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="applying_for_free_of_charge",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="begin",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="billing_address_city",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="billing_address_street",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="billing_address_zip",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="billing_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="billing_first_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="billing_last_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="billing_phone",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="buffer_time_after",
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="buffer_time_before",
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="cancel_details",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="cancel_reason",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="reservations.reservationcancelreason",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="confirmed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="deny_reason",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="reservations.reservationdenyreason",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="end",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="free_of_charge_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="handled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="handling_details",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="home_city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="home_city_reservation",
                to="applications.city",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="non_subsidised_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="non_subsidised_price_net",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="num_persons",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="price_net",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="purpose",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reservations.reservationpurpose",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="recurring_reservation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="reservations.recurringreservation",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_unit",
            field=models.ManyToManyField(to="reservation_units.reservationunit"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_address_city",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_address_street",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_address_zip",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_first_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_is_unregistered_association",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_language",
            field=models.CharField(
                blank=True,
                choices=[("fi", "Finnish"), ("en", "English"), ("sv", "Swedish"), ("", "")],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_last_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_organisation_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_phone",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_type",
            field=models.CharField(
                blank=True,
                choices=[("business", "Business"), ("nonprofit", "Nonprofit"), ("individual", "Individual")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="sku",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="state",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("cancelled", "Cancelled"),
                    ("requires_handling", "Requires handling"),
                    ("waiting_for_payment", "Waiting for payment"),
                    ("confirmed", "Confirmed"),
                    ("denied", "Denied"),
                ],
                db_index=True,
                default="created",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="tax_percentage_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="type",
            field=models.CharField(
                choices=[("normal", "Normal"), ("blocked", "Blocked"), ("staff", "Staff"), ("behalf", "Behalf")],
                default="normal",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="working_memo",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
