# Generated by Django 4.2.7 on 2023-11-23 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0066_update_recurring_reservation_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringreservation",
            name="weekdays",
        ),
        migrations.RenameField(
            model_name="recurringreservation",
            old_name="weekdays_new",
            new_name="weekdays",
        ),
    ]
