# Generated by Django 5.0.4 on 2024-04-08 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0067_alter_reservation_age_group_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="abilitygroup",
            options={"base_manager_name": "objects", "ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="agegroup",
            options={"base_manager_name": "objects", "ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="reservationcancelreason",
            options={"base_manager_name": "objects", "ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="reservationdenyreason",
            options={"base_manager_name": "objects", "ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="reservationmetadatafield",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "Reservation metadata field",
                "verbose_name_plural": "Reservation metadata fields",
            },
        ),
        migrations.AlterModelOptions(
            name="reservationmetadataset",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "Reservation metadata set",
                "verbose_name_plural": "Reservation metadata sets",
            },
        ),
        migrations.AlterModelOptions(
            name="reservationpurpose",
            options={"base_manager_name": "objects", "ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="reservationstatistic",
            options={"base_manager_name": "objects", "ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="reservationstatisticsreservationunit",
            options={"base_manager_name": "objects", "ordering": ["pk"]},
        ),
    ]
