# Generated by Django 5.0.4 on 2024-05-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0068_alter_abilitygroup_options_alter_agegroup_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="type",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("blocked", "Blocked"),
                    ("staff", "Staff"),
                    ("behalf", "Behalf"),
                    ("seasonal", "Seasonal"),
                ],
                default="normal",
                max_length=50,
                null=True,
            ),
        ),
    ]
