# Generated by Django 5.0.6 on 2024-05-29 05:29

import django.db.models.deletion
import graphene_django_extensions.fields.model
from django.db import migrations, models

import reservations.choices


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0070_recurringreservation_allocated_time_slot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RejectedOccurrence",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("begin_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "rejection_reason",
                    graphene_django_extensions.fields.model.StrChoiceField(
                        choices=[
                            ("INTERVAL_NOT_ALLOWED", "Interval not allowed"),
                            ("OVERLAPPING_RESERVATIONS", "Overlapping reservations"),
                            ("RESERVATION_UNIT_CLOSED", "Reservation unit closed"),
                        ],
                        enum=reservations.choices.RejectionReadinessChoice,
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recurring_reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rejected_occurrences",
                        to="reservations.recurringreservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rejected occurrence",
                "verbose_name_plural": "Rejected occurrences",
                "db_table": "rejected_occurrence",
                "ordering": ["begin_datetime", "end_datetime"],
                "base_manager_name": "objects",
            },
        ),
    ]
