# Generated by Django 5.0.7 on 2024-08-07 06:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0075_reservationstatistic_reservee_address_zip_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringreservation",
            name="application_event_schedule",
        ),
    ]
