# Generated by Django 5.0.7 on 2024-08-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0076_uppercase_enums"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationstatistic",
            name="reservee_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
