# Generated by Django 5.0.6 on 2024-06-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0077_alter_reservationstatistic_reservee_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservationdenyreason",
            options={"base_manager_name": "objects", "ordering": ["rank"]},
        ),
        migrations.AddField(
            model_name="reservationdenyreason",
            name="rank",
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
