# Generated by Django 5.0.7 on 2024-08-07 06:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0079_fix_reservation_price_net"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringreservation",
            name="application_event_schedule",
        ),
    ]
