# Generated by Django 5.0.8 on 2024-08-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0080_remove_recurringreservation_application_event_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="non_subsidised_price_net",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="price_net",
        ),
    ]
