# Generated by Django 5.1 on 2024-09-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0080_remove_recurringreservation_application_event_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="reservee_used_ad_login",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="reservationstatistic",
            name="reservee_used_ad_login",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
