# Generated by Django 5.1.1 on 2024-09-26 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0095_alter_applicationround_purposes_and_more"),
        ("reservation_units", "0111_alter_reservationunit_metadata_set"),
        ("reservations", "0083_remove_recurringreservation_ability_group_and_more"),
        ("tilavarauspalvelu", "0011_migrate_reservations"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="AgeGroup",
                ),
                migrations.DeleteModel(
                    name="RejectedOccurrence",
                ),
                migrations.DeleteModel(
                    name="RecurringReservation",
                ),
                migrations.DeleteModel(
                    name="Reservation",
                ),
                migrations.DeleteModel(
                    name="AffectingTimeSpan",
                ),
                migrations.DeleteModel(
                    name="ReservationCancelReason",
                ),
                migrations.DeleteModel(
                    name="ReservationDenyReason",
                ),
                migrations.DeleteModel(
                    name="ReservationMetadataField",
                ),
                migrations.DeleteModel(
                    name="ReservationMetadataSet",
                ),
                migrations.DeleteModel(
                    name="ReservationPurpose",
                ),
                migrations.DeleteModel(
                    name="ReservationStatistic",
                ),
                migrations.DeleteModel(
                    name="ReservationStatisticsReservationUnit",
                ),
            ],
            database_operations=[],
        ),
    ]
