# Generated by Django 3.0.10 on 2020-10-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Area",
            ),
        ),
        migrations.AlterField(
            model_name="space",
            name="area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Area",
            ),
        ),
    ]
