# Generated by Django 3.0.10 on 2020-11-19 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='area',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='area',
        ),
        migrations.RemoveField(
            model_name='space',
            name='area',
        ),
        migrations.AddField(
            model_name='building',
            name='surface_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Surface area'),
        ),
        migrations.AddField(
            model_name='district',
            name='district_type',
            field=models.CharField(choices=[('major_district', 'Major district'), ('district', 'District'), ('sub_district', 'Sub district'), ('neighborhood', 'Neighborhood')], default='district', max_length=30, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='district',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='spaces.District', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='surface_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Surface area'),
        ),
        migrations.AddField(
            model_name='space',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spaces', to='spaces.District', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='space',
            name='max_persons',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum number of persons'),
        ),
        migrations.AddField(
            model_name='space',
            name='surface_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Surface area'),
        ),
        migrations.AlterField(
            model_name='building',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to='spaces.District', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='building',
            name='real_estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to='spaces.RealEstate', verbose_name='Real estate'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estates', to='spaces.District', verbose_name='District'),
        ),
    ]
