# Generated by Django 3.0.10 on 2020-12-11 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0004_mptt_tree_hierarchy_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='location',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='location',
        ),
        migrations.RemoveField(
            model_name='space',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='building',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='spaces.Building', verbose_name='Building'),
        ),
        migrations.AddField(
            model_name='location',
            name='real_estate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='spaces.RealEstate', verbose_name='RealEstate'),
        ),
        migrations.AddField(
            model_name='location',
            name='space',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='spaces.Space', verbose_name='Space'),
        ),
    ]
