# Generated by Django 3.0.10 on 2021-01-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0009_add_coordinates_and_unit_to_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
