# Generated by Django 3.0.10 on 2021-01-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0008_reservationunit_unit'),
        ('spaces', '0009_add_coordinates_and_unit_to_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='ServiceSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_fi', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_sv', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('purposes', models.ManyToManyField(related_name='service_sectors', to='reservation_units.Purpose', verbose_name='Purposes')),
                ('units', models.ManyToManyField(related_name='service_sectors', to='spaces.Unit', verbose_name='Units')),
            ],
        ),
    ]
