# Generated by Django 3.0.10 on 2021-01-28 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0010_service_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spaces', to='spaces.Unit', verbose_name='Unit'),
        ),
    ]
