# Generated by Django 3.1.7 on 2021-03-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0013_unitgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='service_map_id',
        ),
        migrations.AddField(
            model_name='unit',
            name='tprek_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='TPREK id'),
        ),
    ]
