# Generated by Django 3.1.7 on 2021-03-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0014_unit_rename_service_map_id_to_tprek_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address_street_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address street'),
        ),
        migrations.AddField(
            model_name='location',
            name='address_street_fi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address street'),
        ),
        migrations.AddField(
            model_name='location',
            name='address_street_sv',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address street'),
        ),
    ]
