# Generated by Django 3.1.7 on 2021-03-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0015_location_add_address_street_to_translated_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='description_en',
            field=models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='unit',
            name='description_fi',
            field=models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='unit',
            name='description_sv',
            field=models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Description'),
        ),
    ]
