# Generated by Django 3.1.13 on 2021-10-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0016_space_terms_of_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='building',
            name='name_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='building',
            name='name_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='location',
            name='address_city_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address city'),
        ),
        migrations.AddField(
            model_name='location',
            name='address_city_fi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address city'),
        ),
        migrations.AddField(
            model_name='location',
            name='address_city_sv',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address city'),
        ),
        migrations.AddField(
            model_name='location',
            name='address_street_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address street'),
        ),
        migrations.AddField(
            model_name='location',
            name='address_street_fi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address street'),
        ),
        migrations.AddField(
            model_name='location',
            name='address_street_sv',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address street'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='name_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='name_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='space',
            name='terms_of_use_en',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='Terms of use'),
        ),
        migrations.AddField(
            model_name='space',
            name='terms_of_use_fi',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='Terms of use'),
        ),
        migrations.AddField(
            model_name='space',
            name='terms_of_use_sv',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='Terms of use'),
        ),
        migrations.AddField(
            model_name='unit',
            name='description_en',
            field=models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='unit',
            name='description_fi',
            field=models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='unit',
            name='description_sv',
            field=models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='unit',
            name='short_description_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='unit',
            name='short_description_fi',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='unit',
            name='short_description_sv',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='unitgroup',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='unitgroup',
            name='name_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='unitgroup',
            name='name_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
