# Generated by Django 3.1.7 on 2021-03-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0016_unit_add_description_to_translated_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='short_description_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='unit',
            name='short_description_fi',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='unit',
            name='short_description_sv',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Short description'),
        ),
    ]
