# Generated by Django 3.1.13 on 2021-11-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0017_missing_translated_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='hauki_resource_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hauki resource id'),
        ),
        migrations.AddField(
            model_name='unit',
            name='tprek_department_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TPREK department id'),
        ),
    ]
