# Generated by Django 3.1.13 on 2021-11-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_delete_old_purposes'),
        ('spaces', '0018_unit_tprek_department_id_and_hauki_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesector',
            name='purposes',
            field=models.ManyToManyField(related_name='service_sectors', to='reservations.ReservationPurpose', verbose_name='Purposes'),
        ),
    ]
