# Generated by Django 3.1.13 on 2021-11-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0019_service_sector_reservation_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='terms_of_use',
        ),
        migrations.RemoveField(
            model_name='space',
            name='terms_of_use_en',
        ),
        migrations.RemoveField(
            model_name='space',
            name='terms_of_use_fi',
        ),
        migrations.RemoveField(
            model_name='space',
            name='terms_of_use_sv',
        ),
    ]
