# Generated by Django 3.2.15 on 2022-09-02 15:15

from django.db import migrations, models
from django.db.models import F


def update_ranks(apps, schema_editor):
    Unit = apps.get_model("spaces", "Unit")

    Unit.objects.update(rank=F("pk"))


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0020_remove_terms_of_use"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="rank",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Order number to be use in api sorting.",
                null=True,
                verbose_name="Order number",
            ),
        ),
        migrations.RunPython(update_ranks, migrations.RunPython.noop),
    ]
