# Generated by Django 3.1.14 on 2022-01-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0020_remove_terms_of_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesector',
            name='merchant_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Merchant ID'),
        ),
    ]
