# Generated by Django 3.2.15 on 2022-09-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0021_unit_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesector',
            name='purposes',
        ),
    ]
