# Generated by Django 3.2.15 on 2022-09-29 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0022_remove_servicesector_purposes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['rank']},
        ),
    ]
