# Generated by Django 3.2.15 on 2022-09-29 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("merchants", "0001_initial"),
        ("spaces", "0023_alter_unit_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="payment_merchant",
            field=models.ForeignKey(
                help_text="Merchant used for payments",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="units",
                to="merchants.PaymentMerchant",
                verbose_name="Payment merchant",
            ),
        ),
    ]
