# Generated by Django 3.2.15 on 2022-10-10 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_paymentproduct'),
        ('spaces', '0024_add_payment_merchant_to_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='payment_merchant',
            field=models.ForeignKey(blank=True, help_text='Merchant used for payments', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='merchants.paymentmerchant', verbose_name='Payment merchant'),
        ),
    ]
