# Generated by Django 3.2.18 on 2023-03-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0026_unit_payment_accounting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description_en',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description_fi',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description_sv',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Description'),
        ),
    ]
