# Generated by Django 3.2.18 on 2023-04-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0027_increase_description_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, default='', max_length=4000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description_en',
            field=models.TextField(blank=True, default='', max_length=4000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description_fi',
            field=models.TextField(blank=True, default='', max_length=4000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description_sv',
            field=models.TextField(blank=True, default='', max_length=4000, null=True, verbose_name='Description'),
        ),
    ]
