# Generated by Django 4.2.1 on 2023-06-19 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0065_remove_applicationevent_district"),
        ("spaces", "0028_increase_description_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="district",
        ),
        migrations.RemoveField(
            model_name="realestate",
            name="district",
        ),
        migrations.RemoveField(
            model_name="space",
            name="district",
        ),
        migrations.DeleteModel(
            name="District",
        ),
    ]
