# Generated by Django 4.2.1 on 2023-06-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0029_remove_building_district_remove_realestate_district_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="space",
            name="surface_area",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Surface area"
            ),
        ),
    ]
