# Generated by Django 4.2.6 on 2023-10-24 21:50

from django.db import migrations


def migrate_hauki_resource_id(apps, schema_editor):
    Unit = apps.get_model("spaces", "Unit")
    OriginHaukiResource = apps.get_model("opening_hours", "OriginHaukiResource")

    units = Unit.objects.exclude(hauki_resource_id="").exclude(hauki_resource_id__isnull=True)
    for unit in units:
        origin_hauki_resource, _ = OriginHaukiResource.objects.get_or_create(id=unit.hauki_resource_id)
        unit.origin_hauki_resource = origin_hauki_resource
        unit.save()

class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0031_add_origin_hauki_resource_field'),
        ('opening_hours', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_hauki_resource_id, reverse_code=migrations.RunPython.noop),
    ]
