# Generated by Django 4.2.7 on 2023-12-01 09:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("merchants", "0013_alter_paymentorder_reservation"),
        ("spaces", "0033_depracate_hauki_resource_id_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="building",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="name_fi",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="name_sv",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="real_estate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buildings",
                to="spaces.RealEstate",
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="surface_area",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="address_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="location",
            name="address_city_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="address_city_fi",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="address_city_sv",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="address_street",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="location",
            name="address_street_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="address_street_fi",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="address_street_sv",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="address_zip",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="location",
            name="building",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location",
                to="spaces.Building",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name="location",
            name="real_estate",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location",
                to="spaces.RealEstate",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="space",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location",
                to="spaces.Space",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="unit",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location",
                to="spaces.Unit",
            ),
        ),
        migrations.AlterField(
            model_name="realestate",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="realestate",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="realestate",
            name="name_fi",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="realestate",
            name="name_sv",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="realestate",
            name="surface_area",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="servicesector",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="servicesector",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="servicesector",
            name="name_fi",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="servicesector",
            name="name_sv",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="servicesector",
            name="units",
            field=models.ManyToManyField(related_name="service_sectors", to="spaces.Unit"),
        ),
        migrations.AlterField(
            model_name="space",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="spaces",
                to="spaces.Building",
            ),
        ),
        migrations.AlterField(
            model_name="space",
            name="code",
            field=models.CharField(blank=True, db_index=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="space",
            name="max_persons",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="space",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="space",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="space",
            name="name_fi",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="space",
            name="name_sv",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="space",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="spaces.Space",
            ),
        ),
        migrations.AlterField(
            model_name="space",
            name="surface_area",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="space",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="spaces",
                to="spaces.Unit",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="description",
            field=models.TextField(blank=True, default="", max_length=4000),
        ),
        migrations.AlterField(
            model_name="unit",
            name="description_en",
            field=models.TextField(blank=True, default="", max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="description_fi",
            field=models.TextField(blank=True, default="", max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="description_sv",
            field=models.TextField(blank=True, default="", max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name_fi",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name_sv",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="payment_accounting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="units",
                to="merchants.PaymentAccounting",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="payment_merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="units",
                to="merchants.PaymentMerchant",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="unit",
            name="rank",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="short_description",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="unit",
            name="short_description_en",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="short_description_fi",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="short_description_sv",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="tprek_department_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="tprek_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="web_page",
            field=models.URLField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="unitgroup",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="unitgroup",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="unitgroup",
            name="name_fi",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="unitgroup",
            name="name_sv",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterModelOptions(
            name="space",
            options={"base_manager_name": "objects"},
        ),
    ]
