# Generated by Django 4.2.9 on 2024-01-23 07:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0034_alter_building_name_alter_building_name_en_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="building",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="realestate",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="servicesector",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="unit",
            options={"base_manager_name": "objects", "ordering": ["rank"]},
        ),
        migrations.AlterModelOptions(
            name="unitgroup",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelTable(
            name="building",
            table="building",
        ),
        migrations.AlterModelTable(
            name="location",
            table="location",
        ),
        migrations.AlterModelTable(
            name="realestate",
            table="real_estate",
        ),
        migrations.AlterModelTable(
            name="servicesector",
            table="service_sector",
        ),
        migrations.AlterModelTable(
            name="space",
            table="space",
        ),
        migrations.AlterModelTable(
            name="unit",
            table="unit",
        ),
        migrations.AlterModelTable(
            name="unitgroup",
            table="unit_group",
        ),
    ]
