# Generated by Django 4.2.9 on 2024-01-23 07:12

from django.db import migrations

from utils.migration import AlterModelTable


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0035_add_base_manager_name_to_all_models"),
    ]

    operations = [
        AlterModelTable(
            name="building",
            table="building",
        ),
        AlterModelTable(
            name="location",
            table="location",
        ),
        AlterModelTable(
            name="realestate",
            table="real_estate",
        ),
        AlterModelTable(
            name="servicesector",
            table="service_sector",
        ),
        AlterModelTable(
            name="space",
            table="space",
        ),
        AlterModelTable(
            name="unit",
            table="unit",
        ),
        AlterModelTable(
            name="unitgroup",
            table="unit_group",
        ),
    ]
