# Generated by Django 5.0.4 on 2024-05-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0038_unit_group_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="tprek_last_modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
