# Generated by Django 5.1.1 on 2024-09-19 05:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0040_alter_unit_payment_accounting_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="space",
                    name="building",
                ),
                migrations.RemoveField(
                    model_name="location",
                    name="building",
                ),
                migrations.RemoveField(
                    model_name="location",
                    name="real_estate",
                ),
                migrations.RemoveField(
                    model_name="location",
                    name="space",
                ),
                migrations.RemoveField(
                    model_name="location",
                    name="unit",
                ),
                migrations.RemoveField(
                    model_name="servicesector",
                    name="units",
                ),
                migrations.RemoveField(
                    model_name="space",
                    name="parent",
                ),
                migrations.RemoveField(
                    model_name="space",
                    name="unit",
                ),
                migrations.RemoveField(
                    model_name="unit",
                    name="origin_hauki_resource",
                ),
                migrations.RemoveField(
                    model_name="unit",
                    name="payment_accounting",
                ),
                migrations.RemoveField(
                    model_name="unit",
                    name="payment_merchant",
                ),
                migrations.RemoveField(
                    model_name="unitgroup",
                    name="units",
                ),
                migrations.DeleteModel(
                    name="Building",
                ),
                migrations.DeleteModel(
                    name="RealEstate",
                ),
                migrations.DeleteModel(
                    name="Location",
                ),
                migrations.DeleteModel(
                    name="ServiceSector",
                ),
            ],
            database_operations=[],
        ),
    ]
