# Generated by Django 5.1.1 on 2024-09-19 05:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0034_alter_unitrole_unit_groups_alter_unitrole_units"),
        ("reservation_units", "0109_alter_reservationunit_spaces_and_more"),
        ("spaces", "0041_remove_space_building_remove_location_building_and_more"),
        ("tilavarauspalvelu", "0007_migrate_spaces"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Space",
                ),
                migrations.DeleteModel(
                    name="Unit",
                ),
                migrations.DeleteModel(
                    name="UnitGroup",
                ),
            ],
            database_operations=[],
        ),
    ]
