uwsgi:
  # Needed plugins if running against Debian uwsgi-package
  # python docker image cannot use that due to linker mishaps
  # plugins: python3,http
  wsgi-file: tilavarauspalvelu/wsgi.py
  processes: $(UWSGI_NUM_PROCESSES)
  threads: 1
  master: true
  #uid: tvp
  umask: 022
  reload-on-rss: 300
  http: :8000
  static-map: $(MEDIA_URL)=$(MEDIA_ROOT)