const config = {
  REACT_APP_TILAVARAUS_API_URL: process.env.REACT_APP_TILAVARAUS_API_URL,
  REACT_APP_SENTRY_DSN: process.env.REACT_APP_SENTRY_DSN,
  REACT_APP_SENTRY_ENVIRONMENT: process.env.REACT_APP_SENTRY_ENVIRONMENT,
  REACT_APP_VERSION: process.env.REACT_APP_VERSION,
  REACT_APP_OIDC_CLIENT_ID: process.env.REACT_APP_OIDC_CLIENT_ID,
  REACT_APP_DISABLE_AUTH: process.env.REACT_APP_DISABLE_AUTH,
};

module.exports = {
  REACT_APP_TILAVARAUS_API_URL: config.REACT_APP_TILAVARAUS_API_URL,
  REACT_APP_SENTRY_DSN: config.REACT_APP_SENTRY_DSN,
  REACT_APP_SENTRY_ENVIRONMENT: config.REACT_APP_SENTRY_ENVIRONMENT,
  REACT_APP_VERSION: config.REACT_APP_VERSION,
  REACT_APP_OIDC_CLIENT_ID: config.REACT_APP_OIDC_CLIENT_ID,
  REACT_APP_DISABLE_AUTH: config.REACT_APP_DISABLE_AUTH,
};
