const config = {
  REACT_APP_TILAVARAUS_API_URL: process.env.REACT_APP_TILAVARAUS_API_URL,
  REACT_APP_SENTRY_DSN: process.env.REACT_APP_SENTRY_DSN,
  REACT_APP_SENTRY_ENVIRONMENT: process.env.REACT_APP_SENTRY_ENVIRONMENT,
  REACT_APP_VERSION: process.env.REACT_APP_VERSION,
};

module.exports = {
  REACT_APP_TILAVARAUS_API_URL: config.REACT_APP_TILAVARAUS_API_URL,
  REACT_APP_SENTRY_DSN: config.REACT_APP_SENTRY_DSN,
  REACT_APP_SENTRY_ENVIRONMENT: config.REACT_APP_SENTRY_ENVIRONMENT,
  REACT_APP_VERSION: config.REACT_APP_VERSION,
};
