# Generated by Django 3.0.10 on 2020-11-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation_units", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purpose",
            name="reservation_unit",
            field=models.ManyToManyField(
                related_name="purposes",
                to="reservation_units.ReservationUnit",
                verbose_name="Purpose",
            ),
        ),
    ]
