# Generated by Django 3.0.10 on 2020-12-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0004_reservation_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purpose',
            name='name_fi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purpose',
            name='name_sv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='name_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='name_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
