# Generated by Django 3.0.10 on 2020-12-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0004_reservation_unit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purpose',
            name='reservation_unit',
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='purposes',
            field=models.ManyToManyField(blank=True, related_name='reservation_units', to='reservation_units.Purpose', verbose_name='Purposes'),
        ),
    ]
