# Generated by Django 3.0.10 on 2021-01-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0006_added_equipment_and_terms_of_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationunitimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='reservationunitimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image file'),
        ),
    ]
