# Generated by Django 3.1.7 on 2021-03-15 17:21

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0010_reservationunit_desc_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunitimage',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to='reservation_unit_images'),
        ),
    ]
