# Generated by Django 3.1.7 on 2021-03-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0011_reservationunitimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationunitimage',
            name='image_url',
        ),
    ]
