# Generated by Django 3.1.7 on 2021-04-07 08:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0012_remove_reservationunitimage_image_url'),
    ]

    def create_uuid(apps, schema_editor):
        ResevationUnit = apps.get_model('reservation_units', 'ReservationUnit')
        for unit in ResevationUnit.objects.all():
            unit.uuid = uuid.uuid4()
            unit.save()


    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='uuid',
            field=models.UUIDField(editable=False, unique=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='reservationunit',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=False),
        ),
    ]
