# Generated by Django 3.1.7 on 2021-03-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0012_remove_reservationunitimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='description_fi',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='description_sv',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
    ]
