# Generated by Django 3.1.8 on 2021-05-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0013_reservationunit_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='contact_information',
            field=models.TextField(blank=True, default='', verbose_name='Contact information'),
        ),
    ]
