# Generated by Django 3.1.13 on 2021-09-09 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0015_reservation_unit_max_and_min_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('keyword_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keyword_groups', to='reservation_units.keywordcategory', verbose_name='Keyword category')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('keyword_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keywords', to='reservation_units.keywordgroup', verbose_name='Keyword group')),
            ],
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='keyword_groups',
            field=models.ManyToManyField(blank=True, related_name='reservation_units', to='reservation_units.KeywordGroup', verbose_name='Keywords'),
        ),
    ]
