# Generated by Django 3.1.13 on 2021-09-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0016_reservation_unit_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationunit',
            name='keyword_groups',
            field=models.ManyToManyField(blank=True, related_name='reservation_units', to='reservation_units.KeywordGroup', verbose_name='Keyword groups'),
        ),
    ]
