# Generated by Django 3.1.13 on 2021-09-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0020_reservation_unit_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='description_fi',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='description_sv',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
    ]
