# Generated by Django 3.1.13 on 2021-09-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0021_reservation_unit_description_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='max_persons',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum number of persons'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='surface_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Surface area'),
        ),
    ]
