# Generated by Django 3.1.13 on 2021-09-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0022_reservation_unit_surface_area_and_max_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='buffer_time_between_reservations',
            field=models.DurationField(blank=True, null=True, verbose_name='Buffer time between reservations'),
        ),
    ]
