# Generated by Django 3.1.13 on 2021-11-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0024_missing_translated_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='hauki_resource_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hauki resource id'),
        ),
    ]
