# Generated by Django 3.1.13 on 2021-11-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0026_reservation_unit_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationunit',
            name='purposes',
        ),
        migrations.DeleteModel(
            name='ReservationUnitPurpose',
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='purposes',
            field=models.ManyToManyField(blank=True, related_name='reservation_units', to='reservation_units.Purpose',
                                         verbose_name='Purposes'),
        ),
    ]
