# Generated by Django 3.1.13 on 2021-12-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0029_terms_of_use_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='highest_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum price of the reservation unit', max_digits=10, verbose_name='Highest price'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='lowest_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum price of the reservation unit', max_digits=10, verbose_name='Lowest price'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The current list price for reservation units with a fixed price', max_digits=10, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='price_unit',
            field=models.CharField(choices=[('per_15_mins', 'per 15 minutes'), ('per_30_mins', 'per 30 minutes'), ('per_hour', 'per hour'), ('per_half_day', 'per half a day'), ('per_day', 'per day'), ('per_week', 'per week'), ('fixed', 'fixed')], default='per_hour', help_text='Unit of the price', max_length=20, verbose_name='Price unit'),
        ),
    ]
