# Generated by Django 3.1.13 on 2021-11-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0029_terms_of_use_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='highest_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Highest price'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='lowest_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Lowest price'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='price_unit',
            field=models.CharField(choices=[('per_hour', 'per hour'), ('per_day', 'per day'), ('per_week', 'per week'), ('per_piece', 'per piece')], default='per_hour', max_length=20, verbose_name='Price unit'),
        ),
    ]
