# Generated by Django 3.1.13 on 2021-12-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0030_reservation_unit_price_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='additional_instructions',
            field=models.TextField(blank=True, default='', verbose_name='Additional instructions'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='additional_instructions_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Additional instructions'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='additional_instructions_fi',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Additional instructions'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='additional_instructions_sv',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Additional instructions'),
        ),
    ]
