# Generated by Django 3.1.13 on 2021-12-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0033_reservationunit_remove_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationunit',
            name='reservation_start_interval',
            field=models.CharField(choices=[('interval_15_mins', '15 minutes'), ('interval_30_mins', '30 minutes'), ('interval_60_mins', '60 minutes'), ('interval_90_mins', '90 minutes')], default='interval_15_mins', help_text='Determines the interval for the start time of the reservation. For example an interval of 15 minutes means a reservation can begin at minutes 15, 30, 60, or 90. Possible values are interval_15_mins, interval_30_mins, interval_60_mins, interval_90_mins.', max_length=20, verbose_name='Reservation start interval'),
        ),
    ]
