# Generated by Django 3.1.13 on 2021-12-10 13:40

from django.db import migrations
from django.db.models import OuterRef


def update_buffer_time_before_and_after(apps, schema_editor):
    ReservationUnit = apps.get_model("reservation_units", "ReservationUnit")
    ReservationUnit.objects.update(
        buffer_time_after=OuterRef("buffer_time_between_reservations"),
        buffer_time_before=OuterRef("buffer_time_between_reservations"),
    )


def update_buffer_time_between_reservations(apps, schema_editor):
    ReservationUnit = apps.get_model("reservation_units", "ReservationUnit")
    ReservationUnit.objects.update(
        buffer_time_between_reservations=OuterRef("buffer_time_before"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("reservation_units", "0035_reservation_unit_buffer_time_before_and_after"),
    ]

    operations = [
        migrations.RunPython(
            update_buffer_time_before_and_after, update_buffer_time_between_reservations
        )
    ]
