# Generated by Django 3.1.13 on 2021-12-13 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0036_migrate_buffer_time_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationunit',
            name='buffer_time_between_reservations',
        ),
    ]
