# Generated by Django 3.1.13 on 2021-12-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0037_remove_reservationunit_buffer_time_between_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='publish_begins',
            field=models.DateTimeField(blank=True, help_text='Time after this reservation unit should be publicly visible in UI.', null=True),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='publish_ends',
            field=models.DateTimeField(blank=True, help_text='Time after this reservation unit should not be publicly visible in UI.', null=True),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='reservation_begins',
            field=models.DateTimeField(blank=True, help_text='Time when making reservations become possible for this reservation unit.', null=True),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='reservation_ends',
            field=models.DateTimeField(blank=True, help_text='Time when making reservations become not possible for this reservation unit', null=True),
        ),
    ]
