# Generated by Django 3.1.14 on 2021-12-15 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_reservationmetadata'),
        ('reservation_units', '0040_reservationunit_tax_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='metadata_set',
            field=models.ForeignKey(blank=True, help_text='Reservation metadata set that defines the set of supported and required form fields for this reservation unit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_units', to='reservations.reservationmetadataset', verbose_name='Reservation metadata set'),
        ),
    ]
