# Generated by Django 3.1.13 on 2021-12-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_reservationmetadata'),
        ('reservation_units', '0041_reservationunit_metadata_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='reservation_purposes',
            field=models.ManyToManyField(blank=True, related_name='reservation_units', to='reservations.ReservationPurpose', verbose_name='ReservationPurposes'),
        ),
    ]
