# Generated by Django 3.1.14 on 2021-12-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0042_reservationunit_reservation_purposes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='max_reservations_per_user',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum number of active reservations per user'),
        ),
    ]
