# Generated by Django 3.1.13 on 2022-01-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0044_reservationunit_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='require_reservation_handling',
            field=models.BooleanField(blank=True, default=False, help_text="Does reservations of this reservation unit need to be handled before they're confirmed.", verbose_name='Does the reservations of this require a handling'),
        ),
    ]
