# Generated by Django 3.2.12 on 2022-02-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0045_reservationunit_require_reservation_handling'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='authentication',
            field=models.CharField(choices=[('weak', 'Weak'), ('strong', 'Strong')], default='weak', help_text='Authentication required for reserving this reservation unit.', max_length=20, verbose_name='Authentication'),
        ),
    ]
