# Generated by Django 3.2.12 on 2022-02-09 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0046_reservationunit_authentication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationunit',
            name='contact_information_en',
        ),
        migrations.RemoveField(
            model_name='reservationunit',
            name='contact_information_fi',
        ),
        migrations.RemoveField(
            model_name='reservationunit',
            name='contact_information_sv',
        ),
    ]
