# Generated by Django 3.2.12 on 2022-05-18 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0049_reservationunit_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationunit',
            options={'ordering': ('id',)},
        ),
    ]
