# Generated by Django 3.2.12 on 2022-05-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0052_reservationunittype_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='min_persons',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum number of persons'),
        ),
    ]
