# Generated by Django 3.2.13 on 2022-05-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0053_reservationunit_min_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='reservation_kind',
            field=models.CharField(choices=[('DIRECT', 'Direct'), ('SEASON', 'Season'), ('DIRECT_AND_SEASON', 'Direct and season')], default='DIRECT_AND_SEASON', help_text='What kind of reservations are to be booked with this reservation unit.', max_length=20, verbose_name='Reservation kind '),
        ),
    ]
