# Generated by Django 3.2.13 on 2022-05-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0055_reservationunit_can_apply_free_of_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='reservations_max_days_before',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum number of days before reservations can be made'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='reservations_min_days_before',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum days before reservations can be made'),
        ),
    ]
