# Generated by Django 3.2.13 on 2022-05-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0056_reservationunit_min_max_days_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationunit',
            name='reservation_kind',
            field=models.CharField(choices=[('direct', 'Direct'), ('season', 'Season'), ('direct_and_season', 'Direct and season')], default='direct_and_season', help_text='What kind of reservations are to be booked with this reservation unit.', max_length=20, verbose_name='Reservation kind '),
        ),
    ]
