# Generated by Django 3.2.13 on 2022-05-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0057_alter_reservationunit_reservation_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='allow_reservations_without_opening_hours',
            field=models.BooleanField(default=False, help_text='Is it possible to reserve this reservation unit when opening hours are not defined.', verbose_name='Allow reservations without opening hours'),
        ),
    ]
