# Generated by Django 3.2.13 on 2022-06-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0058_reservationunit_allow_reservations_without_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Is reservation unit archived.', verbose_name='Is reservation unit archived'),
        ),
    ]
