# Generated by Django 3.2.13 on 2022-06-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0060_reservationunit_pricing_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='pricing_type',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('free', 'Free')], help_text='What kind of pricing types are to available with this reservation unit.', max_length=20, null=True, verbose_name='Pricing type'),
        ),
    ]
