# Generated by Django 3.2.13 on 2022-06-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0061_reservationunit_pricing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationunit',
            name='pricing_type',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('free', 'Free')], help_text='What kind of pricing types are available with this reservation unit.', max_length=20, null=True, verbose_name='Pricing type'),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='reservation_kind',
            field=models.CharField(choices=[('direct', 'Direct'), ('season', 'Season'), ('direct_and_season', 'Direct And Season')], default='direct_and_season', help_text='What kind of reservations are to be booked with this reservation unit.', max_length=20, verbose_name='Reservation kind '),
        ),
    ]
