# Generated by Django 3.2.13 on 2022-07-01 12:33

from django.db import migrations


def lower_reservation_kind_values(apps, schema_editor):
    ReservationUnit = apps.get_model("reservation_units", "ReservationUnit")

    for res_unit in ReservationUnit.objects.all():
        res_unit.reservation_kind = res_unit.reservation_kind.lower()
        res_unit.save()


class Migration(migrations.Migration):
    dependencies = [
        (
            "reservation_units",
            "0062_reservationunit_pricing_type_and_kind_choices_changes",
        ),
    ]

    operations = [
        migrations.RunPython(
            lower_reservation_kind_values, reverse_code=migrations.RunPython.noop
        ),
    ]
