# Generated by Django 3.2.13 on 2022-08-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0063_lower_reservation_kind_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('invoice', 'Invoice'), ('on_site', 'On Site')], help_text='When pricing type is paid, what kind of payment types are available with this reservation unit.', max_length=20, null=True, verbose_name='Payment type'),
        ),
    ]
