# Generated by Django 3.2.13 on 2022-08-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0064_reservationunit_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_fi', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_sv', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='qualifiers',
            field=models.ManyToManyField(blank=True, related_name='reservation_units', to='reservation_units.Qualifier', verbose_name='Qualifiers'),
        ),
    ]
