# Generated by Django 3.2.13 on 2022-08-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0065_reservation_unit_qualifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationunit',
            name='additional_instructions',
        ),
        migrations.RemoveField(
            model_name='reservationunit',
            name='additional_instructions_en',
        ),
        migrations.RemoveField(
            model_name='reservationunit',
            name='additional_instructions_fi',
        ),
        migrations.RemoveField(
            model_name='reservationunit',
            name='additional_instructions_sv',
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='reservation_confirmed_instructions',
            field=models.TextField(blank=True, default='', verbose_name='Additional instructions for confirmed reservation'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='reservation_confirmed_instructions_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Additional instructions for confirmed reservation'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='reservation_confirmed_instructions_fi',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Additional instructions for confirmed reservation'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='reservation_confirmed_instructions_sv',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Additional instructions for confirmed reservation'),
        ),
    ]
