# Generated by Django 3.2.13 on 2022-08-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0066_rename_reservation_unit_additional_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='reservation_cancelled_instructions',
            field=models.TextField(blank=True, default='', verbose_name='Additional instructions for cancelled reservations'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='reservation_cancelled_instructions_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Additional instructions for cancelled reservations'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='reservation_cancelled_instructions_fi',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Additional instructions for cancelled reservations'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='reservation_cancelled_instructions_sv',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Additional instructions for cancelled reservations'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='reservation_pending_instructions',
            field=models.TextField(blank=True, default='', verbose_name='Additional instructions for pending reservation'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='reservation_pending_instructions_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Additional instructions for pending reservation'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='reservation_pending_instructions_fi',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Additional instructions for pending reservation'),
        ),
        migrations.AddField(
            model_name='reservationunit',
            name='reservation_pending_instructions_sv',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Additional instructions for pending reservation'),
        ),
    ]
