# Generated by Django 3.2.15 on 2022-09-06 13:04

from django.db import migrations
from django.db.models import F


def update_ranks(apps, schema_editor):
    ReservationUnit = apps.get_model("reservation_units", "ReservationUnit")

    ReservationUnit.objects.update(rank=F("pk"))

class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0067_reservation_unit_instructions'),
    ]

    operations = [
        migrations.RunPython(update_ranks, migrations.RunPython.noop),
    ]
