# Generated by Django 3.2.15 on 2022-09-07 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0069_many_to_many_payment_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationunit',
            name='payment_type',
        ),
    ]
