# Generated by Django 3.2.15 on 2022-09-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0070_remove_reservationunit_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationunit',
            name='reservation_purposes',
        ),
    ]
