# Generated by Django 3.2.15 on 2022-09-23 03:14

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0071_remove_reservationunit_reservation_purposes'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to='reservation_unit_purpose_images'),
        ),
    ]
