# Generated by Django 3.2.15 on 2022-09-22 06:15

from django.db import migrations, models
from django.db.models import F

def update_ranks(apps, schema_editor):
    Purpose = apps.get_model("reservation_units", "Purpose")
    Purpose.objects.update(rank=F("pk"))

class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0072_add_runit_purpose_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purpose',
            options={'ordering': ['rank']},
        ),
        migrations.AddField(
            model_name='purpose',
            name='rank',
            field=models.PositiveIntegerField(blank=True, help_text='Order number to be used in api sorting.', null=True, verbose_name='Order number'),
        ),
        migrations.RunPython(update_ranks, migrations.RunPython.noop),
    ]
