# Generated by Django 3.2.15 on 2022-09-29 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('reservation_units', '0075_separate_pricing_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunit',
            name='payment_merchant',
            field=models.ForeignKey(help_text='Merchant used for payments', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_units', to='merchants.paymentmerchant', verbose_name='Payment merchant'),
        ),
    ]
