# Generated by Django 3.2.15 on 2022-10-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0078_reservationunit_payment_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationunit',
            options={'ordering': ('rank', 'id')},
        ),
    ]
