# Generated by Django 3.2.16 on 2022-10-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0079_alter_reservationunit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunitpricing',
            name='highest_price_net',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Maximum price of the reservation unit excluding VAT', max_digits=20, verbose_name='Highest net price'),
        ),
        migrations.AddField(
            model_name='reservationunitpricing',
            name='lowest_price_net',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Minimum price of the reservation unit excluding VAT', max_digits=20, verbose_name='Lowest net price'),
        ),
        migrations.AlterField(
            model_name='reservationunitpricing',
            name='highest_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum price of the reservation unit including VAT', max_digits=10, verbose_name='Highest price'),
        ),
        migrations.AlterField(
            model_name='reservationunitpricing',
            name='lowest_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum price of the reservation unit including VAT', max_digits=10, verbose_name='Lowest price'),
        ),
    ]
