# Generated by Django 3.2.16 on 2022-11-04 07:52
from decimal import Decimal

from django.db.models import F
from django.db import migrations


def update_net_prices(apps, schema_editor):
    ReservationUnitPricing = apps.get_model(
        "reservation_units", "ReservationUnitPricing"
    )

    for price in ReservationUnitPricing.objects.all():
        price.highest_price_net = price.highest_price / (
            1 + (price.tax_percentage.value / Decimal("100"))
        )

        price.lowest_price_net = price.lowest_price / (
            1 + (price.tax_percentage.value / Decimal("100"))
        )

        price.save()


class Migration(migrations.Migration):

    dependencies = [
        ("reservation_units", "0080_reservationunit_net_prices"),
    ]

    operations = [
        migrations.RunPython(update_net_prices, migrations.RunPython.noop),
    ]
