# Generated by Django 3.2.16 on 2022-12-14 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0082_reservationunit_payment_accounting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationunit',
            name='highest_price',
        ),
        migrations.RemoveField(
            model_name='reservationunit',
            name='lowest_price',
        ),
        migrations.RemoveField(
            model_name='reservationunit',
            name='price_unit',
        ),
        migrations.RemoveField(
            model_name='reservationunit',
            name='pricing_type',
        ),
        migrations.RemoveField(
            model_name='reservationunit',
            name='tax_percentage',
        ),
    ]
