# Generated by Django 3.2.18 on 2023-03-31 11:01

from django.db import migrations, models
from easy_thumbnails.exceptions import InvalidImageFormatError


def update_urls(apps, schema_editor):
    ReservationUnitImage = apps.get_model("reservation_units", "ReservationUnitImage")
    for image in ReservationUnitImage.objects.all():
        try:
            image.large_url = image.image["large"].url
            image.medium_url = image.image["medium"].url
            image.small_url = image.image["small"].url
            image.save(update_urls=False)
        except InvalidImageFormatError:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0083_remove_old_pricing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationunitimage',
            name='large_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reservationunitimage',
            name='medium_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reservationunitimage',
            name='small_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(update_urls, reverse_code=migrations.RunPython.noop),
    ]
