# Generated by Django 4.2.1 on 2023-06-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation_units", "0084_reservation_unit_image_url_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationunit",
            name="surface_area",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Surface area"
            ),
        ),
    ]
