# Generated by Django 4.2.6 on 2023-10-24 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opening_hours", "0001_initial"),
        ("reservation_units", "0085_surface_area_to_integer"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationunit",
            name="origin_hauki_resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservation_units",
                to="opening_hours.OriginHaukiResource",
            ),
        ),
    ]
