# Generated by Django 4.2.6 on 2023-10-24 20:38

from django.db import migrations


def migrate_hauki_resource_id(apps, schema_editor):
    ReservationUnit = apps.get_model("reservation_units", "ReservationUnit")
    OriginHaukiResource = apps.get_model("opening_hours", "OriginHaukiResource")

    reservation_units = ReservationUnit.objects.exclude(hauki_resource_id="").exclude(hauki_resource_id__isnull=True)
    for reservation_unit in reservation_units:
        origin_hauki_resource, _ = OriginHaukiResource.objects.get_or_create(id=reservation_unit.hauki_resource_id)
        reservation_unit.origin_hauki_resource = origin_hauki_resource
        reservation_unit.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0086_add_origin_hauki_resource_field'),
        ('opening_hours', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_hauki_resource_id, reverse_code=migrations.RunPython.noop),
    ]
