# Generated by Django 4.2.6 on 2023-11-03 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservation_units", "0088_depracate_hauki_resource_id_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="daypart",
            name="day",
        ),
        migrations.RemoveField(
            model_name="period",
            name="reservation_unit",
        ),
        migrations.DeleteModel(
            name="Day",
        ),
        migrations.DeleteModel(
            name="DayPart",
        ),
        migrations.DeleteModel(
            name="Period",
        ),
    ]
