# Generated by Django 4.2.6 on 2023-11-23 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservation_units", "0089_delete_unused_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservationunit",
            options={"base_manager_name": "objects", "ordering": ("rank", "id")},
        ),
        migrations.AlterModelOptions(
            name="reservationunitpricing",
            options={"base_manager_name": "objects"},
        ),
    ]
