# Generated by Django 4.2.7 on 2024-01-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation_units", "0090_add_base_manager_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationunit",
            name="reservation_block_whole_day",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
