# Generated by Django 4.2.9 on 2024-01-23 07:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservation_units", "0091_reservationunit_reservation_block_whole_day"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="equipmentcategory",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="introduction",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="keyword",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="keywordcategory",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="keywordgroup",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="purpose",
            options={"base_manager_name": "objects", "ordering": ["rank"]},
        ),
        migrations.AlterModelOptions(
            name="qualifier",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="reservationunit",
            options={"base_manager_name": "objects", "ordering": ["rank", "id"]},
        ),
        migrations.AlterModelOptions(
            name="reservationunitcancellationrule",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="reservationunitimage",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="reservationunitpaymenttype",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="reservationunittype",
            options={"base_manager_name": "objects", "ordering": ["rank"]},
        ),
        migrations.AlterModelOptions(
            name="taxpercentage",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelTable(
            name="equipment",
            table="equipment",
        ),
        migrations.AlterModelTable(
            name="equipmentcategory",
            table="equipment_category",
        ),
        migrations.AlterModelTable(
            name="introduction",
            table="introduction",
        ),
        migrations.AlterModelTable(
            name="keyword",
            table="keyword",
        ),
        migrations.AlterModelTable(
            name="keywordcategory",
            table="keyword_category",
        ),
        migrations.AlterModelTable(
            name="keywordgroup",
            table="keyword_group",
        ),
        migrations.AlterModelTable(
            name="purpose",
            table="purpose",
        ),
        migrations.AlterModelTable(
            name="qualifier",
            table="qualifier",
        ),
        migrations.AlterModelTable(
            name="reservationunit",
            table="reservation_unit",
        ),
        migrations.AlterModelTable(
            name="reservationunitcancellationrule",
            table="reservation_unit_cancellation_rule",
        ),
        migrations.AlterModelTable(
            name="reservationunitimage",
            table="reservation_unit_image",
        ),
        migrations.AlterModelTable(
            name="reservationunitpaymenttype",
            table="reservation_unit_payment_type",
        ),
        migrations.AlterModelTable(
            name="reservationunitpricing",
            table="reservation_unit_pricing",
        ),
        migrations.AlterModelTable(
            name="reservationunittype",
            table="reservation_unit_type",
        ),
        migrations.AlterModelTable(
            name="taxpercentage",
            table="tax_percentage",
        ),
    ]
