# Generated by Django 4.2.9 on 2024-01-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation_units", "0095_alter_reservationunit_buffer_time_after_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservationunitpricing",
            name="highest_price_net",
        ),
        migrations.RemoveField(
            model_name="reservationunitpricing",
            name="lowest_price_net",
        ),
        migrations.AddConstraint(
            model_name="reservationunitpricing",
            constraint=models.CheckConstraint(
                check=models.Q(("lowest_price__lte", models.F("highest_price"))),
                name="lower_price_greater_than_highest_price",
                violation_error_message="Lowest price can not be greater than highest price.",
            ),
        ),
    ]
