# Generated by Django 4.2.10 on 2024-03-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation_units", "0096_remove_pricing_net_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationunit",
            name="reservation_start_interval",
            field=models.CharField(
                choices=[
                    ("interval_15_mins", "15 minutes"),
                    ("interval_30_mins", "30 minutes"),
                    ("interval_60_mins", "60 minutes"),
                    ("interval_90_mins", "90 minutes"),
                    ("interval_120_mins", "2 hours"),
                    ("interval_180_mins", "3 hours"),
                    ("interval_240_mins", "4 hours"),
                    ("interval_300_mins", "5 hours"),
                    ("interval_360_mins", "6 hours"),
                    ("interval_420_mins", "7 hours"),
                ],
                default="interval_15_mins",
                help_text="Determines the interval for the start time of the reservation. For example an interval of 15 minutes means a reservation can begin at minutes 15, 30, 60, or 90. Possible values are interval_15_mins, interval_30_mins, interval_60_mins, interval_90_mins, interval_120_mins, interval_180_mins, interval_240_mins, interval_300_mins, interval_360_mins, interval_420_mins.",
                max_length=20,
                verbose_name="Reservation start interval",
            ),
        ),
    ]
