# Generated by Django 5.0.4 on 2024-05-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0100_alter_reservationunitimage_image_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purpose',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
