# Generated by Django 5.0.6 on 2024-05-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0102_create_reservation_unit_hierarchy_materialized_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationunit',
            name='publish_begins',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='publish_ends',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='reservation_begins',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='reservation_ends',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='reservation_kind',
            field=models.CharField(choices=[('direct', 'Direct'), ('season', 'Season'), ('direct_and_season', 'Direct And Season')], db_index=True, default='direct_and_season', max_length=20),
        ),
    ]
