# Generated by Django 5.0.7 on 2024-07-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation_units", "0103_alter_reservationunit_publish_begins_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationunit",
            name="reservation_kind",
            field=models.CharField(
                choices=[("direct", "Direct"), ("season", "Season"), ("direct_and_season", "Direct and season")],
                db_index=True,
                default="direct_and_season",
                max_length=20,
            ),
        ),
    ]
