# Generated by Django 5.1.1 on 2024-09-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation_units", "0104_alter_reservationunit_reservation_kind"),
        ("tilavarauspalvelu", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="reservationunit",
                    name="services",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="reservation_units",
                        to="tilavarauspalvelu.service",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
