# Generated by Django 5.1 on 2024-09-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_units', '0105_refactor_pricing_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationunitpricing',
            name='pricing_type',
        ),
    ]
