# Generated by Django 5.1.1 on 2024-09-18 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation_units", "0105_alter_reservationunit_services"),
        ("tilavarauspalvelu", "0004_migrate_terms_of_use"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="reservationunit",
                    name="cancellation_terms",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancellation_terms_reservation_unit",
                        to="tilavarauspalvelu.termsofuse",
                    ),
                ),
                migrations.AlterField(
                    model_name="reservationunit",
                    name="payment_terms",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_terms_reservation_unit",
                        to="tilavarauspalvelu.termsofuse",
                    ),
                ),
                migrations.AlterField(
                    model_name="reservationunit",
                    name="pricing_terms",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pricing_terms_reservation_unit",
                        to="tilavarauspalvelu.termsofuse",
                    ),
                ),
                migrations.AlterField(
                    model_name="reservationunit",
                    name="service_specific_terms",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_specific_terms_reservation_unit",
                        to="tilavarauspalvelu.termsofuse",
                    ),
                ),
            ],
            # We just moved the model, so no need to modify foreign keys
            database_operations=[],
        ),
    ]
