# Generated by Django 5.1.1 on 2024-09-18 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation_units", "0106_alter_reservationunit_cancellation_terms_and_more"),
        ("tilavarauspalvelu", "0005_migrate_merchants"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="reservationunit",
                    name="payment_accounting",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservation_units",
                        to="tilavarauspalvelu.paymentaccounting",
                    ),
                ),
                migrations.AlterField(
                    model_name="reservationunit",
                    name="payment_merchant",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservation_units",
                        to="tilavarauspalvelu.paymentmerchant",
                    ),
                ),
                migrations.AlterField(
                    model_name="reservationunit",
                    name="payment_product",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservation_units",
                        to="tilavarauspalvelu.paymentproduct",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
