# Generated by Django 5.1.1 on 2024-09-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation_units", "0107_alter_reservationunit_payment_accounting_and_more"),
        ("tilavarauspalvelu", "0006_migrate_resources"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="reservationunit",
                    name="resources",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="reservation_units",
                        to="tilavarauspalvelu.resource",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
