# Generated by Django 5.1.1 on 2024-09-19 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation_units", "0108_alter_reservationunit_resources"),
        ("tilavarauspalvelu", "0007_migrate_spaces"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="reservationunit",
                    name="spaces",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="reservation_units",
                        to="tilavarauspalvelu.space",
                    ),
                ),
                migrations.AlterField(
                    model_name="reservationunit",
                    name="unit",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tilavarauspalvelu.unit",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
