# Generated by Django 5.1.1 on 2024-09-19 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation_units", "0109_alter_reservationunit_spaces_and_more"),
        ("tilavarauspalvelu", "0010_migrate_opening_hours"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="reservationunit",
                    name="origin_hauki_resource",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservation_units",
                        to="tilavarauspalvelu.originhaukiresource",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
