# Generated by Django 5.1.1 on 2024-09-26 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation_units", "0110_alter_reservationunit_origin_hauki_resource"),
        ("tilavarauspalvelu", "0011_migrate_reservations"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="reservationunit",
                    name="metadata_set",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservation_units",
                        to="tilavarauspalvelu.reservationmetadataset",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
