# Generated by Django 3.1.7 on 2021-03-19 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0028_organisation_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, verbose_name='Start time')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End time')),
                ('completed', models.BooleanField(blank=True, default=False, verbose_name='Completed')),
                ('application_round', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.applicationround', verbose_name='Application round')),
                ('application_round_baskets', models.ManyToManyField(to='applications.ApplicationRoundBasket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
