# Build and deploy to the test environment after creating a tag with the given pattern.

resources:
  repositories:
    # Azure DevOps repository.
    - repository: tilavarauspalvelu-pipelines
      type: git
      # Azure DevOps project/repository.
      name: tilavarauspalvelu/tilavarauspalvelu-pipelines

trigger:
  # If another instance of this pipeline is running,
  # wait for it to complete and then run all other changes in a batch.
  batch: true
  tags:
    # Trigger when creating tags like v1.0.0, release-1.0.0, hotfix-1.0.0, v1.0.0-ui, v1.0.0-customer,
    # but not when creating tags like v1.0.0-staff, v1.0.0-core, etc.
    include:
      - "v*"
      - "release-*"
      - "hotfix-*"
    exclude:
      - "*-staff"
      - "*-core"
  paths:
    # Should use turborepo to calculate the real needed packages,
    # but currently this is not possible.
    include:
      - packages/common
      - apps/customer
    exclude:
      - README.md

# Don't use Azure pipelines for PRs.
pr: none

# By default, use self-hosted agents.
pool: Default

extends:
  # Filename for pipeline to extend from the Azure DevOps Repository.
  template: ui-build-release.yml@tilavarauspalvelu-pipelines
