# Generated by Django 5.1 on 2024-09-11 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0014_migrate_common"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailtemplate",
            name="content",
        ),
        migrations.RemoveField(
            model_name="emailtemplate",
            name="content_en",
        ),
        migrations.RemoveField(
            model_name="emailtemplate",
            name="content_fi",
        ),
        migrations.RemoveField(
            model_name="emailtemplate",
            name="content_sv",
        ),
        migrations.RemoveField(
            model_name="emailtemplate",
            name="html_content",
        ),
        migrations.RemoveField(
            model_name="emailtemplate",
            name="html_content_en",
        ),
        migrations.RemoveField(
            model_name="emailtemplate",
            name="html_content_fi",
        ),
        migrations.RemoveField(
            model_name="emailtemplate",
            name="html_content_sv",
        ),
    ]
