# Generated by Django 5.1.1 on 2024-09-23 15:42

from django.db import migrations


def update_email_types(apps, schema_editor):
    EmailTemplate = apps.get_model("tilavarauspalvelu", "EmailTemplate")

    EmailTemplate.objects.filter(type="handling_required_reservation").update(type="reservation_handling_required")
    EmailTemplate.objects.filter(type="access_code_for_reservation").delete()
    EmailTemplate.objects.filter(type="reservation_with_pin_confirmed").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0016_rename_email_types_part_1"),
    ]

    operations = [
        migrations.RunPython(update_email_types, migrations.RunPython.noop),
    ]
