# Generated by Django 5.1.2 on 2024-10-16 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0019_add_now_tt"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailTemplate",
        ),
    ]
