# Generated by Django 5.1.2 on 2024-10-18 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0023_user_sent_email_about_anonymization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="abilitygroup",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "ability group",
                "verbose_name_plural": "ability groups",
            },
        ),
        migrations.AlterModelOptions(
            name="address",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "address",
                "verbose_name_plural": "addresses",
            },
        ),
        migrations.AlterModelOptions(
            name="agegroup",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "age group",
                "verbose_name_plural": "age groups",
            },
        ),
        migrations.AlterModelOptions(
            name="allocatedtimeslot",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "allocated time slot",
                "verbose_name_plural": "allocated time slots",
            },
        ),
        migrations.AlterModelOptions(
            name="application",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "application",
                "verbose_name_plural": "applications",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationround",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "application round",
                "verbose_name_plural": "application rounds",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationroundtimeslot",
            options={
                "base_manager_name": "objects",
                "ordering": ["reservation_unit", "weekday"],
                "verbose_name": "application round time slot",
                "verbose_name_plural": "application round time slots",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationsection",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "application section",
                "verbose_name_plural": "application sections",
            },
        ),
        migrations.AlterModelOptions(
            name="bannernotification",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "banner notification",
                "verbose_name_plural": "banner notifications",
            },
        ),
        migrations.AlterModelOptions(
            name="building",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "building",
                "verbose_name_plural": "buildings",
            },
        ),
        migrations.AlterModelOptions(
            name="city",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "city",
                "verbose_name_plural": "cities",
            },
        ),
        migrations.AlterModelOptions(
            name="equipment",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "equipment",
                "verbose_name_plural": "equipments",
            },
        ),
        migrations.AlterModelOptions(
            name="equipmentcategory",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "equipment category",
                "verbose_name_plural": "equipment categories",
            },
        ),
        migrations.AlterModelOptions(
            name="generalrole",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "general role",
                "verbose_name_plural": "general roles",
            },
        ),
        migrations.AlterModelOptions(
            name="introduction",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "introduction",
                "verbose_name_plural": "introductions",
            },
        ),
        migrations.AlterModelOptions(
            name="keyword",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "keyword",
                "verbose_name_plural": "keywords",
            },
        ),
        migrations.AlterModelOptions(
            name="keywordcategory",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "keyword category",
                "verbose_name_plural": "keyword categories",
            },
        ),
        migrations.AlterModelOptions(
            name="keywordgroup",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "keyword group",
                "verbose_name_plural": "keyword groups",
            },
        ),
        migrations.AlterModelOptions(
            name="location",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "location",
                "verbose_name_plural": "locations",
            },
        ),
        migrations.AlterModelOptions(
            name="organisation",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "organisation",
                "verbose_name_plural": "organisations",
            },
        ),
        migrations.AlterModelOptions(
            name="originhaukiresource",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "origin hauki resource",
                "verbose_name_plural": "origin hauki resources",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentaccounting",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "payment accounting",
                "verbose_name_plural": "payment accountings",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentmerchant",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "payment merchant",
                "verbose_name_plural": "payment merchants",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentorder",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "payment order",
                "verbose_name_plural": "payment orders",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentproduct",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "payment product",
                "verbose_name_plural": "payment products",
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "person",
                "verbose_name_plural": "persons",
            },
        ),
        migrations.AlterModelOptions(
            name="personalinfoviewlog",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "personal info view log",
                "verbose_name_plural": "personal info view logs",
            },
        ),
        migrations.AlterModelOptions(
            name="purpose",
            options={
                "base_manager_name": "objects",
                "ordering": ["rank"],
                "verbose_name": "purpose",
                "verbose_name_plural": "purposes",
            },
        ),
        migrations.AlterModelOptions(
            name="qualifier",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "qualifier",
                "verbose_name_plural": "qualifiers",
            },
        ),
        migrations.AlterModelOptions(
            name="realestate",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "real estate",
                "verbose_name_plural": "real estates",
            },
        ),
        migrations.AlterModelOptions(
            name="recurringreservation",
            options={
                "base_manager_name": "objects",
                "ordering": ["begin_date", "begin_time", "reservation_unit"],
                "verbose_name": "recurring reservation",
                "verbose_name_plural": "recurring reservations",
            },
        ),
        migrations.AlterModelOptions(
            name="rejectedoccurrence",
            options={
                "base_manager_name": "objects",
                "ordering": ["begin_datetime", "end_datetime"],
                "verbose_name": "rejected occurrence",
                "verbose_name_plural": "rejected occurrences",
            },
        ),
        migrations.AlterModelOptions(
            name="requestlog",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "request log",
                "verbose_name_plural": "request logs",
            },
        ),
        migrations.AlterModelOptions(
            name="reservabletimespan",
            options={
                "base_manager_name": "objects",
                "ordering": ["resource", "start_datetime", "end_datetime"],
                "verbose_name": "request log",
                "verbose_name_plural": "request logs",
            },
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "base_manager_name": "objects",
                "ordering": ["begin"],
                "verbose_name": "reservation",
                "verbose_name_plural": "reservations",
            },
        ),
        migrations.AlterModelOptions(
            name="reservationcancelreason",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "reservation cancel reason",
                "verbose_name_plural": "reservation cancel reasons",
            },
        ),
        migrations.AlterModelOptions(
            name="reservationdenyreason",
            options={
                "base_manager_name": "objects",
                "ordering": ["rank"],
                "verbose_name": "reservation deny reason",
                "verbose_name_plural": "reservation deny reasons",
            },
        ),
        migrations.AlterModelOptions(
            name="reservationmetadatafield",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "reservation metadata field",
                "verbose_name_plural": "reservation metadata fields",
            },
        ),
        migrations.AlterModelOptions(
            name="reservationmetadataset",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "reservation metadata set",
                "verbose_name_plural": "reservation metadata sets",
            },
        ),
        migrations.AlterModelOptions(
            name="reservationpurpose",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "reservation purpose",
                "verbose_name_plural": "reservation purposes",
            },
        ),
        migrations.AlterModelOptions(
            name="reservationstatistic",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "reservation statistic",
                "verbose_name_plural": "reservation statistics",
            },
        ),
        migrations.AlterModelOptions(
            name="reservationstatisticsreservationunit",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "reservation statistics reservation unit",
                "verbose_name_plural": "reservation statistics reservation units",
            },
        ),
        migrations.AlterModelOptions(
            name="reservationunit",
            options={
                "base_manager_name": "objects",
                "ordering": ["rank", "id"],
                "verbose_name": "reservation unit",
                "verbose_name_plural": "reservation units",
            },
        ),
        migrations.AlterModelOptions(
            name="reservationunitcancellationrule",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "reservation unit cancellation rule",
                "verbose_name_plural": "reservation unit cancellation rules",
            },
        ),
        migrations.AlterModelOptions(
            name="reservationunitimage",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "reservation unit image",
                "verbose_name_plural": "reservation unit images",
            },
        ),
        migrations.AlterModelOptions(
            name="reservationunitoption",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "reservation unit option",
                "verbose_name_plural": "reservation unit options",
            },
        ),
        migrations.AlterModelOptions(
            name="reservationunitpaymenttype",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "reservation unit payment type",
                "verbose_name_plural": "reservation unit payment types",
            },
        ),
        migrations.AlterModelOptions(
            name="reservationunitpricing",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "reservation unit pricing",
                "verbose_name_plural": "reservation unit pricings",
            },
        ),
        migrations.AlterModelOptions(
            name="reservationunittype",
            options={
                "base_manager_name": "objects",
                "ordering": ["rank"],
                "verbose_name": "reservation unit type",
                "verbose_name_plural": "reservation unit types",
            },
        ),
        migrations.AlterModelOptions(
            name="resource",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "resource",
                "verbose_name_plural": "resources",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "service",
                "verbose_name_plural": "services",
            },
        ),
        migrations.AlterModelOptions(
            name="servicesector",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "service sector",
                "verbose_name_plural": "service sectors",
            },
        ),
        migrations.AlterModelOptions(
            name="space",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "space",
                "verbose_name_plural": "spaces",
            },
        ),
        migrations.AlterModelOptions(
            name="suitabletimerange",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "suitable time range",
                "verbose_name_plural": "suitable time ranges",
            },
        ),
        migrations.AlterModelOptions(
            name="taxpercentage",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "tax percentage",
                "verbose_name_plural": "tax percentages",
            },
        ),
        migrations.AlterModelOptions(
            name="unit",
            options={
                "base_manager_name": "objects",
                "ordering": ["rank"],
                "verbose_name": "unit",
                "verbose_name_plural": "units",
            },
        ),
        migrations.AlterModelOptions(
            name="unitgroup",
            options={
                "base_manager_name": "objects",
                "ordering": ["name"],
                "verbose_name": "unit group",
                "verbose_name_plural": "unit groups",
            },
        ),
        migrations.AlterModelOptions(
            name="unitrole",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "unit role",
                "verbose_name_plural": "unit roles",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "base_manager_name": "objects",
                "ordering": ["pk"],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.AlterField(
            model_name="generalrole",
            name="assigner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_general_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="introduction",
            name="reservation_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="introductions",
                to="tilavarauspalvelu.reservationunit",
            ),
        ),
        migrations.AlterField(
            model_name="introduction",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="introductions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recurringreservation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurring_reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="age_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="tilavarauspalvelu.agegroup",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="home_city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="tilavarauspalvelu.city",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="purpose",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="tilavarauspalvelu.reservationpurpose",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_unit",
            field=models.ManyToManyField(
                related_name="reservations",
                to="tilavarauspalvelu.reservationunit",
            ),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="ability_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservation_statistics",
                to="tilavarauspalvelu.abilitygroup",
            ),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="primary_reservation_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservation_statistics",
                to="tilavarauspalvelu.reservationunit",
            ),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="reservation",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservation_statistic",
                to="tilavarauspalvelu.reservation",
            ),
        ),
        migrations.AlterField(
            model_name="reservationstatisticsreservationunit",
            name="reservation_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservation_stats_reservation_units",
                to="tilavarauspalvelu.reservationunit",
            ),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="cancellation_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservation_units",
                to="tilavarauspalvelu.reservationunitcancellationrule",
            ),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="cancellation_terms",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancellation_terms_reservation_units",
                to="tilavarauspalvelu.termsofuse",
            ),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="equipments",
            field=models.ManyToManyField(
                blank=True,
                related_name="reservation_units",
                to="tilavarauspalvelu.equipment",
            ),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="payment_terms",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_terms_reservation_units",
                to="tilavarauspalvelu.termsofuse",
            ),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="payment_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="reservation_units",
                to="tilavarauspalvelu.reservationunitpaymenttype",
            ),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="pricing_terms",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pricing_terms_reservation_units",
                to="tilavarauspalvelu.termsofuse",
            ),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="service_specific_terms",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_specific_terms_reservation_units",
                to="tilavarauspalvelu.termsofuse",
            ),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservation_units",
                to="tilavarauspalvelu.unit",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resources",
                to="tilavarauspalvelu.space",
            ),
        ),
        migrations.AlterField(
            model_name="unitrole",
            name="assigner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_unit_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                blank=True, choices=[("fi", "Finnish"), ("en", "English"), ("sv", "Swedish")], max_length=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="reservation_notification",
            field=models.CharField(
                choices=[("all", "All"), ("only_handling_required", "Only Handling Required"), ("none", "None")],
                default="only_handling_required",
                max_length=32,
            ),
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="reservation_unit",
            new_name="reservation_units",
        ),
    ]
