# Generated by Django 5.1.1 on 2024-09-26 14:42

from django.db import migrations
from django.db.models.functions import Now


def migrate_rounds(apps, schema_editor):
    Application = apps.get_model("tilavarauspalvelu", "Application")

    # Applications in `IN_ALLOCATION`, `HANDLED` and `RESULTS_SENT` application rounds
    applications = Application.objects.select_related("application_round").filter(
        application_round__application_period_end__lte=Now(),
    )

    # Can't use qs.update() because it can't use data from a related model
    for application in applications:
        application.in_allocation_notification_sent_date = application.application_round.application_period_end

    Application.objects.bulk_update(applications, ["in_allocation_notification_sent_date"])

    # Applications in `RESULTS_SENT` application rounds
    applications = Application.objects.select_related("application_round").exclude(
        application_round__sent_date=None,
    )

    # Can't use qs.update() because it can't use data from a related model
    for application in applications:
        application.results_ready_notification_sent_date = application.application_round.sent_date

    Application.objects.bulk_update(applications, ["results_ready_notification_sent_date"])


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0028_fix_rank_fields"),
    ]

    operations = [
        migrations.RunPython(migrate_rounds, migrations.RunPython.noop),
    ]
