# Generated by Django 5.1.3 on 2024-11-27 09:23
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0031_alter_user_preferred_language"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ServiceSector",
        ),
    ]
