# Generated by Django 5.1.3 on 2024-11-27 11:44
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0033_delete_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="real_estate",
        ),
        migrations.RemoveField(
            model_name="location",
            name="real_estate",
        ),
        migrations.DeleteModel(
            name="RealEstate",
        ),
    ]
