# Generated by Django 5.1.3 on 2024-11-27 11:55
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0034_delete_real_estate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="building",
        ),
        migrations.RemoveField(
            model_name="space",
            name="building",
        ),
        migrations.DeleteModel(
            name="Building",
        ),
    ]
