# Generated by Django 5.1.3 on 2024-11-27 12:32
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0038_remove_resource_buffer_time_after_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservationunitcancellationrule",
            name="needs_handling",
        ),
    ]
