# Generated by Django 5.1.3 on 2024-11-27 12:35
from __future__ import annotations

from django.db import migrations, models


def migrate_func(apps, schema_editor) -> None:
    model = apps.get_model("tilavarauspalvelu", "ReservationStatisticsReservationUnit")
    model.objects.filter(unit_tprek_id=None).update(unit_tprek_id="")


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0039_remove_reservationunitcancellationrule_needs_handling"),
    ]

    operations = [
        migrations.RunPython(migrate_func, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="reservationstatisticsreservationunit",
            name="unit_tprek_id",
            field=models.CharField(default="", max_length=255),
        ),
    ]
