# Generated by Django 5.1.3 on 2024-11-28 07:23
from __future__ import annotations

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0041_rename_recurring_reservation_uuid_to_ext_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="ext_uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
