# Generated by Django 5.1.3 on 2024-11-28 07:31
from __future__ import annotations

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0043_populate_uuid_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="ext_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
