# Generated by Django 5.1.3 on 2024-11-28 13:11
from __future__ import annotations

from django.db import migrations

import tilavarauspalvelu.models.reservation_unit.queryset


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0045_reservationstatistic_reservation_uuid"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="reservationunit",
            managers=[
                ("objects", tilavarauspalvelu.models.reservation_unit.queryset.ReservationUnitManager()),
            ],
        ),
    ]
