# Generated by Django 5.1.3 on 2024-11-29 09:32
from __future__ import annotations

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0047_add_reservation_unit_search_vectors"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationunit",
            name="search_terms",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
