# Generated by Django 5.1.3 on 2024-11-28 11:58
from __future__ import annotations

from django.db import migrations


def gen_vectors(apps, schema_editor) -> None:
    ReservationUnit = apps.get_model("tilavarauspalvelu", "ReservationUnit")
    ReservationUnit.objects.update_search_vectors()


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0048_reservationunit_search_terms"),
    ]

    operations = [migrations.RunPython(gen_vectors, migrations.RunPython.noop)]
