# Generated by Django 5.1.3 on 2024-12-10 07:58
from __future__ import annotations

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor) -> None:
    """See. https://docs.djangoproject.com/en/5.1/howto/writing-migrations/#migrations-that-add-unique-fields"""
    ApplicationSection = apps.get_model("tilavarauspalvelu", "ApplicationSection")

    # Should be fine, since there aren't that many application sections yet (~1000 in production)
    rows = list(ApplicationSection.objects.all())
    for row in rows:
        row.ext_uuid = uuid.uuid4()
    ApplicationSection.objects.bulk_update(rows, ["ext_uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0051_add_application_section_ext_uuid"),
    ]

    operations = [migrations.RunPython(gen_uuid, migrations.RunPython.noop)]
