# Generated by Django 5.1.3 on 2024-12-16 11:52
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0053_unique_application_section_ext_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="BugReport",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("Pull Request", "Pull Request"),
                            ("Manual Testing", "Manual Testing"),
                            ("Production", "Production"),
                        ],
                        max_length=255,
                    ),
                ),
                ("was_real_issue", models.BooleanField(default=True)),
                (
                    "found_by",
                    models.CharField(
                        choices=[
                            ("Eemeli", "Eemeli"),
                            ("Jesse", "Jesse"),
                            ("Joonatan", "Joonatan"),
                            ("Jusa", "Jusa"),
                            ("Matti", "Matti"),
                            ("Matu", "Matu"),
                            ("Milla", "Milla"),
                            ("Oiva", "Oiva"),
                            ("Risto", "Risto"),
                            ("Other", "Someone else, who?"),
                        ],
                        max_length=255,
                    ),
                ),
                ("found_at", models.DateTimeField()),
                (
                    "fixed_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Eemeli", "Eemeli"),
                            ("Jesse", "Jesse"),
                            ("Joonatan", "Joonatan"),
                            ("Jusa", "Jusa"),
                            ("Matti", "Matti"),
                            ("Matu", "Matu"),
                            ("Milla", "Milla"),
                            ("Oiva", "Oiva"),
                            ("Risto", "Risto"),
                            ("Other", "Someone else, who?"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("fixed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "bug report",
                "verbose_name_plural": "bug reports",
                "db_table": "bug_report",
                "ordering": ["pk"],
                "base_manager_name": "objects",
                "constraints": [
                    models.CheckConstraint(
                        check=models.Q(
                            models.Q(("fixed_by__isnull", True), ("fixed_at__isnull", True)),
                            models.Q(("fixed_by__isnull", False), ("fixed_at__isnull", False)),
                            _connector="OR",
                        ),
                        name="must_set_both_fixed_by_and_fixed_at_together",
                        violation_error_message="Bug report fixed by and fixed at must be set together.",
                    )
                ],
            },
        ),
    ]
