# Generated by Django 5.1.3 on 2024-12-10 16:00
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0056_bugreport_fix_strategy_bugreport_github_pr_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationunit",
            name="require_adult_reservee",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
