# Generated by Django 5.1.4 on 2025-02-17 12:13
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0066_remove_reservationunit_require_introduction"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationUnitAccessType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("ACCESS_CODE", "access code"),
                            ("OPENED_BY_STAFF", "opened by staff"),
                            ("PHYSICAL_KEY", "physical key"),
                            ("UNRESTRICTED", "unrestricted"),
                        ],
                        default="UNRESTRICTED",
                        max_length=255,
                    ),
                ),
                ("begin_date", models.DateField()),
                (
                    "reservation_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_types",
                        to="tilavarauspalvelu.reservationunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "reservation unit access type",
                "verbose_name_plural": "reservation unit access types",
                "db_table": "reservation_unit_access_type",
                "ordering": ["reservation_unit", "begin_date"],
                "base_manager_name": "objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reservation_unit", "begin_date"),
                        name="single_access_type_per_day_per_reservation_unit",
                        violation_error_message="Access type already exists for this reservation unit and date",
                    )
                ],
            },
        ),
    ]
