# Generated by Django 5.1.6 on 2025-03-04 16:30
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0068_remove_direct_access_type_from_reservation_unit"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                check=~models.Q(("access_code_generated_at", None), ("access_code_is_active", True)),
                name="no_access_code_but_active",
                violation_error_message="Reservation cannot have active access code if one is not generated",
            ),
        ),
    ]
