# Generated by Django 5.1.6 on 2025-03-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilavarauspalvelu', '0069_reservation_no_access_code_but_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationunitimage',
            options={'base_manager_name': 'objects', 'ordering': ['image_type'], 'verbose_name': 'reservation unit image', 'verbose_name_plural': 'reservation unit images'},
        ),
        migrations.AlterField(
            model_name='reservationunitimage',
            name='image_type',
            field=models.CharField(choices=[('main', 'Main image'), ('other', 'Other')], max_length=20),
        ),
    ]
