# Generated by Django 5.1.8 on 2025-04-17 10:02
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0074_paymentaccounting_internal_order_profit_center_or_project_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationunitpricing",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[("ONLINE", "Online"), ("ON_SITE", "On site"), ("INVOICE", "Invoice")],
                max_length=20,
                null=True,
            ),
        ),
    ]
