# Generated by Django 5.1.8 on 2025-04-17 10:02
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0075_paymentaccounting_internal_order_profit_center_or_project_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationunitpricing",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[("ON_SITE", "On site"), ("ONLINE", "Online"), ("ONLINE_OR_INVOICE", "Online or invoice")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymentorder",
            name="payment_type",
            field=models.CharField(
                choices=[("ON_SITE", "On site"), ("ONLINE", "Online"), ("ONLINE_OR_INVOICE", "Online or invoice")],
                max_length=128,
            ),
        ),
    ]
