# Generated by Django 5.1.8 on 2025-04-25 10:39
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0077_migrate_payment_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("EXPIRED", "Expired"),
                    ("CANCELLED", "Cancelled"),
                    ("PAID", "Paid"),
                    ("PAID_BY_INVOICE", "Paid by invoice"),
                    ("PAID_MANUALLY", "Paid manually"),
                    ("REFUNDED", "Refunded"),
                ],
                db_index=True,
                max_length=128,
            ),
        ),
    ]
