# Generated by Django 5.1.8 on 2025-04-29 09:06
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0078_add_payment_order_status_paid_by_invoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservationunit",
            name="payment_types",
        ),
        migrations.DeleteModel(
            name="ReservationUnitPaymentType",
        ),
    ]
