# Generated by Django 5.1.8 on 2025-05-13 15:18
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0079_remove_reservationunit_payment_types_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentorder",
            name="handled_payment_due_by",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="paymentorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING", "Pending"),
                    ("EXPIRED", "Expired"),
                    ("CANCELLED", "Cancelled"),
                    ("PAID", "Paid"),
                    ("PAID_BY_INVOICE", "Paid by invoice"),
                    ("PAID_MANUALLY", "Paid manually"),
                    ("REFUNDED", "Refunded"),
                ],
                db_index=True,
                max_length=128,
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentorder",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("status", "PENDING"), _negated=True),
                    models.Q(("status", "PENDING"), ("handled_payment_due_by__isnull", False)),
                    _connector="OR",
                ),
                name="pending_orders_must_have_due_date",
                violation_error_message="Orders in status 'PENDING' must have 'handled_payment_due_by' set.",
            ),
        ),
    ]
