# Generated by Django 5.1.8 on 2025-05-14 09:37
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0081_remove_duplicate_payment_orders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentorder",
            name="reservation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_order",
                to="tilavarauspalvelu.reservation",
            ),
        ),
    ]
