# Generated by Django 5.1.8 on 2025-05-23 09:23
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0082_alter_paymentorder_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationstatistic",
            name="ability_group",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="ability_group_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="age_group",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="cancel_reason",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="deny_reason",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="home_city",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="primary_reservation_unit",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="purpose",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
