# Generated by Django 5.1.8 on 2025-05-23 09:26
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tilavarauspalvelu", "0083_alter_reservationstatistic_ability_group_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReservationStatisticsReservationUnit",
        ),
    ]
