# Generated by Django 5.1.8 on 2025-05-23 10:39
from __future__ import annotations

from django.db import migrations


def migrate_func(apps, schema_editor):
    Reservation = apps.get_model("tilavarauspalvelu", "Reservation")

    qs = Reservation.objects.filter(cancel_reason__isnull=False)

    reservations = []

    # Cannot use a case since 'cancel_reason' is a relation.
    # There are about 30_000 cancelled reservations in production,
    # so updating their cancel reasons in a loop like this should be fine.
    for reservation in qs:
        if reservation.cancel_reason is None:  # just in case...
            continue

        match reservation.cancel_reason.reason_fi:
            case "Minulle tuli yllättävä este":
                reservation.new_cancel_reason = "CHANGE_OF_PLANS"

            case "En tarvitse varausta enää":
                reservation.new_cancel_reason = "CHANGE_OF_PLANS"

            case "Löysin toisen tilan Varaamosta":
                reservation.new_cancel_reason = "FOUND_ANOTHER_SPACE_VARAAMO"

            case "Löysin toisen tilan muualta":
                reservation.new_cancel_reason = "FOUND_ANOTHER_SPACE_ELSEWHERE"

            case "Aikatauluihin on tullut muutoksia":
                reservation.new_cancel_reason = "CHANGE_OF_PLANS"

            case "Kyseinen ajankohta ei ole enää sopiva":
                reservation.new_cancel_reason = "CHANGE_OF_PLANS"

            case "Tilan varustelu ei vastaa tarpeitani":
                reservation.new_cancel_reason = "UNSUITABLE_SPACE"

            case "Tila ei sovellu käyttötarkoitukseeni":
                reservation.new_cancel_reason = "UNSUITABLE_SPACE"

            case "Varauksen käsittelyaika on liian pitkä":
                reservation.new_cancel_reason = "PROCESSING_TIME_TOO_LONG"

            case _:
                reservation.new_cancel_reason = "OTHER"

        reservations.append(reservation)

    Reservation.objects.bulk_update(reservations, ["new_cancel_reason"])


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0085_reservation_new_cancel_reason"),
    ]

    operations = [
        migrations.RunPython(migrate_func, migrations.RunPython.noop),
    ]
