# Generated by Django 5.1.8 on 2025-05-23 10:51
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0086_migrate_cancel_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="cancel_reason",
        ),
    ]
