# Generated by Django 5.1.8 on 2025-05-23 10:55
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0087_remove_reservation_cancel_reason"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="new_cancel_reason",
            new_name="cancel_reason",
        ),
    ]
