# Generated by Django 5.1.8 on 2025-05-23 11:37
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0088_rename_new_cancel_reason_reservation_cancel_reason"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReservationCancelReason",
        ),
    ]
