# Generated by Django 5.1.8 on 2025-06-02 08:20
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tilavarauspalvelu", "0089_delete_reservationcancelreason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservationunit",
            name="qualifiers",
        ),
        migrations.DeleteModel(
            name="Qualifier",
        ),
    ]
