# Generated by Django 5.1.8 on 2025-06-02 09:05
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0090_remove_reservationunit_qualifiers_delete_qualifier"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BugReport",
        ),
        migrations.RemoveField(
            model_name="sqllog",
            name="request_log",
        ),
        migrations.DeleteModel(
            name="RequestLog",
        ),
        migrations.DeleteModel(
            name="SQLLog",
        ),
    ]
