# Generated by Django 5.1.8 on 2025-06-02 09:07
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tilavarauspalvelu", "0091_delete_bugreport_remove_sqllog_request_log_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringreservation",
            name="ability_group",
        ),
        migrations.DeleteModel(
            name="AbilityGroup",
        ),
    ]
