# Generated by Django 5.1.8 on 2025-06-02 09:08
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0092_remove_recurringreservation_ability_group_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="sku",
        ),
        migrations.RemoveField(
            model_name="reservationunit",
            name="sku",
        ),
    ]
