# Generated by Django 5.1.8 on 2025-06-02 10:17
from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0093_remove_reservation_sku_remove_reservationunit_sku"),
    ]

    operations = [
        migrations.RenameField(
            model_name="Reservation",
            old_name="recurring_reservation",
            new_name="reservation_series",
        ),
        migrations.RenameField(
            model_name="RejectedOccurrence",
            old_name="recurring_reservation",
            new_name="reservation_series",
        ),
        migrations.RenameModel(
            old_name="RecurringReservation",
            new_name="ReservationSeries",
        ),
        migrations.AlterModelTable(
            name="ReservationSeries",
            table="reservation_series",
        ),
        migrations.AlterModelOptions(
            name="ReservationSeries",
            options={
                "base_manager_name": "objects",
                "ordering": ["begin_date", "begin_time", "reservation_unit"],
                "verbose_name": "reservation series",
                "verbose_name_plural": "reservation series",
            },
        ),
        migrations.AlterField(
            model_name="ReservationSeries",
            name="age_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservation_series",
                to="tilavarauspalvelu.agegroup",
            ),
        ),
        migrations.AlterField(
            model_name="ReservationSeries",
            name="allocated_time_slot",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservation_series",
                to="tilavarauspalvelu.allocatedtimeslot",
            ),
        ),
        migrations.AlterField(
            model_name="ReservationSeries",
            name="reservation_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservation_series",
                to="tilavarauspalvelu.reservationunit",
            ),
        ),
        migrations.AlterField(
            model_name="ReservationSeries",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservation_series",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="termsofuse",
            name="terms_type",
            field=models.CharField(
                choices=[
                    ("generic_terms", "Generic terms"),
                    ("payment_terms", "Payment terms"),
                    ("cancellation_terms", "Cancellation terms"),
                    ("recurring_terms", "Reservation series terms"),
                    ("service_terms", "Service-specific terms"),
                    ("pricing_terms", "Pricing terms"),
                ],
                default="generic_terms",
                max_length=40,
            ),
        ),
    ]
