# Generated by Django 5.1.8 on 2025-06-05 10:19
from __future__ import annotations

from django.db import migrations


def update_application_additional_information(apps, schema_editor):
    Application = apps.get_model("tilavarauspalvelu", "Application")

    Application.objects.filter(additional_information=None).update(additional_information="")


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0094_rename_recurring_reservation_to_series"),
    ]

    operations = [
        migrations.RunPython(update_application_additional_information, migrations.RunPython.noop),
    ]
