# Generated by Django 5.1.8 on 2025-06-05 12:36
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0097_rename_application_round_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="applicationroundtimeslot",
            old_name="closed",
            new_name="is_closed",
        ),
        migrations.RemoveConstraint(
            model_name="applicationroundtimeslot",
            name="closed_no_slots_check",
        ),
        migrations.AddConstraint(
            model_name="applicationroundtimeslot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_closed", True), ("reservable_times__len", 0)),
                    models.Q(("is_closed", False), models.Q(("reservable_times__len", 0), _negated=True)),
                    _connector="OR",
                ),
                name="closed_no_slots_check",
                violation_error_message="Closed timeslots cannot have reservable times, but open timeslots must.",
            ),
        ),
    ]
