# Generated by Django 5.1.8 on 2025-06-05 13:22
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0100_rename_unit_role_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservationunitoption",
            old_name="locked",
            new_name="is_locked",
        ),
        migrations.RenameField(
            model_name="reservationunitoption",
            old_name="rejected",
            new_name="is_rejected",
        ),
    ]
