# Generated by Django 5.1.8 on 2025-06-05 13:41
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0101_rename_reservation_unit_option_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservationseries",
            old_name="created",
            new_name="created_at",
        ),
    ]
