# Generated by Django 5.1.8 on 2025-06-06 06:31
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0102_rename_reservation_series_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="begin",
            new_name="begins_at",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="end",
            new_name="ends_at",
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "base_manager_name": "objects",
                "ordering": ["begins_at"],
                "verbose_name": "reservation",
                "verbose_name_plural": "reservations",
            },
        ),
    ]
