# Generated by Django 5.1.8 on 2025-06-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0103_alter_reservation_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservationunit",
            old_name="uuid",
            new_name="ext_uuid",
        ),
        migrations.RenameField(
            model_name="reservationunit",
            old_name="terms_of_use",
            new_name="notes_when_applying",
        ),
        migrations.RenameField(
            model_name="reservationunit",
            old_name="terms_of_use_en",
            new_name="notes_when_applying_en",
        ),
        migrations.RenameField(
            model_name="reservationunit",
            old_name="terms_of_use_fi",
            new_name="notes_when_applying_fi",
        ),
        migrations.RenameField(
            model_name="reservationunit",
            old_name="terms_of_use_sv",
            new_name="notes_when_applying_sv",
        ),
        migrations.RenameField(
            model_name="reservationunit",
            old_name="publish_begins",
            new_name="publish_begins_at",
        ),
        migrations.RenameField(
            model_name="reservationunit",
            old_name="publish_ends",
            new_name="publish_ends_at",
        ),
        migrations.RenameField(
            model_name="reservationunit",
            old_name="reservation_begins",
            new_name="reservation_begins_at",
        ),
        migrations.RenameField(
            model_name="reservationunit",
            old_name="reservation_ends",
            new_name="reservation_ends_at",
        ),
    ]
