# Generated by Django 5.1.8 on 2025-06-06 09:32
from __future__ import annotations

from django.db import migrations


def migrate_location_to_unit(apps, schema_editor):
    Unit = apps.get_model("tilavarauspalvelu", "Unit")
    Location = apps.get_model("tilavarauspalvelu", "Location")

    units = []

    # After checking production, no locations exist for spaces.
    for location in Location.objects.filter(unit__isnull=False).select_related("unit"):
        unit = location.unit

        unit.address_street = location.address_street
        unit.address_street_fi = location.address_street_fi
        unit.address_street_en = location.address_street_en
        unit.address_street_sv = location.address_street_sv
        unit.address_city = location.address_city
        unit.address_city_fi = location.address_city_fi
        unit.address_city_en = location.address_city_en
        unit.address_city_sv = location.address_city_sv
        unit.address_zip = location.address_zip
        unit.coordinates = location.coordinates

        units.append(unit)

    Unit.objects.bulk_update(
        units,
        fields=[
            "address_street",
            "address_street_fi",
            "address_street_en",
            "address_street_sv",
            "address_city",
            "address_city_fi",
            "address_city_en",
            "address_city_sv",
            "address_zip",
            "coordinates",
        ],
    )


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0105_unit_address_city_unit_address_city_en_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_location_to_unit, reverse_code=migrations.RunPython.noop),
    ]
