# Generated by Django 5.1.8 on 2025-06-06 09:51
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0106_migrate_location_to_unit"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
    ]
