# Generated by Django 5.1.8 on 2025-06-06 10:26
from __future__ import annotations

from django.db import migrations, models

import tilavarauspalvelu.enums
import utils.fields.model


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0107_delete_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="billing_city",
            field=models.TextField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="application",
            name="billing_post_code",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="application",
            name="billing_street_address",
            field=models.TextField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="application",
            name="contact_person_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="contact_person_first_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="application",
            name="contact_person_last_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="application",
            name="contact_person_phone_number",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="application",
            name="municipality",
            field=utils.fields.model.StrChoiceField(
                blank=True,
                choices=[("Helsinki", "Helsinki"), ("Other", "Other")],
                enum=tilavarauspalvelu.enums.MunicipalityChoice,
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="municipality",
            field=utils.fields.model.StrChoiceField(
                blank=True,
                choices=[("HELSINKI", "Helsinki"), ("OTHER", "Other")],
                enum=tilavarauspalvelu.enums.MunicipalityChoice,
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="organisation_active_members",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="organisation_city",
            field=models.TextField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="application",
            name="organisation_core_business",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="application",
            name="organisation_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="organisation_identifier",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="application",
            name="organisation_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="application",
            name="organisation_post_code",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="application",
            name="organisation_street_address",
            field=models.TextField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="application",
            name="organisation_year_established",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
