# Generated by Django 5.1.8 on 2025-06-06 10:26
from __future__ import annotations

from django.db import migrations


def migrate_application_data_from_related_models(apps, schema_editor):
    Application = apps.get_model("tilavarauspalvelu", "Application")

    qs = Application.objects.select_related(
        "organisation",
        "contact_person",
        "billing_address",
        "organisation__address",
        "home_city",
    )

    applications = []

    for application in qs:
        organisation = application.organisation
        if organisation is not None:
            application.organisation_name = organisation.name
            application.organisation_email = organisation.email or None
            application.organisation_identifier = organisation.identifier or ""
            application.organisation_year_established = organisation.year_established
            application.organisation_active_members = organisation.active_members
            application.organisation_core_business = organisation.core_business

            organisation_address = organisation.address

            if organisation_address is not None:
                application.organisation_street_address = organisation_address.street_address
                application.organisation_post_code = organisation_address.post_code
                application.organisation_city = organisation_address.city

        contact_person = application.contact_person
        if contact_person is not None:
            application.contact_person_first_name = contact_person.first_name
            application.contact_person_last_name = contact_person.last_name
            application.contact_person_email = contact_person.email or None
            application.contact_person_phone_number = contact_person.phone_number or ""

        billing_address = application.billing_address
        if billing_address is not None:
            application.billing_street_address = billing_address.street_address
            application.billing_post_code = billing_address.post_code
            application.billing_city = billing_address.city

        home_city = application.home_city
        if home_city is not None:
            if home_city.name == "Helsinki":
                application.municipality = "HELSINKI"
            else:
                application.municipality = "OTHER"

        applications.append(application)

    Application.objects.bulk_update(
        applications,
        fields=[
            "organisation_name",
            "organisation_email",
            "organisation_identifier",
            "organisation_year_established",
            "organisation_active_members",
            "organisation_core_business",
            "organisation_street_address",
            "organisation_post_code",
            "organisation_city",
            "contact_person_first_name",
            "contact_person_last_name",
            "contact_person_email",
            "contact_person_phone_number",
            "billing_street_address",
            "billing_post_code",
            "billing_city",
            "municipality",
        ],
    )


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0108_application_billing_city_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_application_data_from_related_models,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
