# Generated by Django 5.1.8 on 2025-06-06 14:07
from __future__ import annotations

from django.db import migrations


def migrate_home_city_for_reservation(apps, schema_editor):
    Reservation = apps.get_model("tilavarauspalvelu", "Application")

    qs = Reservation.objects.filter(home_city__isnull=False)

    qs.filter(home_city__municipality_code="091").update(municipality="HELSINKI")
    qs.filter(home_city__municipality_code="199").update(municipality="OTHER")


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0109_migrate_application_data_from_related_models"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_home_city_for_reservation,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
