# Generated by Django 5.1.8 on 2025-06-06 14:07
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0110_migrate_reservation_home_city_to_municipality"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="billing_address",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="address",
        ),
        migrations.RemoveField(
            model_name="application",
            name="home_city",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="home_city",
        ),
        migrations.RemoveField(
            model_name="application",
            name="organisation",
        ),
        migrations.RemoveField(
            model_name="application",
            name="contact_person",
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="Organisation",
        ),
        migrations.DeleteModel(
            name="Person",
        ),
    ]
