# Generated by Django 5.1.8 on 2025-06-09 07:30
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0111_remove_application_billing_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="reservation_units",
            field=models.ManyToManyField(
                related_name="reservations_set",
                to="tilavarauspalvelu.reservationunit",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="reservation_unit",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="tilavarauspalvelu.reservationunit",
            ),
            preserve_default=False,
        ),
    ]
