# Generated by Django 5.1.8 on 2025-06-09 07:30
from __future__ import annotations

import itertools

from django.db import migrations, models


def migrate_reservation_reservation_unit(apps, schema_editor):
    Reservation = apps.get_model("tilavarauspalvelu", "Reservation")

    # There are a lot of reservations in production, so we make the migration in batches.
    # Cannot simply use a 'qs.update()' call, since joins are not permitted in those queries.
    #
    # This strategy fetches reservations in batches and updates the 'reservation_unit_id'
    # for the foreign key relationship with a matching id from the many-to-many relationship.
    #
    # We cannot do all of them at once, since each when-condition requires 2 variables,
    # and PostgreSQL has a variable limit of 32_767. That's why we update 20_000 reservations
    # at a time. This will still likely be slow, and so we should use a longer timeout for the migration.

    chunk_size = 10_000
    reservations = Reservation.objects.values("pk", "reservation_units__id").iterator(chunk_size=chunk_size)

    for reservations_batch in itertools.batched(reservations, chunk_size, strict=False):
        pks = set()
        whens = []

        for item in reservations_batch:
            when = models.When(
                condition=models.Q(pk=item["pk"]),
                then=models.Value(item["reservation_units__id"]),
            )
            whens.append(when)
            pks.add(item["pk"])

        Reservation.objects.filter(pk__in=pks).update(
            reservation_unit_id=models.Case(
                *whens,
                default=models.F("reservation_unit_id"),
                output_field=models.IntegerField(),
            )
        )

    missing = Reservation.objects.filter(reservation_unit__isnull=True).count()
    if missing > 0:
        msg = f"Migration incomplete, {missing} reservations have no reservation unit."
        raise RuntimeError(msg)


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0112_reservation_reservation_unit_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_reservation_reservation_unit,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
