# Generated by Django 5.1.8 on 2025-06-10 16:37
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0114_remove_reservation_reservation_units_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationunit",
            name="reservation_form",
            field=models.CharField(
                choices=[
                    ("CONTACT_INFO_FORM", "Contact info form"),
                    ("RESERVEE_INFO_FORM", "Reservee info form"),
                    ("PURPOSE_FORM", "Purpose form"),
                    ("AGE_GROUP_FORM", "Age group form"),
                    ("PURPOSE_SUBVENTION_FORM", "Purpose subvention form"),
                    ("AGE_GROUP_SUBVENTION_FORM", "Age group subvention form"),
                ],
                db_index=True,
                default="CONTACT_INFO_FORM",
                max_length=255,
            ),
        ),
    ]
