# Generated by Django 5.1.8 on 2025-06-11 07:28
from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def check_no_null_reservation_series_user(apps, schema_editor):
    ReservationSeries = apps.get_model("tilavarauspalvelu", "ReservationSeries")

    null_user_series = ReservationSeries.objects.filter(user__isnull=True).count()

    if null_user_series > 0:
        msg = f"{null_user_series} reservations series have a null user. Cannot migrate to non-null column."
        raise RuntimeError(msg)


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0117_alter_application_user"),
    ]

    operations = [
        migrations.RunPython(
            code=check_no_null_reservation_series_user,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="reservationseries",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservation_series",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
