# Generated by Django 5.1.8 on 2025-06-11 08:14
from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def check_no_null_reservation_user(apps, schema_editor):
    Reservation = apps.get_model("tilavarauspalvelu", "Reservation")

    null_user_reservations = Reservation.objects.filter(user__isnull=True).count()

    if null_user_reservations > 0:
        msg = f"{null_user_reservations} reservations have a null user. Cannot migrate to non-null column."
        raise RuntimeError(msg)


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0118_alter_reservationseries_user"),
    ]

    operations = [
        migrations.RunPython(
            code=check_no_null_reservation_user,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
