# Generated by Django 5.1.8 on 2025-06-11 09:06
from __future__ import annotations

from django.db import migrations, models


def check_no_null_reservation_working_memo(apps, schema_editor):
    Reservation = apps.get_model("tilavarauspalvelu", "Reservation")

    null_memo = Reservation.objects.filter(working_memo__isnull=True).count()

    if null_memo > 0:
        msg = f"{null_memo} reservations have a null working memo. Cannot migrate to non-null column."
        raise RuntimeError(msg)


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0119_alter_reservation_user"),
    ]

    operations = [
        migrations.RunPython(
            code=check_no_null_reservation_working_memo,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="reservation",
            name="working_memo",
            field=models.TextField(blank=True, default=""),
        ),
    ]
