# Generated by Django 5.1.8 on 2025-06-11 09:40
from __future__ import annotations

from django.db import migrations, models


def check_no_null_reservation_series_times(apps, schema_editor):
    ReservationSeries = apps.get_model("tilavarauspalvelu", "ReservationSeries")

    null_times = ReservationSeries.objects.filter(
        models.Q(begin_date__isnull=True)
        | models.Q(begin_time__isnull=True)
        | models.Q(end_date__isnull=True)
        | models.Q(end_time__isnull=True)
    ).count()

    if null_times > 0:
        msg = f"{null_times} series have a non-null begin/end date/time. Cannot migrate to non-null columns."
        raise RuntimeError(msg)


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0120_alter_reservation_working_memo"),
    ]

    operations = [
        migrations.RunPython(
            code=check_no_null_reservation_series_times,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="reservationseries",
            name="begin_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="reservationseries",
            name="begin_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="reservationseries",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="reservationseries",
            name="end_time",
            field=models.TimeField(),
        ),
    ]
