# Generated by Django 5.1.8 on 2025-06-11 10:01
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


def check_no_null_reservation_unit_unit(apps, schema_editor):
    ReservationUnit = apps.get_model("tilavarauspalvelu", "ReservationUnit")

    null_unit = ReservationUnit.objects.filter(unit__isnull=True).count()

    if null_unit > 0:
        msg = f"{null_unit} reservation units have a null unit. Cannot migrate to non-null column."
        raise RuntimeError(msg)


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0121_alter_reservationseries_begin_date_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=check_no_null_reservation_unit_unit,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservation_units",
                to="tilavarauspalvelu.unit",
            ),
        ),
    ]
