# Generated by Django 5.1.8 on 2025-06-11 10:25
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


def check_no_null_space_unit(apps, schema_editor):
    Space = apps.get_model("tilavarauspalvelu", "Space")

    null_unit = Space.objects.filter(unit__isnull=True).count()

    if null_unit > 0:
        msg = f"{null_unit} spaces have a null unit. Cannot migrate to non-null column."
        raise RuntimeError(msg)


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0122_alter_reservationunit_unit"),
    ]

    operations = [
        migrations.RunPython(
            code=check_no_null_space_unit,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="space",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="spaces",
                to="tilavarauspalvelu.unit",
            ),
        ),
    ]
