# Generated by Django 5.1.8 on 2025-06-11 10:51
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0123_alter_space_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationunitpricing",
            name="reservation_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricings",
                to="tilavarauspalvelu.reservationunit",
            ),
        ),
    ]
