# Generated by Django 5.1.8 on 2025-06-11 10:44
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0124_alter_reservationunitpricing_reservation_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationunitpricing",
            name="tax_percentage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservation_unit_pricings",
                to="tilavarauspalvelu.taxpercentage",
            ),
        ),
    ]
