# Generated by Django 5.1.8 on 2025-06-11 11:16
from __future__ import annotations

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0125_alter_reservationunitpricing_tax_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationseries",
            name="new_weekdays",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("MONDAY", "Monday"),
                        ("TUESDAY", "Tuesday"),
                        ("WEDNESDAY", "Wednesday"),
                        ("THURSDAY", "Thursday"),
                        ("FRIDAY", "Friday"),
                        ("SATURDAY", "Saturday"),
                        ("SUNDAY", "Sunday"),
                    ],
                    max_length=255,
                ),
                default=list,
                size=7,
            ),
        ),
    ]
