# Generated by Django 5.1.8 on 2025-06-11 11:16
from __future__ import annotations

from django.db import migrations


def migrate_series_weekdays(apps, schema_editor):
    ReservationSeries = apps.get_model("tilavarauspalvelu", "ReservationSeries")

    all_series = list(ReservationSeries.objects.all())

    for series in all_series:
        weekdays = []

        for weekday_num in series.weekdays:
            match weekday_num:
                case "0":
                    weekdays.append("MONDAY")
                case "1":
                    weekdays.append("TUESDAY")
                case "2":
                    weekdays.append("WEDNESDAY")
                case "3":
                    weekdays.append("THURSDAY")
                case "4":
                    weekdays.append("FRIDAY")
                case "5":
                    weekdays.append("SATURDAY")
                case "6":
                    weekdays.append("SUNDAY")
                case ",":
                    pass
                case _:
                    msg = f"Invalid weekday for series {series.pk}: {weekday_num} {type(weekday_num)}"
                    raise ValueError(msg)

        series.new_weekdays = weekdays

    ReservationSeries.objects.bulk_update(all_series, ["new_weekdays"])


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0126_add_new_reservation_series_weekdays"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_series_weekdays,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
