# Generated by Django 5.1.8 on 2025-06-11 12:21
from __future__ import annotations

from typing import Any

from django.db import migrations, models

import tilavarauspalvelu.enums


class StrChoiceField(models.CharField):
    """CharField for TextChoices that automatically sets 'max_length' to the length of the longest choice."""

    def __init__(self, enum: type[models.Choices], **kwargs: Any) -> None:
        self.enum = enum
        kwargs["max_length"] = max(len(val) for val, _ in enum.choices)
        kwargs["choices"] = enum.choices
        super().__init__(**kwargs)

    def deconstruct(self) -> tuple[str, str, list[Any], dict[str, Any]]:
        name, path, args, kwargs = super().deconstruct()
        kwargs["enum"] = self.enum
        return name, path, args, kwargs


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0129_rename_series_new_weekdays"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationroundtimeslot",
            name="new_weekday",
            field=StrChoiceField(
                choices=[
                    ("MONDAY", "Monday"),
                    ("TUESDAY", "Tuesday"),
                    ("WEDNESDAY", "Wednesday"),
                    ("THURSDAY", "Thursday"),
                    ("FRIDAY", "Friday"),
                    ("SATURDAY", "Saturday"),
                    ("SUNDAY", "Sunday"),
                ],
                enum=tilavarauspalvelu.enums.Weekday,
                default=tilavarauspalvelu.enums.Weekday.MONDAY,  # Will be updated later
                max_length=9,
            ),
        ),
    ]
