# Generated by Django 5.1.8 on 2025-06-11 12:21
from __future__ import annotations

from django.db import migrations

import tilavarauspalvelu.enums
import utils.fields.model


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0129_rename_series_new_weekdays"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationroundtimeslot",
            name="new_weekday",
            field=utils.fields.model.StrChoiceField(
                choices=[
                    ("MONDAY", "Monday"),
                    ("TUESDAY", "Tuesday"),
                    ("WEDNESDAY", "Wednesday"),
                    ("THURSDAY", "Thursday"),
                    ("FRIDAY", "Friday"),
                    ("SATURDAY", "Saturday"),
                    ("SUNDAY", "Sunday"),
                ],
                enum=tilavarauspalvelu.enums.Weekday,
                default=tilavarauspalvelu.enums.Weekday.MONDAY,  # Will be updated later
                max_length=9,
            ),
        ),
    ]
