# Generated by Django 5.1.8 on 2025-06-11 12:21
from __future__ import annotations

from django.db import migrations, models


def migrate_arts_weekdays(apps, schema_editor):
    ApplicationRoundTimeSlot = apps.get_model("tilavarauspalvelu", "ApplicationRoundTimeSlot")

    ApplicationRoundTimeSlot.objects.update(
        new_weekday=models.Case(
            models.When(weekday=0, then=models.Value("MONDAY")),
            models.When(weekday=1, then=models.Value("TUESDAY")),
            models.When(weekday=2, then=models.Value("WEDNESDAY")),
            models.When(weekday=3, then=models.Value("THURSDAY")),
            models.When(weekday=4, then=models.Value("FRIDAY")),
            models.When(weekday=5, then=models.Value("SATURDAY")),
            models.When(weekday=6, then=models.Value("SUNDAY")),
            default=models.Value("MONDAY"),
            output_field=models.CharField(),
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0130_add_new_arts_weekday"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_arts_weekdays,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
