# Generated by Django 5.1.8 on 2025-06-11 11:56
from __future__ import annotations

from django.db import migrations

import tilavarauspalvelu.enums
import utils.fields.model


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0132_remove_old_arts_weekday"),
    ]

    operations = [
        migrations.RenameField(
            model_name="applicationroundtimeslot",
            old_name="new_weekday",
            new_name="weekday",
        ),
        migrations.AlterField(
            model_name="applicationroundtimeslot",
            name="weekday",
            field=utils.fields.model.StrChoiceField(
                choices=[
                    ("MONDAY", "Monday"),
                    ("TUESDAY", "Tuesday"),
                    ("WEDNESDAY", "Wednesday"),
                    ("THURSDAY", "Thursday"),
                    ("FRIDAY", "Friday"),
                    ("SATURDAY", "Saturday"),
                    ("SUNDAY", "Sunday"),
                ],
                enum=tilavarauspalvelu.enums.Weekday,
                max_length=9,
            ),
        ),
    ]
