# Generated by Django 5.1.8 on 2025-06-12 07:28
from __future__ import annotations

from django.db import migrations

import tilavarauspalvelu.enums
import utils.fields.model


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0133_rename_arts_new_weekday"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="new_applicant_type",
            field=utils.fields.model.StrChoiceField(
                blank=True,
                choices=[("INDIVIDUAL", "Individual"), ("COMPANY", "Company"), ("NONPROFIT", "Nonprofit")],
                enum=tilavarauspalvelu.enums.ReserveeType,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="new_reservee_type",
            field=utils.fields.model.StrChoiceField(
                blank=True,
                choices=[("INDIVIDUAL", "Individual"), ("COMPANY", "Company"), ("NONPROFIT", "Nonprofit")],
                enum=tilavarauspalvelu.enums.ReserveeType,
                max_length=10,
                null=True,
            ),
        ),
    ]
