# Generated by Django 5.1.8 on 2025-06-12 07:28
from __future__ import annotations

from typing import Any

from django.db import migrations, models

import tilavarauspalvelu.enums


class StrChoiceField(models.CharField):
    """CharField for TextChoices that automatically sets 'max_length' to the length of the longest choice."""

    def __init__(self, enum: type[models.Choices], **kwargs: Any) -> None:
        self.enum = enum
        kwargs["max_length"] = max(len(val) for val, _ in enum.choices)
        kwargs["choices"] = enum.choices
        super().__init__(**kwargs)

    def deconstruct(self) -> tuple[str, str, list[Any], dict[str, Any]]:
        name, path, args, kwargs = super().deconstruct()
        kwargs["enum"] = self.enum
        return name, path, args, kwargs


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0133_rename_arts_new_weekday"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="new_applicant_type",
            field=StrChoiceField(
                blank=True,
                choices=[("INDIVIDUAL", "Individual"), ("COMPANY", "Company"), ("NONPROFIT", "Nonprofit")],
                enum=tilavarauspalvelu.enums.ReserveeType,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="new_reservee_type",
            field=StrChoiceField(
                blank=True,
                choices=[("INDIVIDUAL", "Individual"), ("COMPANY", "Company"), ("NONPROFIT", "Nonprofit")],
                enum=tilavarauspalvelu.enums.ReserveeType,
                max_length=10,
                null=True,
            ),
        ),
    ]
