# Generated by Django 5.1.8 on 2025-06-12 07:28
from __future__ import annotations

from django.db import migrations, models


def migrate_applicant_and_reservee_types(apps, schema_editor):
    Application = apps.get_model("tilavarauspalvelu", "Application")
    Reservation = apps.get_model("tilavarauspalvelu", "Reservation")

    Application.objects.update(
        new_applicant_type=models.Case(
            models.When(models.Q(applicant_type="INDIVIDUAL"), then=models.Value("INDIVIDUAL")),
            models.When(models.Q(applicant_type="COMPANY"), then=models.Value("COMPANY")),
            models.When(models.Q(applicant_type="ASSOCIATION"), then=models.Value("NONPROFIT")),
            models.When(models.Q(applicant_type="COMMUNITY"), then=models.Value("NONPROFIT")),
            default=None,
        ),
    )

    Reservation.objects.update(
        new_reservee_type=models.Case(
            models.When(models.Q(reservee_type="INDIVIDUAL"), then=models.Value("INDIVIDUAL")),
            models.When(models.Q(reservee_type="BUSINESS"), then=models.Value("COMPANY")),
            models.When(models.Q(reservee_type="NONPROFIT"), then=models.Value("NONPROFIT")),
            default=None,
        ),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0134_add_new_applicant_and_reservee_types"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_applicant_and_reservee_types,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
