# Generated by Django 5.1.8 on 2025-06-11 11:56
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0135_migrate_applicant_and_reservee_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="applicant_type",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="reservee_type",
        ),
    ]
