# Generated by Django 5.1.8 on 2025-06-11 11:56
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0136_remove_old_applicant_and_reservee_types"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="new_applicant_type",
            new_name="applicant_type",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="new_reservee_type",
            new_name="reservee_type",
        ),
    ]
