# Generated by Django 5.1.8 on 2025-06-12 09:16
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0137_rename_new_applicant_and_reservee_types"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="reservee_id",
            new_name="reservee_identifier",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="reservee_is_unregistered_association",
        ),
    ]
