# Generated by Django 5.1.8 on 2025-06-12 07:28
from __future__ import annotations

from django.db import migrations


def migrate_metadata_fields(apps, schema_editor):
    ReservationMetadataField = apps.get_model("tilavarauspalvelu", "ReservationMetadataField")

    ReservationMetadataField.objects.filter(field_name="reservee_id").update(field_name="reservee_identifier")
    ReservationMetadataField.objects.filter(field_name="reservee_is_unregistered_association").delete()
    ReservationMetadataField.objects.filter(field_name="home_city").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0138_rename_reservee_id_reservation_reservee_identifier_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_metadata_fields,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
