# Generated by Django 5.1.8 on 2025-06-12 10:36
from __future__ import annotations

from django.db import migrations, models


def migrate_reservation_kind(apps, schema_editor):
    ReservationUnit = apps.get_model("tilavarauspalvelu", "ReservationUnit")

    ReservationUnit.objects.update(
        new_reservation_kind=models.Case(
            models.When(models.Q(reservation_kind="direct"), then=models.Value("DIRECT")),
            models.When(models.Q(reservation_kind="season"), then=models.Value("SEASON")),
            models.When(models.Q(reservation_kind="direct_and_season"), then=models.Value("DIRECT_AND_SEASON")),
            default=None,
            output_field=models.CharField(),
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0140_add_new_reservation_kind"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_reservation_kind,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
