# Generated by Django 5.1.8 on 2025-06-13 04:42
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0143_rename_new_reservation_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="cancel_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHANGE_OF_PLANS", "My plans have changed"),
                    ("FOUND_ANOTHER_SPACE_ELSEWHERE", "I found another space somewhere else"),
                    ("FOUND_ANOTHER_SPACE_VARAAMO", "I found another space through Varaamo"),
                    ("UNSUITABLE_SPACE", "The space is not suitable for my purpose"),
                    ("PROCESSING_TIME_TOO_LONG", "The booking processing time is too long"),
                    ("OTHER", "Other reason"),
                    (
                        "NOT_PAID",
                        (
                            "The booking was not paid for or invoice was not "
                            "selected as the payment method by the deadline."
                        ),
                    ),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
