# Generated by Django 5.1.8 on 2025-06-13 04:42
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0144_alter_reservation_cancel_reasons"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="billing_address_city",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="billing_address_street",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="billing_address_zip",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="billing_email",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="billing_first_name",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="billing_last_name",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="billing_phone",
        ),
    ]
