# Generated by Django 5.1.8 on 2025-06-12 07:28
from __future__ import annotations

from django.db import migrations


def migrate_metadata_fields(apps, schema_editor):
    ReservationMetadataField = apps.get_model("tilavarauspalvelu", "ReservationMetadataField")

    fields_to_delete = [
        "billing_first_name",
        "billing_last_name",
        "billing_email",
        "billing_phone",
        "billing_address_street",
        "billing_address_zip",
        "billing_address_city",
    ]

    ReservationMetadataField.objects.filter(field_name__in=fields_to_delete).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0145_remove_reservation_billing_address_city_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_metadata_fields,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
