# Generated by Django 5.1.11 on 2025-07-17 09:48
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0146_migrate_metadata_fields"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="bannernotification",
            name="level_priority_index",
        ),
        migrations.RemoveIndex(
            model_name="bannernotification",
            name="target_priority_index",
        ),
    ]
