# Generated by Django 5.1.11 on 2025-08-29 08:40
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0148_affecting_reservations_now_tt_split"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationunit",
            name="reservation_form",
            field=models.CharField(
                choices=[
                    ("CONTACT_INFO_FORM", "Contact information only"),
                    ("RESERVEE_INFO_FORM", "Contact information and event description"),
                    ("PURPOSE_FORM", "Purpose of use"),
                    ("AGE_GROUP_FORM", "Age group"),
                    ("PURPOSE_SUBVENTION_FORM", "Purpose of use + discount"),
                    ("AGE_GROUP_SUBVENTION_FORM", "Age group + discount"),
                ],
                db_index=True,
                default="CONTACT_INFO_FORM",
                max_length=255,
            ),
        ),
    ]
