# Generated by Django 5.1.11 on 2025-07-20 08:49
from __future__ import annotations

from inspect import cleandoc

import django.contrib.postgres.fields
from django.db import migrations

import tilavarauspalvelu.enums
import utils.fields.model


def drop_affecting_reservations() -> str:
    return cleandoc(
        """
        DROP INDEX IF EXISTS idx_buffered_end_datetime;
        DROP INDEX IF EXISTS idx_buffered_start_datetime;
        DROP INDEX IF EXISTS idx_affected_reservation_unit_ids;
        DROP INDEX IF EXISTS idx_reservation_id;
        DROP MATERIALIZED VIEW IF EXISTS affecting_time_spans;
        """
    )


def create_affecting_reservations() -> str:
    # SELECT 1 is for syntax highlighting in PyCharm
    return cleandoc(
        """
        SELECT 1;
        CREATE MATERIALIZED VIEW affecting_time_spans AS
             SELECT
                res.reservation_id,
                array_agg(res.ru_id ORDER BY res.ru_id) AS affected_reservation_unit_ids,
                res.buffered_start_datetime,
                res.buffered_end_datetime,
                res.buffer_time_before,
                res.buffer_time_after,
                res.is_blocking
            FROM (
                SELECT DISTINCT
                    r.id as reservation_id,
                    unnest(ruh.related_reservation_unit_ids) as ru_id,
                    (r.begins_at - r.buffer_time_before) as buffered_start_datetime,
                    (r.ends_at + r.buffer_time_after) as buffered_end_datetime,
                    r.buffer_time_before as buffer_time_before,
                    r.buffer_time_after as buffer_time_after,
                    (CASE WHEN UPPER(r."type") = 'BLOCKED' THEN true ELSE false END) as is_blocking
                FROM reservation r
                INNER JOIN "reservation_unit_hierarchy" ruh ON r.reservation_unit_id = ruh.reservation_unit_id
                WHERE (
                    (r.ends_at + r.buffer_time_after)::date >= NOW_TT()::date
                    AND UPPER(r.state) IN ('CREATED', 'CONFIRMED', 'WAITING_FOR_PAYMENT', 'REQUIRES_HANDLING')
                )
            ) res
            GROUP BY
                res.reservation_id,
                res.buffered_start_datetime,
                res.buffered_end_datetime,
                res.buffer_time_before,
                res.buffer_time_after,
                res.is_blocking
            ORDER BY res.buffered_start_datetime, res.reservation_id;

        CREATE UNIQUE INDEX idx_reservation_id ON affecting_time_spans (reservation_id);
        CREATE INDEX idx_affected_reservation_unit_ids on affecting_time_spans USING GIN (
            affected_reservation_unit_ids gin__int_ops
        );
        CREATE INDEX idx_buffered_start_datetime ON affecting_time_spans (buffered_start_datetime);
        CREATE INDEX idx_buffered_end_datetime ON affecting_time_spans (buffered_end_datetime);
        """
    )


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0150_remove_bannernotification_level_priority_index_and_more"),
    ]

    operations = [
        migrations.RunSQL(sql=drop_affecting_reservations(), reverse_sql=None),
        migrations.AlterField(
            model_name="allocatedtimeslot",
            name="day_of_the_week",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("MONDAY", "Monday"),
                    ("TUESDAY", "Tuesday"),
                    ("WEDNESDAY", "Wednesday"),
                    ("THURSDAY", "Thursday"),
                    ("FRIDAY", "Friday"),
                    ("SATURDAY", "Saturday"),
                    ("SUNDAY", "Sunday"),
                ],
                choices_enum=tilavarauspalvelu.enums.Weekday,
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="applicant_type",
            field=utils.fields.model.TextChoicesField(
                blank=True,
                choices=[
                    ("INDIVIDUAL", "Individual"),
                    ("COMPANY", "Company"),
                    ("NONPROFIT", "Nonprofit"),
                ],
                choices_enum=tilavarauspalvelu.enums.ReserveeType,
                max_length=10,  # Max length changed
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="municipality",
            field=utils.fields.model.TextChoicesField(
                blank=True,
                choices=[
                    ("HELSINKI", "Helsinki"),
                    ("OTHER", "Other"),
                ],
                choices_enum=tilavarauspalvelu.enums.MunicipalityChoice,
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="applicationroundtimeslot",
            name="weekday",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("MONDAY", "Monday"),
                    ("TUESDAY", "Tuesday"),
                    ("WEDNESDAY", "Wednesday"),
                    ("THURSDAY", "Thursday"),
                    ("FRIDAY", "Friday"),
                    ("SATURDAY", "Saturday"),
                    ("SUNDAY", "Sunday"),
                ],
                choices_enum=tilavarauspalvelu.enums.Weekday,
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="bannernotification",
            name="level",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("EXCEPTION", "Exception"),
                    ("WARNING", "Warning"),
                    ("NORMAL", "Normal"),
                ],
                choices_enum=tilavarauspalvelu.enums.BannerNotificationLevel,
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="bannernotification",
            name="target",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("ALL", "All"),
                    ("STAFF", "Staff"),
                    ("USER", "User"),
                ],
                choices_enum=tilavarauspalvelu.enums.BannerNotificationTarget,
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="generalrole",
            name="role",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("HANDLER", "Handler"),
                    ("VIEWER", "Viewer"),
                    ("RESERVER", "Reserver"),
                    ("NOTIFICATION_MANAGER", "Notification manager"),
                ],
                choices_enum=tilavarauspalvelu.enums.UserRoleChoice,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paymentorder",
            name="language",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("fi", "Finnish"),
                    ("sv", "Swedish"),
                    ("en", "English"),
                ],
                choices_enum=tilavarauspalvelu.enums.Language,
                max_length=2,  # Max length changed
            ),
        ),
        migrations.AlterField(
            model_name="paymentorder",
            name="payment_type",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("ON_SITE", "On site"),
                    ("ONLINE", "Online"),
                    ("ONLINE_OR_INVOICE", "Online or invoice"),
                ],
                choices_enum=tilavarauspalvelu.enums.PaymentType,
                max_length=17,  # Max length changed
            ),
        ),
        migrations.AlterField(
            model_name="paymentorder",
            name="status",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING", "Pending"),
                    ("EXPIRED", "Expired"),
                    ("CANCELLED", "Cancelled"),
                    ("PAID", "Paid"),
                    ("PAID_BY_INVOICE", "Paid by invoice"),
                    ("PAID_MANUALLY", "Paid manually"),
                    ("REFUNDED", "Refunded"),
                ],
                choices_enum=tilavarauspalvelu.enums.OrderStatus,
                db_index=True,
                max_length=15,  # Max length changed
            ),
        ),
        migrations.AlterField(
            model_name="rejectedoccurrence",
            name="rejection_reason",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("INTERVAL_NOT_ALLOWED", "Interval not allowed"),
                    ("OVERLAPPING_RESERVATIONS", "Overlapping reservations"),
                    ("RESERVATION_UNIT_CLOSED", "Reservation unit closed"),
                ],
                choices_enum=tilavarauspalvelu.enums.RejectionReadinessChoice,
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="access_type",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("ACCESS_CODE", "access code"),
                    ("OPENED_BY_STAFF", "opened by staff"),
                    ("PHYSICAL_KEY", "physical key"),
                    ("UNRESTRICTED", "unrestricted"),
                ],
                choices_enum=tilavarauspalvelu.enums.AccessType,
                default="UNRESTRICTED",
                max_length=15,  # Max length changed
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="cancel_reason",
            field=utils.fields.model.TextChoicesField(
                blank=True,
                choices=[
                    ("CHANGE_OF_PLANS", "My plans have changed"),
                    ("FOUND_ANOTHER_SPACE_ELSEWHERE", "I found another space somewhere else"),
                    ("FOUND_ANOTHER_SPACE_VARAAMO", "I found another space through Varaamo"),
                    ("UNSUITABLE_SPACE", "The space is not suitable for my purpose"),
                    ("PROCESSING_TIME_TOO_LONG", "The booking processing time is too long"),
                    ("OTHER", "Other reason"),
                    (
                        "NOT_PAID",
                        (
                            "The booking was not paid for or invoice was "
                            "not selected as the payment method by the deadline."
                        ),
                    ),
                ],
                choices_enum=tilavarauspalvelu.enums.ReservationCancelReasonChoice,
                max_length=29,  # Max length changed
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="municipality",
            field=utils.fields.model.TextChoicesField(
                blank=True,
                choices=[
                    ("HELSINKI", "Helsinki"),
                    ("OTHER", "Other"),
                ],
                choices_enum=tilavarauspalvelu.enums.MunicipalityChoice,
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee_type",
            field=utils.fields.model.TextChoicesField(
                blank=True,
                choices=[
                    ("INDIVIDUAL", "Individual"),
                    ("COMPANY", "Company"),
                    ("NONPROFIT", "Nonprofit"),
                ],
                choices_enum=tilavarauspalvelu.enums.ReserveeType,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="state",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("CREATED", "Created"),
                    ("CANCELLED", "Cancelled"),
                    ("REQUIRES_HANDLING", "Requires handling"),
                    ("WAITING_FOR_PAYMENT", "Waiting for payment"),
                    ("CONFIRMED", "Confirmed"),
                    ("DENIED", "Denied"),
                ],
                choices_enum=tilavarauspalvelu.enums.ReservationStateChoice,
                db_index=True,
                default="CREATED",
                max_length=19,  # Max length changed
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="type",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("NORMAL", "Normal"),
                    ("BLOCKED", "Blocked"),
                    ("STAFF", "Staff"),
                    ("BEHALF", "Behalf"),
                    ("SEASONAL", "Seasonal"),
                ],
                choices_enum=tilavarauspalvelu.enums.ReservationTypeChoice,
                default="NORMAL",
                max_length=8,  # Max length changed
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservationseries",
            name="weekdays",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=utils.fields.model.TextChoicesField(
                    choices=[
                        ("MONDAY", "Monday"),
                        ("TUESDAY", "Tuesday"),
                        ("WEDNESDAY", "Wednesday"),
                        ("THURSDAY", "Thursday"),
                        ("FRIDAY", "Friday"),
                        ("SATURDAY", "Saturday"),
                        ("SUNDAY", "Sunday"),
                    ],
                    choices_enum=tilavarauspalvelu.enums.Weekday,
                    max_length=9,  # Max length changed
                ),
                default=list,
                size=7,
            ),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="authentication",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("weak", "Weak"),
                    ("strong", "Strong"),
                ],
                choices_enum=tilavarauspalvelu.enums.AuthenticationType,
                default="weak",
                max_length=6,  # Max length changed
            ),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="reservation_form",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("CONTACT_INFO_FORM", "Contact info form"),
                    ("RESERVEE_INFO_FORM", "Reservee info form"),
                    ("PURPOSE_FORM", "Purpose form"),
                    ("AGE_GROUP_FORM", "Age group form"),
                    ("PURPOSE_SUBVENTION_FORM", "Purpose subvention form"),
                    ("AGE_GROUP_SUBVENTION_FORM", "Age group subvention form"),
                ],
                choices_enum=tilavarauspalvelu.enums.ReservationFormType,
                db_index=True,
                default="CONTACT_INFO_FORM",
                max_length=25,  # Max length changed
            ),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="reservation_kind",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("DIRECT", "Direct"),
                    ("SEASON", "Season"),
                    ("DIRECT_AND_SEASON", "Direct and season"),
                ],
                choices_enum=tilavarauspalvelu.enums.ReservationKind,
                db_index=True,
                default="DIRECT_AND_SEASON",
                max_length=17,
            ),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="reservation_start_interval",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("interval_15_mins", "15 minutes"),
                    ("interval_30_mins", "30 minutes"),
                    ("interval_60_mins", "60 minutes"),
                    ("interval_90_mins", "90 minutes"),
                    ("interval_120_mins", "2 hours"),
                    ("interval_180_mins", "3 hours"),
                    ("interval_240_mins", "4 hours"),
                    ("interval_300_mins", "5 hours"),
                    ("interval_360_mins", "6 hours"),
                    ("interval_420_mins", "7 hours"),
                ],
                choices_enum=tilavarauspalvelu.enums.ReservationStartInterval,
                default="interval_15_mins",
                max_length=17,  # Max length changed
            ),
        ),
        migrations.AlterField(
            model_name="reservationunitaccesstype",
            name="access_type",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("ACCESS_CODE", "access code"),
                    ("OPENED_BY_STAFF", "opened by staff"),
                    ("PHYSICAL_KEY", "physical key"),
                    ("UNRESTRICTED", "unrestricted"),
                ],
                choices_enum=tilavarauspalvelu.enums.AccessType,
                default="UNRESTRICTED",
                max_length=15,  # Max length changed
            ),
        ),
        migrations.AlterField(
            model_name="reservationunitimage",
            name="image_type",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("main", "Main image"),
                    ("other", "Other"),
                ],
                choices_enum=tilavarauspalvelu.enums.ReservationUnitImageType,
                max_length=5,  # Max length changed
            ),
        ),
        migrations.AlterField(
            model_name="reservationunitpricing",
            name="payment_type",
            field=utils.fields.model.TextChoicesField(
                blank=True,
                choices=[
                    ("ON_SITE", "On site"),
                    ("ONLINE", "Online"),
                    ("ONLINE_OR_INVOICE", "Online or invoice"),
                ],
                choices_enum=tilavarauspalvelu.enums.PaymentType,
                max_length=17,  # Max length changed
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservationunitpricing",
            name="price_unit",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("per_15_mins", "per 15 minutes"),
                    ("per_30_mins", "per 30 minutes"),
                    ("per_hour", "per hour"),
                    ("per_half_day", "per half a day"),
                    ("per_day", "per day"),
                    ("per_week", "per week"),
                    ("fixed", "fixed"),
                ],
                choices_enum=tilavarauspalvelu.enums.PriceUnit,
                default="per_hour",
                max_length=12,  # Max length changed
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="location_type",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("fixed", "Fixed"),
                    ("movable", "Movable"),
                ],
                choices_enum=tilavarauspalvelu.enums.ResourceLocationType,
                default="fixed",
                max_length=7,  # Max length changed
            ),
        ),
        migrations.AlterField(
            model_name="suitabletimerange",
            name="day_of_the_week",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("MONDAY", "Monday"),
                    ("TUESDAY", "Tuesday"),
                    ("WEDNESDAY", "Wednesday"),
                    ("THURSDAY", "Thursday"),
                    ("FRIDAY", "Friday"),
                    ("SATURDAY", "Saturday"),
                    ("SUNDAY", "Sunday"),
                ],
                choices_enum=tilavarauspalvelu.enums.Weekday,
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="suitabletimerange",
            name="priority",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("PRIMARY", "Primary"),
                    ("SECONDARY", "Secondary"),
                ],
                choices_enum=tilavarauspalvelu.enums.Priority,
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="termsofuse",
            name="terms_type",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("generic_terms", "Generic terms"),
                    ("payment_terms", "Payment terms"),
                    ("cancellation_terms", "Cancellation terms"),
                    ("recurring_terms", "Reservation series terms"),
                    ("service_terms", "Service-specific terms"),
                    ("pricing_terms", "Pricing terms"),
                ],
                choices_enum=tilavarauspalvelu.enums.TermsOfUseTypeChoices,
                default="generic_terms",
                max_length=18,  # Max length changed
            ),
        ),
        migrations.AlterField(
            model_name="unitrole",
            name="role",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("HANDLER", "Handler"),
                    ("VIEWER", "Viewer"),
                    ("RESERVER", "Reserver"),
                    ("NOTIFICATION_MANAGER", "Notification manager"),
                ],
                choices_enum=tilavarauspalvelu.enums.UserRoleChoice,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="preferred_language",
            field=utils.fields.model.TextChoicesField(
                blank=True,
                choices=[
                    ("fi", "Finnish"),
                    ("sv", "Swedish"),
                    ("en", "English"),
                ],
                choices_enum=tilavarauspalvelu.enums.Language,
                default="fi",
                max_length=2,  # Max length changed
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="reservation_notification",
            field=utils.fields.model.TextChoicesField(
                choices=[
                    ("all", "All"),
                    ("only_handling_required", "Only Handling Required"),
                    ("none", "None"),
                ],
                choices_enum=tilavarauspalvelu.enums.ReservationNotification,
                default="only_handling_required",
                max_length=22,  # Max length changed
            ),
        ),
        migrations.RunSQL(sql=create_affecting_reservations(), reverse_sql=None),
    ]
