# Generated by Django 5.1.11 on 2025-08-08 08:54

import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0151_alter_allocatedtimeslot_day_of_the_week_and_more"),
    ]

    operations = [
        # Set blank=True on a bunch of nullable fields so that `clean()` doesn't fail on them if null is given.
        migrations.AlterField(
            model_name="applicationround",
            name="terms_of_use",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="application_rounds",
                to="tilavarauspalvelu.termsofuse",
            ),
        ),
        migrations.AlterField(
            model_name="applicationsection",
            name="age_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="application_sections",
                to="tilavarauspalvelu.agegroup",
            ),
        ),
        migrations.AlterField(
            model_name="applicationsection",
            name="purpose",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="application_sections",
                to="tilavarauspalvelu.reservationpurpose",
            ),
        ),
        migrations.AlterField(
            model_name="paymentproduct",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="tilavarauspalvelu.paymentmerchant",
            ),
        ),
        migrations.AlterField(
            model_name="personalinfoviewlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personal_info_view_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="personalinfoviewlog",
            name="viewer_user",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="as_viewer_personal_info_view_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="purpose",
            name="image",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True, null=True, upload_to="reservation_unit_purpose_images"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),  # noqa: TID251
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="primary_unit_tprek_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="recurrence_begin_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="recurrence_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="reservation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservation_statistic",
                to="tilavarauspalvelu.reservation",
            ),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="reservation_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="reservation_created_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),  # noqa: TID251
        ),
        migrations.AlterField(
            model_name="reservationstatistic",
            name="reservation_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="reservationunitimage",
            name="image",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True, null=True, upload_to="reservation_unit_images"
            ),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="search_vector_en",
            field=django.contrib.postgres.search.SearchVectorField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="search_vector_fi",
            field=django.contrib.postgres.search.SearchVectorField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="search_vector_sv",
            field=django.contrib.postgres.search.SearchVectorField(blank=True, default=""),
        ),
    ]
