# Generated by Django 5.1.11 on 2025-09-03 12:12
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0152_set_blank_on_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_api_use",
            field=models.DateField(blank=True, null=True, verbose_name="Latest API token usage date"),
        ),
    ]
