# Generated by Django 5.1.11 on 2025-08-20 06:01
from __future__ import annotations

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models

import tilavarauspalvelu.validators
import utils.date_utils


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0152_set_blank_on_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.TextField()),
                (
                    "recipients",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        size=None,
                    ),
                ),
                ("text_content", models.TextField()),
                ("html_content", models.TextField()),
                (
                    "attachments",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.hstore.HStoreField(),
                        blank=True,
                        default=list,
                        size=None,
                        validators=[tilavarauspalvelu.validators.validate_email_attachments],
                    ),
                ),
                ("valid_until", models.DateTimeField(db_index=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=utils.date_utils.local_datetime,
                    ),
                ),
            ],
            options={
                "verbose_name": "email message",
                "verbose_name_plural": "email messages",
                "ordering": ["created_at"],
            },
        ),
    ]
