# Generated by Django 5.1.11 on 2025-09-03 11:42
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0153_emailmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationunitpricing",
            name="material_price_description",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="reservationunitpricing",
            name="material_price_description_en",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="reservationunitpricing",
            name="material_price_description_fi",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="reservationunitpricing",
            name="material_price_description_sv",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
