# Generated by Django 5.1.12 on 2025-09-17 14:44

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tilavarauspalvelu", "0155_user_last_api_use"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="space",
            managers=[
                ("_tree_manager", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
