# Generated by Django 5.1.12 on 2025-09-19 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0156_alter_space_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="reservee_address_city",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="reservee_address_street",
        ),
    ]
