# Generated by Django 5.1.12 on 2025-09-22 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0156_alter_space_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationround",
            name="terms_of_use",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("terms_type", "recurring_terms")),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="application_rounds",
                to="tilavarauspalvelu.termsofuse",
            ),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="cancellation_terms",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("terms_type", "cancellation_terms")),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancellation_terms_reservation_units",
                to="tilavarauspalvelu.termsofuse",
            ),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="payment_terms",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("terms_type", "payment_terms")),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_terms_reservation_units",
                to="tilavarauspalvelu.termsofuse",
            ),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="pricing_terms",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("terms_type", "pricing_terms")),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pricing_terms_reservation_units",
                to="tilavarauspalvelu.termsofuse",
            ),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="service_specific_terms",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("terms_type", "service_terms")),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_specific_terms_reservation_units",
                to="tilavarauspalvelu.termsofuse",
            ),
        ),
    ]
