# Generated by Django 5.1.11 on 2025-09-03 11:07
from __future__ import annotations

import django.core.validators
from django.db import migrations, models

import tilavarauspalvelu.validators


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0156_alter_space_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentaccounting",
            name="balance_profit_center",
            field=models.CharField(max_length=10, validators=[tilavarauspalvelu.validators.is_numeric]),
        ),
        migrations.AlterField(
            model_name="paymentaccounting",
            name="product_invoicing_material",
            field=models.CharField(
                blank=True,
                default="",
                max_length=8,
                validators=[django.core.validators.MinLengthValidator(8), tilavarauspalvelu.validators.is_numeric],
            ),
        ),
        migrations.AlterField(
            model_name="paymentaccounting",
            name="product_invoicing_order_type",
            field=models.CharField(
                blank=True, default="", max_length=4, validators=[django.core.validators.MinLengthValidator(4)]
            ),
        ),
        migrations.AlterField(
            model_name="paymentaccounting",
            name="product_invoicing_sales_office",
            field=models.CharField(
                blank=True,
                default="",
                max_length=4,
                validators=[django.core.validators.MinLengthValidator(4), tilavarauspalvelu.validators.is_numeric],
            ),
        ),
        migrations.AlterField(
            model_name="paymentaccounting",
            name="product_invoicing_sales_org",
            field=models.CharField(
                blank=True,
                default="",
                max_length=4,
                validators=[django.core.validators.MinLengthValidator(4), tilavarauspalvelu.validators.is_numeric],
            ),
        ),
        migrations.AlterField(
            model_name="paymentaccounting",
            name="vat_code",
            field=models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AddConstraint(
            model_name="paymentaccounting",
            constraint=models.CheckConstraint(
                condition=models.Q(("profit_center", ""), ("internal_order", ""), _connector="OR"),
                name="either_internal_order_or_profit_center",
                violation_error_message="Can fill either 'internal_order' or 'profit_center'",
            ),
        ),
    ]
