# Generated by Django 5.1.12 on 2025-09-23 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0156_alter_space_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxpercentage",
            name="is_enabled",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="reservationunitpricing",
            name="tax_percentage",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("is_enabled", True)),
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservation_unit_pricings",
                to="tilavarauspalvelu.taxpercentage",
            ),
        ),
    ]
