# Generated by Django 5.1.12 on 2025-09-15 09:42

import undine.utils.model_fields
from django.db import migrations

import tilavarauspalvelu.enums


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0156_alter_space_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationunit",
            name="new_authentication",
            field=undine.utils.model_fields.TextChoicesField(
                choices=[
                    ("WEAK", "Weak"),
                    ("STRONG", "Strong"),
                ],
                choices_enum=tilavarauspalvelu.enums.AuthenticationType,
                default="WEAK",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="reservationunit",
            name="new_reservation_start_interval",
            field=undine.utils.model_fields.TextChoicesField(
                choices=[
                    ("INTERVAL_15_MINUTES", "15 minutes"),
                    ("INTERVAL_30_MINUTES", "30 minutes"),
                    ("INTERVAL_60_MINUTES", "60 minutes"),
                    ("INTERVAL_90_MINUTES", "90 minutes"),
                    ("INTERVAL_120_MINUTES", "2 hours"),
                    ("INTERVAL_180_MINUTES", "3 hours"),
                    ("INTERVAL_240_MINUTES", "4 hours"),
                    ("INTERVAL_300_MINUTES", "5 hours"),
                    ("INTERVAL_360_MINUTES", "6 hours"),
                    ("INTERVAL_420_MINUTES", "7 hours"),
                ],
                choices_enum=tilavarauspalvelu.enums.ReservationStartInterval,
                default="INTERVAL_15_MINUTES",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="reservationunitpricing",
            name="new_price_unit",
            field=undine.utils.model_fields.TextChoicesField(
                choices=[
                    ("PER_15_MINS", "per 15 minutes"),
                    ("PER_30_MINS", "per 30 minutes"),
                    ("PER_HOUR", "per hour"),
                    ("PER_HALF_DAY", "per half a day"),
                    ("PER_DAY", "per day"),
                    ("PER_WEEK", "per week"),
                    ("FIXED", "fixed"),
                ],
                choices_enum=tilavarauspalvelu.enums.PriceUnit,
                default="PER_HOUR",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="new_location_type",
            field=undine.utils.model_fields.TextChoicesField(
                choices=[
                    ("FIXED", "Fixed"),
                    ("MOVABLE", "Movable"),
                ],
                choices_enum=tilavarauspalvelu.enums.ResourceLocationType,
                default="FIXED",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="termsofuse",
            name="new_terms_type",
            field=undine.utils.model_fields.TextChoicesField(
                choices=[
                    ("GENERIC", "Generic terms"),
                    ("PAYMENT", "Payment terms"),
                    ("CANCELLATION", "Cancellation terms"),
                    ("RECURRING", "Reservation series terms"),
                    ("SERVICE", "Service-specific terms"),
                    ("PRICING", "Pricing terms"),
                ],
                choices_enum=tilavarauspalvelu.enums.TermsOfUseTypeChoices,
                default="GENERIC",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="new_reservation_notification",
            field=undine.utils.model_fields.TextChoicesField(
                choices=[
                    ("ALL", "All"),
                    ("ONLY_HANDLING_REQUIRED", "Only Handling Required"),
                    ("NONE", "None"),
                ],
                choices_enum=tilavarauspalvelu.enums.ReservationNotification,
                default="ONLY_HANDLING_REQUIRED",
                max_length=22,
            ),
        ),
    ]
