# Generated by Django 5.1.12 on 2025-09-19 11:09
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0159_migrate_metadata_to_forms"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Purpose",
            new_name="IntendedUse",
        ),
        migrations.AlterModelOptions(
            name="intendeduse",
            options={
                "base_manager_name": "objects",
                "ordering": ["rank"],
                "verbose_name": "intended use",
                "verbose_name_plural": "intended uses",
            },
        ),
        migrations.RenameField(
            model_name="reservationunit",
            old_name="purposes",
            new_name="intended_uses",
        ),
        migrations.AlterModelTable(
            name="intendeduse",
            table="intended_use",
        ),
    ]
