# Generated by Django 5.1.12 on 2025-09-19 12:29
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0160_rename_purpose_to_intended_use"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="reservee_address_city",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="reservee_address_street",
        ),
    ]
