# Generated by Django 5.1.12 on 2025-09-15 09:42
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0163_migrate_enums"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservationunit",
            name="authentication",
        ),
        migrations.RemoveField(
            model_name="reservationunit",
            name="reservation_start_interval",
        ),
        migrations.RemoveField(
            model_name="reservationunitpricing",
            name="price_unit",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="location_type",
        ),
        migrations.RemoveField(
            model_name="termsofuse",
            name="terms_type",
        ),
        migrations.RemoveField(
            model_name="user",
            name="reservation_notification",
        ),
    ]
