# Generated by Django 5.1.12 on 2025-09-15 09:42
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0164_remove_old_enums"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservationunit",
            old_name="new_authentication",
            new_name="authentication",
        ),
        migrations.RenameField(
            model_name="reservationunit",
            old_name="new_reservation_start_interval",
            new_name="reservation_start_interval",
        ),
        migrations.RenameField(
            model_name="reservationunitpricing",
            old_name="new_price_unit",
            new_name="price_unit",
        ),
        migrations.RenameField(
            model_name="resource",
            old_name="new_location_type",
            new_name="location_type",
        ),
        migrations.RenameField(
            model_name="termsofuse",
            old_name="new_terms_type",
            new_name="terms_type",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="new_reservation_notification",
            new_name="reservation_notification",
        ),
    ]
