# Generated by Django 5.1.13 on 2025-10-29 15:57
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0166_taxpercentage_is_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationround",
            name="terms_of_use",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("terms_type", "RECURRING")),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="application_rounds",
                to="tilavarauspalvelu.termsofuse",
            ),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="cancellation_terms",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("terms_type", "CANCELLATION")),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancellation_terms_reservation_units",
                to="tilavarauspalvelu.termsofuse",
            ),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="payment_terms",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("terms_type", "PAYMENT")),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_terms_reservation_units",
                to="tilavarauspalvelu.termsofuse",
            ),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="pricing_terms",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("terms_type", "PRICING")),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pricing_terms_reservation_units",
                to="tilavarauspalvelu.termsofuse",
            ),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="service_specific_terms",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("terms_type", "SERVICE")),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_specific_terms_reservation_units",
                to="tilavarauspalvelu.termsofuse",
            ),
        ),
    ]
