# Generated by Django 5.1.12 on 2025-09-19 07:26
from __future__ import annotations

import django_nh3.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0167_terms_of_use_limit_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="additional_information",
            field=django_nh3.models.Nh3Field(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="application",
            name="billing_city",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="application",
            name="billing_street_address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="application",
            name="organisation_city",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="application",
            name="organisation_core_business",
            field=django_nh3.models.Nh3Field(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="application",
            name="organisation_street_address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="application",
            name="working_memo",
            field=django_nh3.models.Nh3Field(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="applicationround",
            name="criteria",
            field=django_nh3.models.Nh3Field(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="applicationround",
            name="criteria_en",
            field=django_nh3.models.Nh3Field(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="applicationround",
            name="criteria_fi",
            field=django_nh3.models.Nh3Field(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="applicationround",
            name="criteria_sv",
            field=django_nh3.models.Nh3Field(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="applicationround",
            name="notes_when_applying",
            field=django_nh3.models.Nh3Field(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="applicationround",
            name="notes_when_applying_en",
            field=django_nh3.models.Nh3Field(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="applicationround",
            name="notes_when_applying_fi",
            field=django_nh3.models.Nh3Field(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="applicationround",
            name="notes_when_applying_sv",
            field=django_nh3.models.Nh3Field(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="bannernotification",
            name="message",
            field=django_nh3.models.Nh3Field(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="bannernotification",
            name="message_en",
            field=django_nh3.models.Nh3Field(blank=True, default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="bannernotification",
            name="message_fi",
            field=django_nh3.models.Nh3Field(blank=True, default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="bannernotification",
            name="message_sv",
            field=django_nh3.models.Nh3Field(blank=True, default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="cancel_details",
            field=django_nh3.models.Nh3Field(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="free_of_charge_reason",
            field=django_nh3.models.Nh3Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="handling_details",
            field=django_nh3.models.Nh3Field(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="working_memo",
            field=django_nh3.models.Nh3Field(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="contact_information",
            field=django_nh3.models.Nh3Field(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="description",
            field=django_nh3.models.Nh3Field(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="description_en",
            field=django_nh3.models.Nh3Field(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="description_fi",
            field=django_nh3.models.Nh3Field(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="description_sv",
            field=django_nh3.models.Nh3Field(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="notes_when_applying",
            field=django_nh3.models.Nh3Field(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="notes_when_applying_en",
            field=django_nh3.models.Nh3Field(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="notes_when_applying_fi",
            field=django_nh3.models.Nh3Field(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="notes_when_applying_sv",
            field=django_nh3.models.Nh3Field(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="reservation_cancelled_instructions",
            field=django_nh3.models.Nh3Field(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="reservation_cancelled_instructions_en",
            field=django_nh3.models.Nh3Field(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="reservation_cancelled_instructions_fi",
            field=django_nh3.models.Nh3Field(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="reservation_cancelled_instructions_sv",
            field=django_nh3.models.Nh3Field(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="reservation_confirmed_instructions",
            field=django_nh3.models.Nh3Field(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="reservation_confirmed_instructions_en",
            field=django_nh3.models.Nh3Field(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="reservation_confirmed_instructions_fi",
            field=django_nh3.models.Nh3Field(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="reservation_confirmed_instructions_sv",
            field=django_nh3.models.Nh3Field(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="reservation_pending_instructions",
            field=django_nh3.models.Nh3Field(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="reservation_pending_instructions_en",
            field=django_nh3.models.Nh3Field(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="reservation_pending_instructions_fi",
            field=django_nh3.models.Nh3Field(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="reservationunit",
            name="reservation_pending_instructions_sv",
            field=django_nh3.models.Nh3Field(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="termsofuse",
            name="text",
            field=django_nh3.models.Nh3Field(),
        ),
        migrations.AlterField(
            model_name="termsofuse",
            name="text_en",
            field=django_nh3.models.Nh3Field(null=True),
        ),
        migrations.AlterField(
            model_name="termsofuse",
            name="text_fi",
            field=django_nh3.models.Nh3Field(null=True),
        ),
        migrations.AlterField(
            model_name="termsofuse",
            name="text_sv",
            field=django_nh3.models.Nh3Field(null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="description",
            field=django_nh3.models.Nh3Field(blank=True, default="", max_length=4000),
        ),
        migrations.AlterField(
            model_name="unit",
            name="description_en",
            field=django_nh3.models.Nh3Field(blank=True, default="", max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="description_fi",
            field=django_nh3.models.Nh3Field(blank=True, default="", max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="description_sv",
            field=django_nh3.models.Nh3Field(blank=True, default="", max_length=4000, null=True),
        ),
    ]
