# Generated by Django 5.1.13 on 2025-10-29 16:01

import django_nh3.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tilavarauspalvelu', '0168_use_nh3_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationunitpricing',
            name='material_price_description',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='reservationunitpricing',
            name='material_price_description_en',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reservationunitpricing',
            name='material_price_description_fi',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reservationunitpricing',
            name='material_price_description_sv',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=500, null=True),
        ),
    ]
