# Generated by Django 5.1.11 on 2025-11-11 11:11
from __future__ import annotations

from typing import Any
from unittest.mock import patch

from django.db import migrations, models


def to_python(value) -> Any:
    return value


# Must patch the 'TextChoicesField' so that it doesn't try to convert string from db to an enum.
# This would fail, since the enum values have changed.
@patch("utils.fields.model.TextChoicesField.to_python", side_effect=to_python)
def migrate_enums(apps, schema_editor, _patch):
    ReservationUnitImage = apps.get_model("tilavarauspalvelu", "ReservationUnitImage")

    ReservationUnitImage.objects.update(
        image_type=models.Case(
            models.When(image_type="main", then=models.Value("MAIN")),
            models.When(image_type="other", then=models.Value("OTHER")),
            default=models.Value("main"),
            output_field=models.CharField(),
        ),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0169_material_price_description_nh3"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_enums,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
