# Generated by Django 5.1.14 on 2025-11-13 16:03

import django_nh3.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tilavarauspalvelu', '0170_migrate_image_type_enum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationunit',
            name='contact_information',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='description',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=8000),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='description_en',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='description_fi',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='description_sv',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='notes_when_applying',
            field=django_nh3.models.Nh3Field(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='notes_when_applying_en',
            field=django_nh3.models.Nh3Field(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='notes_when_applying_fi',
            field=django_nh3.models.Nh3Field(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='notes_when_applying_sv',
            field=django_nh3.models.Nh3Field(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='reservation_cancelled_instructions',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=8000),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='reservation_cancelled_instructions_en',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='reservation_cancelled_instructions_fi',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='reservation_cancelled_instructions_sv',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='reservation_confirmed_instructions',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=8000),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='reservation_confirmed_instructions_en',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='reservation_confirmed_instructions_fi',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='reservation_confirmed_instructions_sv',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='reservation_pending_instructions',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=8000),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='reservation_pending_instructions_en',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='reservation_pending_instructions_fi',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='reservationunit',
            name='reservation_pending_instructions_sv',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='reservationunitpricing',
            name='material_price_description',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='reservationunitpricing',
            name='material_price_description_en',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reservationunitpricing',
            name='material_price_description_fi',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reservationunitpricing',
            name='material_price_description_sv',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=8000),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description_en',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description_fi',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description_sv',
            field=django_nh3.models.Nh3Field(blank=True, default='', max_length=8000, null=True),
        ),
    ]
