# Generated by Django 5.2.8 on 2025-12-02 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tilavarauspalvelu', '0173_fix_affecting_reservations_now_tt_split'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationmetadataset',
            name='required_fields',
        ),
        migrations.RemoveField(
            model_name='reservationmetadataset',
            name='supported_fields',
        ),
        migrations.RemoveField(
            model_name='reservationunit',
            name='metadata_set',
        ),
        migrations.DeleteModel(
            name='ReservationMetadataField',
        ),
        migrations.DeleteModel(
            name='ReservationMetadataSet',
        ),
    ]
