# Generated by Django 5.2.8 on 2025-12-02 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tilavarauspalvelu', '0174_remove_reservation_metadata_field_and_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationunit',
            name='allow_reservations_without_opening_hours',
        ),
    ]
