# Generated by Django 5.2.17 on 2026-10-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0175_remove_allow_reservations_without_opening_hours"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="suitabletimerange",
            name="begin_and_end_time_multiple_of_60_minutes_suitable",
        ),
        migrations.AddConstraint(
            model_name="suitabletimerange",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("begin_time__minute__in", [0, 15, 30, 45]), ("end_time__minute__in", [0, 15, 30, 45])
                ),
                name="begin_and_end_time_multiple_of_15_minutes_suitable",
                violation_error_message="Begin and end times must be multiples of 15 minutes.",
            ),
        ),
    ]
