# Generated by Django 5.2.17 on 2026-10-08 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tilavarauspalvelu", "0175_remove_allow_reservations_without_opening_hours"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="applicationsection",
            name="durations_multiple_of_30_minutes_max_24_hours",
        ),
        migrations.RemoveConstraint(
            model_name="suitabletimerange",
            name="begin_and_end_time_multiple_of_60_minutes_suitable",
        ),
        migrations.AddConstraint(
            model_name="applicationsection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "reservation_max_duration__in",
                        [datetime.timedelta(minutes=minutes) for minutes in range(15, 1441, 15)],
                    ),
                    (
                        "reservation_min_duration__in",
                        [datetime.timedelta(minutes=minutes) for minutes in range(15, 1441, 15)],
                    ),
                ),
                name="durations_multiple_of_15_minutes_max_24_hours",
                violation_error_message=(
                    "Reservation min and max durations must be multiples of 15 minutes, up to a maximum of 24 hours."
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="suitabletimerange",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("begin_time__minute__in", [0, 15, 30, 45]), ("end_time__minute__in", [0, 15, 30, 45])
                ),
                name="begin_and_end_time_multiple_of_15_minutes_suitable",
                violation_error_message="Begin and end times must be multiples of 15 minutes.",
            ),
        ),
    ]
