from __future__ import annotations

from .reservation import (
    get_context_for_reservation_access_code_changed,
    get_context_for_reservation_access_type_changed,
    get_context_for_reservation_approved,
    get_context_for_reservation_cancelled,
    get_context_for_reservation_confirmed,
    get_context_for_reservation_confirmed_staff_notification,
    get_context_for_reservation_denied,
    get_context_for_reservation_requires_handling,
    get_context_for_reservation_requires_handling_staff_notification,
    get_context_for_reservation_requires_payment,
    get_context_for_reservation_rescheduled,
)
from .seasonal_bookings import (
    get_context_for_seasonal_booking_access_code_changed,
    get_context_for_seasonal_booking_access_type_changed,
    get_context_for_seasonal_booking_application_received,
    get_context_for_seasonal_booking_application_round_handled,
    get_context_for_seasonal_booking_application_round_in_allocation,
    get_context_for_seasonal_booking_cancelled_all,
    get_context_for_seasonal_booking_cancelled_all_staff_notification,
    get_context_for_seasonal_booking_cancelled_single,
    get_context_for_seasonal_booking_denied_series,
    get_context_for_seasonal_booking_denied_single,
    get_context_for_seasonal_booking_rescheduled_series,
    get_context_for_seasonal_booking_rescheduled_single,
)
from .user import get_context_for_user_anonymization, get_context_for_user_permissions_deactivation

__all__ = [
    "get_context_for_reservation_access_code_changed",
    "get_context_for_reservation_access_type_changed",
    "get_context_for_reservation_approved",
    "get_context_for_reservation_cancelled",
    "get_context_for_reservation_confirmed",
    "get_context_for_reservation_confirmed_staff_notification",
    "get_context_for_reservation_denied",
    "get_context_for_reservation_requires_handling",
    "get_context_for_reservation_requires_handling_staff_notification",
    "get_context_for_reservation_requires_payment",
    "get_context_for_reservation_rescheduled",
    "get_context_for_seasonal_booking_access_code_changed",
    "get_context_for_seasonal_booking_access_type_changed",
    "get_context_for_seasonal_booking_application_received",
    "get_context_for_seasonal_booking_application_round_handled",
    "get_context_for_seasonal_booking_application_round_in_allocation",
    "get_context_for_seasonal_booking_cancelled_all",
    "get_context_for_seasonal_booking_cancelled_all_staff_notification",
    "get_context_for_seasonal_booking_cancelled_single",
    "get_context_for_seasonal_booking_denied_series",
    "get_context_for_seasonal_booking_denied_single",
    "get_context_for_seasonal_booking_rescheduled_series",
    "get_context_for_seasonal_booking_rescheduled_single",
    "get_context_for_user_anonymization",
    "get_context_for_user_permissions_deactivation",
]
