# Generated by Django 3.2.12 on 2022-02-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reservation_confirmed', 'Reservation Confirmed'), ('reservation_with_pin_confirmed', 'Reservation With Pin Confirmed'), ('handling_required_reservation', 'Handling Required Reservation'), ('reservation_handled_and_confirmed', 'Reservation Handled And Confirmed'), ('reservation_modified', 'Reservation Modified'), ('reservation_rejected', 'Reservation Rejected'), ('reservation_cancelled', 'Reservation Cancelled'), ('access_code_for_reservation', 'Access Code For Reservation'), ('reservation_needs_to_be_paid', 'Reservation Needs To Be Paid')], help_text='Only one template per type can be created.', max_length=254, unique=True, verbose_name='Email type')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Unique name for this content')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Email body content. Use curly brackets to indicate data specific fields e.g {{reservee_name}}.', verbose_name='Content')),
            ],
        ),
    ]
