# Generated by Django 3.2.15 on 2022-08-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_notification', '0002_content_and_subject_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='type',
            field=models.CharField(choices=[('reservation_confirmed', 'Reservation Confirmed'), ('reservation_with_pin_confirmed', 'Reservation With Pin Confirmed'), ('handling_required_reservation', 'Handling Required Reservation'), ('reservation_handled_and_confirmed', 'Reservation Handled And Confirmed'), ('reservation_modified', 'Reservation Modified'), ('reservation_rejected', 'Reservation Rejected'), ('reservation_cancelled', 'Reservation Cancelled'), ('access_code_for_reservation', 'Access Code For Reservation'), ('reservation_needs_to_be_paid', 'Reservation Needs To Be Paid'), ('staff_notification_reservation_requires_handling', 'Staff Notification Reservation Requires Handling'), ('staff_notification_reservation_made', 'Staff Notification Reservation Made')], help_text='Only one template per type can be created.', max_length=254, unique=True, verbose_name='Email type'),
        ),
    ]
