# Generated by Django 3.2.16 on 2022-12-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_notification', '0003_alter_emailtemplate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='html_content',
            field=models.FileField(blank=True, help_text='Email body content as HTML. Use curly brackets to indicate data specific fields e.g {{reservee_name}}.', null=True, upload_to='email_html_templates', verbose_name='HTML content'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_content_en',
            field=models.FileField(blank=True, help_text='Email body content as HTML. Use curly brackets to indicate data specific fields e.g {{reservee_name}}.', null=True, upload_to='email_html_templates', verbose_name='HTML content'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_content_fi',
            field=models.FileField(blank=True, help_text='Email body content as HTML. Use curly brackets to indicate data specific fields e.g {{reservee_name}}.', null=True, upload_to='email_html_templates', verbose_name='HTML content'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_content_sv',
            field=models.FileField(blank=True, help_text='Email body content as HTML. Use curly brackets to indicate data specific fields e.g {{reservee_name}}.', null=True, upload_to='email_html_templates', verbose_name='HTML content'),
        ),
    ]
