# Generated by Django 4.2.9 on 2024-01-23 07:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("email_notification", "0004_add_html_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailtemplate",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelTable(
            name="emailtemplate",
            table="email_template",
        ),
    ]
