# Generated by Django 4.2.9 on 2024-01-23 07:12

from django.db import migrations

from utils.migration import AlterModelTable


class Migration(migrations.Migration):
    dependencies = [
        ("email_notification", "0005_add_base_manager_name_to_all_models"),
    ]

    operations = [
        AlterModelTable(
            name="emailtemplate",
            table="email_template",
        ),
    ]
