# Generated by Django 5.0.3 on 2024-03-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email_notification", "0006_change_database_table_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("access_code_for_reservation", "Access Code For Reservation"),
                    ("application_handled", "Application Handled"),
                    ("application_in_handling", "Application In Handling"),
                    ("application_received", "Application Received"),
                    ("handling_required_reservation", "Handling Required Reservation"),
                    ("reservation_cancelled", "Reservation Cancelled"),
                    ("reservation_confirmed", "Reservation Confirmed"),
                    (
                        "reservation_handled_and_confirmed",
                        "Reservation Handled And Confirmed",
                    ),
                    ("reservation_modified", "Reservation Modified"),
                    ("reservation_needs_to_be_paid", "Reservation Needs To Be Paid"),
                    ("reservation_rejected", "Reservation Rejected"),
                    (
                        "reservation_with_pin_confirmed",
                        "Reservation With Pin Confirmed",
                    ),
                    (
                        "staff_notification_reservation_made",
                        "Staff Notification Reservation Made",
                    ),
                    (
                        "staff_notification_reservation_requires_handling",
                        "Staff Notification Reservation Requires Handling",
                    ),
                ],
                help_text="Only one template per type can be created.",
                max_length=254,
                unique=True,
                verbose_name="Email type",
            ),
        ),
    ]
