# Generated by Django 5.0.4 on 2024-04-08 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("email_notification", "0007_email_template_Types"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailtemplate",
            options={"base_manager_name": "objects", "ordering": ["pk"]},
        ),
    ]
