# Generated by Django 5.1.1 on 2024-09-19 07:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("email_notification", "0009_rename_in_handling_to_in_allocation"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="EmailTemplate",
                ),
            ],
            database_operations=[],
        ),
    ]
