# Generated by Django 3.0.10 on 2020-12-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='resource',
            name='name_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='resource',
            name='name_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
