# Generated by Django 3.0.10 on 2020-11-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedresource",
            name="buffer_time_after",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Buffer time after"
            ),
        ),
        migrations.AddField(
            model_name="fixedresource",
            name="buffer_time_before",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Buffer time before"
            ),
        ),
        migrations.AddField(
            model_name="movableresource",
            name="buffer_time_after",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Buffer time after"
            ),
        ),
        migrations.AddField(
            model_name="movableresource",
            name="buffer_time_before",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Buffer time before"
            ),
        ),
    ]
