# Generated by Django 3.1.13 on 2021-09-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resources_modeltranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is the resource in draft state (=not publish ready).'),
        ),
    ]
