# Generated by Django 3.1.13 on 2021-09-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(default='', verbose_name='Description for the resource'),
        ),
    ]
