# Generated by Django 3.1.13 on 2021-09-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resource_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description_en',
            field=models.TextField(default='', null=True, verbose_name='Description for the resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='description_fi',
            field=models.TextField(default='', null=True, verbose_name='Description for the resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='description_sv',
            field=models.TextField(default='', null=True, verbose_name='Description for the resource'),
        ),
    ]
