# Generated by Django 3.2.13 on 2022-06-15 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_resource_description_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='is_draft',
        ),
    ]
