# Generated by Django 4.2.9 on 2024-01-23 07:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0008_add_base_manager_name_to_all_models"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="resource",
            table="resource",
        ),
    ]
