# Generated by Django 5.1.1 on 2024-09-19 04:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservation_units", "0107_alter_reservationunit_payment_accounting_and_more"),
        ("resources", "0010_alter_resource_options"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Resource",
                ),
            ],
            database_operations=[],
        ),
    ]
