name: Auto approve PRs by bots

on:
  # Trigger when any action on a pull request is taken.
  pull_request_target:

env:
  # PRs created by these bots are auto approved and merged if tests pass.
  bots: '["dependabot[bot]", "pre-commit-ci[bot]"]'

jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # allows approving the PR
      contents: write  # allows merging the PR

    # Only run if one of the selected authors is the pull request author.
    if: contains(fromJSON(env.bots), github.event.pull_request.user.login)

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: "Approve a pull request and set to auto rebase-merge if tests pass"
        # Only approve the PR if it's not already approved to avoid email spam.
        run: |
          gh pr checkout "$PR_URL"
          if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ];
          then gh pr review --approve "$PR_URL"
          else echo "PR already approved.";
          fi
          gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
