name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11
      - name: Install flake8
        run: |
          pip install flake8
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --show-source --statistics
          flake8 . --count --exit-zero --statistics
  Format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11
      - name: Install black and isort
        run: |
          pip install isort==5.6.4
          pip install black==22.12.0
          # Needs to be pinned for black to work
          pip install click==8.1.3
      - name: Check format with black and isort
        run: |
          black --check --config black.toml .
          isort --check-only .
  Vulnerabilities-and-Safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python-env
      - name: Install safety and bandit
        run: |
          pip install safety
          pip install bandit
      - name: Check safety
        run: |
          bandit -a vuln --exclude "tests" -r .
          safety check --full-report
  Unit-Tests-and-SonarCloud:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:13-3.3-alpine
        env:
          POSTGRES_USER: tvp
          POSTGRES_PASSWORD: tvp
          POSTGRES_DB: tvp
          DEBUG: true
          SECRET_KEY: build_secret
        ports:
          - 5432:5432
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
        env:
          xpack.security.enabled: false
          discovery.type: single-node
        ports:
          - 9200:9200
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-python-env
      - name: Run pytest with coverage
        run: |
          pytest --cov=./ --cov-report=xml --cov-branch
        env:
          DATABASE_URL: postgis://tvp:tvp@localhost/tvp
          CACHE_LOCATION: redis://localhost:6379/0
          DEBUG: true
          SECRET_KEY: build_secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # Without this workaround Sonar reports a warning about an incorrect source path; credits to linked-events
      - name: Override coverage report source path for Sonar
        run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage.xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
