name: "Build frontend docker images"

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types:
      - fast-forward

# Cancel a workflow from the same PR, branch or tag when a new workflow is triggered.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # Build both ui and admin-ui dockers
  build-ui-docker:
    name: "Build ui docker"
    uses: ./.github/workflows/build-ui-docker.yml
    with:
      app-name: "customer"
      base-url: ""
    secrets: inherit

  build-admin-ui-docker:
    name: "Build admin ui docker"
    uses: ./.github/workflows/build-ui-docker.yml
    with:
      app-name: "staff"
      base-url: "/kasittely"
    secrets: inherit
