# Generic workflow to build a frontend application and push it to the GitHub Container Registry.
name: "Build docker"

on:
  workflow_call:
    inputs:
      # Docker build arg / package name suffix: valid values are "admin-ui" or "ui"
      app-name:
        required: true
        type: string
      # Root url for the application relative to hostname
      base-url:
        required: true
        type: string

env:
  SKIP_ENV_VALIDATION: "true"
  REGISTRY: "ghcr.io"

jobs:
  build-and-push:
    name: "Build and push Docker images to GitHub Packages"
    runs-on: ubuntu-latest
    env:
      BUILD_APP: ${{ inputs.app-name }}
      # Relative location for the package registry
      REPO_NAME: ${{ github.repository }}
      # Have to be build variable
      NEXT_PUBLIC_BASE_URL: ${{ inputs.base-url }}
      # required because error pages use build time env vars, not runtime env vars
      # it's the same on every environment
      EMAIL_VARAAMO_EXT_LINK: "https://lomake.hel.fi/varaamo-palaute"

    permissions:
      contents: read
      packages: write

    steps:
    - name: "Checkout code"
      uses: actions/checkout@v4

    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@v3

    - name: "Log in to the Container registry"
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Repository name needs to be lowercase
    - name: "Create repository name"
      id: repo
      run: >-
        echo "repo=$(
          echo ${{ env.REGISTRY }}/${{ env.REPO_NAME }}-${{ env.BUILD_APP }} | tr '[:upper:]' '[:lower:]'
        )" >> $GITHUB_OUTPUT

    - name: "Extract ui metadata (tags, labels) for Docker"
      id: meta
      uses: docker/metadata-action@v5
      env:
        DOCKER_METADATA_PR_HEAD_SHA: true
      with:
        images: ${{ steps.repo.outputs.repo }}
        tags: |
          type=ref,event=tag,priority=3
          type=sha,prefix=,priority=2
          type=ref,event=branch,priority=1
        labels: |
          org.opencontainers.image.title=Tilavarauspalvelu ${{ env.BUILD_APP }}
          org.opencontainers.image.description=Tilavarauspalvelu ${{ env.BUILD_APP }} ${{ github.ref_name }}.
          org.opencontainers.image.version=${{ github.ref_name }}

    - name: "Build container"
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        build-args: |
          APP=${{ env.BUILD_APP }}
          NEXT_PUBLIC_BASE_URL=${{ env.NEXT_PUBLIC_BASE_URL }}
          EMAIL_VARAAMO_EXT_LINK=${{ env.EMAIL_VARAAMO_EXT_LINK }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        annotations: ${{ steps.meta.outputs.annotations }}
        # Use a shared cache to speed up builds
        cache-from: type=registry,ref=${{ steps.repo.outputs.repo }}:cache
        cache-to: type=registry,ref=${{ steps.repo.outputs.repo }}:cache,mode=max
