name: common-style-test

defaults:
  run:
    working-directory: common
on:
  push:
    branches: [main]
    paths:
      - "common/**"
      - "yarn.lock"
      - ".github/workflows/common-style-test.yml"
  pull_request:
    paths:
      - "common/**"
      - "yarn.lock"
      - ".github/workflows/common-style-test.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run style checks and tests
        run: |
          yarn install --frozen-lockfile
          yarn lint
