name: PR Labeler

on:
  pull_request:
    types:
      - opened

permissions:
  contents: read

jobs:
  pr-labeler:

    permissions:
      contents: read  # Required to read config file.
      pull-requests: write  # Required to add labels in PR.

    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
