name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:11-2.5
        env:
          POSTGRES_USER: tvp
          POSTGRES_PASSWORD: tvp
          POSTGRES_DB: tvp
          DEBUG: true
          SECRET_KEY: build_secret
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: psycopg2 prerequisites
        run: |
          sudo apt update
          sudo apt install python-dev libpq-dev gdal-bin -y
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit
          pip install safety
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --show-source --statistics
          flake8 . --count --exit-zero --statistics
      - name: Check format
        run: |
          black --check --config black.toml .
          isort --check-only .
      - name: bandit check
        run : |
          bandit -a vuln --exclude "tests" -r .
      - name: Safety check
        run : |
          safety check --full-report
      - name: Test with pytest
        env:
          DATABASE_URL: postgis://tvp:tvp@localhost/tvp
          DEBUG: true
          SECRET_KEY: build_secret
        run: |
          pytest
