name: style-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js lts/fermium (14)
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Run style checks and client tests
        run: |
          yarn install --frozen-lockfile
          yarn lint
          yarn build
          yarn test
