name: ui-style-test

defaults:
  run:
    working-directory: ui
on:
  push:
    branches: [main]
    paths:
      - "ui/**"
      - "yarn.lock"
      - ".github/workflows/ui-style-test.yml"
  pull_request:
    branches: [main]
    paths:
      - "ui/**"
      - "yarn.lock"
      - ".github/workflows/ui-style-test.yml"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run lint and style checks
        run: |
          yarn install --frozen-lockfile
          yarn lint
          yarn lint:css
