import datetime
from typing import Any, Iterator, Iterable, Collection, Mapping, Sequence, Self, Generic, TypeVar

from django.db.models import Model, OrderBy, QuerySet
from django.db.models.manager import BaseManager
from django.db.models.sql import Query


TModel = TypeVar("TModel", bound=Model)
TQuerySet = TypeVar("TQuerySet", bound=QuerySet)


class ModelQuerySet(Generic[TModel], QuerySet[TModel]):
    """Simplified protocol of a model manager."""

    model: type[TModel]
    query: Query
    _hints: dict[str, Any]
    _result_cache: list[TModel] | None

    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[TModel]: ...
    def __bool__(self) -> bool: ...
    def __class_getitem__(cls, item: type[TModel]) -> Self: ...
    def __getstate__(self) -> dict[str, Any]: ...
    def __and__(self, other: Self) -> Self: ...
    def __or__(self, other: Self) -> Self: ...

    @classmethod
    def as_manager(cls) -> ModelManager[TModel, Self]: ...

    def _fetch_all(self) -> None: ...

    def iterator(self, chunk_size: int | None = ...) -> Iterator[TModel]: ...

    def aggregate(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

    def count(self) -> int: ...

    def get(self, *args: Any, **kwargs: Any) -> TModel: ...

    def create(self, **kwargs: Any) -> TModel: ...

    def bulk_create(
        self,
        objs: Iterable[TModel],
        batch_size: int | None = ...,
        ignore_conflicts: bool = ...,
        update_conflicts: bool = ...,
        update_fields: Collection[str] | None = ...,
        unique_fields: Collection[str] | None = ...,
    ) -> list[TModel]: ...

    def bulk_update(
        self,
        objs: Iterable[TModel],
        fields: Iterable[str],
        batch_size: int | None = ...,
    ) -> int: ...

    def get_or_create(
        self,
        defaults: Mapping[str, Any] | None = ...,
        **kwargs: Any,
    ) -> tuple[TModel, bool]: ...

    def update_or_create(
        self,
        defaults: Mapping[str, Any] | None = ...,
        create_defaults: Mapping[str, Any] | None = ...,
        **kwargs: Any,
    ) -> tuple[TModel, bool]: ...

    def earliest(self, *fields: str | OrderBy) -> TModel: ...

    def latest(self, *fields: str | OrderBy) -> TModel: ...

    def first(self) -> TModel | None: ...

    def last(self) -> TModel | None: ...

    def in_bulk(self, id_list: Iterable[Any] | None = ..., *, field_name: str = ...) -> dict[Any, TModel]: ...

    def delete(self) -> int: ...

    def update(self, **kwargs: Any) -> int: ...

    def exists(self) -> bool: ...

    def explain(self, *, format: Any | None = ..., **options: Any) -> str: ...

    def contains(self, obj: TModel) -> bool: ...

    def values(self, *fields: str, **expressions: Any) -> Self: ...

    def values_list(self, *fields: str, flat: bool = ..., named: bool = ...) -> Self: ...

    def dates(self, field_name: str, kind: str, order: str = ...) -> Self: ...

    def datetimes(
        self,
        field_name: str,
        kind: str,
        order: str = ...,
        tzinfo: datetime.tzinfo | None = ...,
    ) -> Self: ...

    def none(self) -> Self: ...

    def all(self) -> Self: ...

    def filter(self, *args: Any, **kwargs: Any) -> Self: ...

    def exclude(self, *args: Any, **kwargs: Any) -> Self: ...

    def complex_filter(self, filter_obj: Any) -> Self: ...

    def union(self, *other_qs: Self, all: bool = ...) -> Self: ...

    def intersection(self, *other_qs: Self) -> Self: ...

    def difference(self, *other_qs: Self) -> Self: ...

    def select_for_update(
        self,
        nowait: bool = ...,
        skip_locked: bool = ...,
        of: Sequence[str] = ...,
        no_key: bool = ...
    ) -> Self: ...

    def select_related(self, *fields: Any) -> Self: ...

    def prefetch_related(self, *lookups: Any) -> Self: ...

    def annotate(self, *args: Any, **kwargs: Any) -> Self: ...

    def alias(self, *args: Any, **kwargs: Any) -> Self: ...

    def order_by(self, *field_names: Any) -> Self: ...

    def distinct(self, *field_names: Any) -> Self: ...

    def reverse(self) -> Self: ...

    def defer(self, *fields: Any) -> Self: ...

    def only(self, *fields: Any) -> Self: ...

    def using(self, alias: str | None) -> Self: ...


class ModelManager(Generic[TModel, TQuerySet], BaseManager[TModel]):
    """Simplified protocol of a model manager."""

    model: type[TModel]
    name: str
    creation_counter: int
    auto_created: bool
    use_in_migrations: bool
    _queryset_class: type[TQuerySet]

    def __class_getitem__(cls, *args: Any, **kwargs: Any) -> type[Self]: ...

    def get_queryset(self) -> TQuerySet: ...

    def iterator(self, chunk_size: int | None = ...) -> Iterator[TModel]: ...

    def aggregate(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

    def count(self) -> int: ...

    def get(self, *args: Any, **kwargs: Any) -> TModel: ...

    def create(self, **kwargs: Any) -> TModel: ...

    def bulk_create(
        self,
        objs: Iterable[TModel],
        batch_size: int | None = ...,
        ignore_conflicts: bool = ...,
        update_conflicts: bool = ...,
        update_fields: Collection[str] | None = ...,
        unique_fields: Collection[str] | None = ...,
    ) -> list[TModel]: ...

    def bulk_update(
        self,
        objs: Iterable[TModel],
        fields: Iterable[str],
        batch_size: int | None = ...,
    ) -> int: ...

    def get_or_create(
        self,
        defaults: Mapping[str, Any] | None = ...,
        **kwargs: Any,
    ) -> tuple[TModel, bool]: ...

    def update_or_create(
        self,
        defaults: Mapping[str, Any] | None = ...,
        create_defaults: Mapping[str, Any] | None = ...,
        **kwargs: Any,
    ) -> tuple[TModel, bool]: ...

    def earliest(self, *fields: str | OrderBy) -> TModel: ...

    def latest(self, *fields: str | OrderBy) -> TModel: ...

    def first(self) -> TModel | None: ...

    def last(self) -> TModel | None: ...

    def in_bulk(self, id_list: Iterable[Any] | None = ..., *, field_name: str = ...) -> dict[Any, TModel]: ...

    def delete(self) -> int: ...

    def update(self, **kwargs: Any) -> int: ...

    def exists(self) -> bool: ...

    def explain(self, *, format: Any | None = ..., **options: Any) -> str: ...

    def contains(self, obj: TModel) -> bool: ...

    def values(self, *fields: str, **expressions: Any) -> TQuerySet: ...

    def values_list(self, *fields: str, flat: bool = ..., named: bool = ...) -> TQuerySet: ...

    def dates(self, field_name: str, kind: str, order: str = ...) -> TQuerySet: ...

    def datetimes(
        self,
        field_name: str,
        kind: str,
        order: str = ...,
        tzinfo: datetime.tzinfo | None = ...,
    ) -> TQuerySet: ...

    def none(self) -> TQuerySet: ...

    def all(self) -> TQuerySet: ...

    def filter(self, *args: Any, **kwargs: Any) -> TQuerySet: ...

    def exclude(self, *args: Any, **kwargs: Any) -> TQuerySet: ...

    def complex_filter(self, filter_obj: Any) -> TQuerySet: ...

    def union(self, *other_qs: TQuerySet, all: bool = ...) -> TQuerySet: ...

    def intersection(self, *other_qs: TQuerySet) -> TQuerySet: ...

    def difference(self, *other_qs: TQuerySet) -> TQuerySet: ...

    def select_for_update(
        self,
        nowait: bool = ...,
        skip_locked: bool = ...,
        of: Sequence[str] = ...,
        no_key: bool = ...
    ) -> TQuerySet: ...

    def select_related(self, *fields: Any) -> TQuerySet: ...

    def prefetch_related(self, *lookups: Any) -> TQuerySet: ...

    def annotate(self, *args: Any, **kwargs: Any) -> TQuerySet: ...

    def alias(self, *args: Any, **kwargs: Any) -> TQuerySet: ...

    def order_by(self, *field_names: Any) -> TQuerySet: ...

    def distinct(self, *field_names: Any) -> TQuerySet: ...

    def reverse(self) -> TQuerySet: ...

    def defer(self, *fields: Any) -> TQuerySet: ...

    def only(self, *fields: Any) -> TQuerySet: ...

    def using(self, alias: str | None) -> TQuerySet: ...


class OneToManyRelatedManager(ModelManager[TModel, TQuerySet]):
    """Simplified protocol of a manager for a one-to-many relation."""

    def __eq__(self, other: object) -> bool: ...

    def __hash__(self) -> int: ...

    def add(self, *objs: TModel | int, bulk: bool = ...) -> int: ...

    def remove(self, *obj: TModel | int, bulk: bool = ...) -> TModel: ...

    def clear(self, *, clear: bool = ...) -> None: ...

    def set(
        self,
        objs: TQuerySet | Iterable[TModel | int],
        *,
        bulk: bool = ...,
        clear: bool = ...,
    ) -> None: ...


class ManyToManyRelatedManager(ModelManager[TModel, TQuerySet]):
    """Simplified protocol of a manager for a many-to-many relation."""

    through: type[Model]

    def add(
        self,
        *objs: TModel | int,
        through_defaults: Mapping[str, Any] | None = ...,
    ) -> None: ...

    def remove(self, obj: TModel | int) -> None: ...

    def clear(self) -> None: ...

    def set(
        self,
        objs: TQuerySet | Iterable[TModel | int],
        *,
        clear: bool = ...,
        through_defaults: Mapping[str, Any] | None = ...,
    ) -> None: ...

    def create(
        self,
        through_defaults: Mapping[str, Any] | None = ...,
        **kwargs: Any,
    ) -> TModel: ...

    def get_or_create(
        self,
        defaults: Mapping[str, Any] | None = ...,
        through_defaults: Mapping[str, Any] | None = ...,
        **kwargs: Any,
    ) -> tuple[TModel, bool]: ...

    def update_or_create(
        self,
        defaults: Mapping[str, Any] | None = ...,
        create_defaults: Mapping[str, Any] | None = ...,
        through_defaults: Mapping[str, Any] | None = ...,
        **kwargs: Any,
    ) -> tuple[TModel, bool]: ...


class SerializableModelManagerMixin:
    def serialize(self) -> list[dict[str, Any]]: ...


class SerializableModelMixin:
    def serialize(self) -> list[dict[str, Any]]: ...
